eclipse-apoapsis/ort-server

api/v1/model/src/commonMain/kotlin/InfrastructureService.kt
api/v1/model/src/commonMain/kotlin/Organization.kt
api/v1/model/src/commonMain/kotlin/Product.kt
api/v1/model/src/commonMain/kotlin/Secret.kt
api/v1/model/src/commonMain/kotlin/validation/Constraints.kt
config/secret-file/src/main/kotlin/ConfigSecretFileProviderFactory.kt
dao/src/main/kotlin/tables/runs/advisor/DefectsTable.kt
dao/src/main/kotlin/tables/runs/repository/RepositoryAnalyzerConfigurationsTable.kt
dao/src/main/kotlin/tables/runs/shared/EnvironmentsTable.kt
model/src/commonMain/kotlin/InfrastructureService.kt
model/src/commonMain/kotlin/runs/scanner/Provenance.kt
model/src/commonMain/kotlin/validation/Constraints.kt
services/authorization/src/main/kotlin/DefaultAuthorizationService.kt
services/authorization/src/test/kotlin/DefaultAuthorizationServiceTest.kt
transport/kubernetes/src/main/kotlin/KubernetesSenderConfig.kt
transport/rabbitmq/src/main/kotlin/RabbitMqMessageReceiverFactory.kt
transport/rabbitmq/src/main/kotlin/RabbitMqMessageSenderFactory.kt
transport/spi/src/main/kotlin/Endpoint.kt
workers/common/src/main/kotlin/common/OrtMappings.kt
workers/common/src/main/kotlin/common/RunResult.kt

Address inspection hints

---

.github/renovate.json

Fine tune the Renovate config, see the commit messages for details.

Improve Renovate config

---

NOTICE

Keep entries sorted alphabetically.

chore: Add Double Open to the `NOTICE` file

---

workers/analyzer/src/main/kotlin/analyzer/AnalyzerRunner.kt
workers/analyzer/src/test/kotlin/AnalyzerRunnerTest.kt
workers/common/src/main/kotlin/common/context/WorkerContextFactory.kt
workers/common/src/main/kotlin/common/context/WorkerOrtConfig.kt
workers/common/src/test/kotlin/common/context/WorkerContextFactoryTest.kt
workers/common/src/test/kotlin/common/context/WorkerOrtConfigTest.kt

Refer to the single commits for further details.

Correctly set up ORT config in forked Analyzer worker

---

logaccess/loki/src/test/kotlin/LokiLogFileProviderTest.kt
storage/database/src/test/kotlin/LargeObjectsTest.kt
transport/kubernetes/src/test/kotlin/KubernetesMessageSenderFactoryTest.kt
workers/config/src/test/kotlin/ConfigValidatorTest.kt

Improve dealing with test resources

---

workers/common/src/main/kotlin/common/OrtMappings.kt
workers/common/src/main/kotlin/common/OrtServerMappings.kt
workers/common/src/test/kotlin/OrtServerMappingsTest.kt
workers/common/src/testFixtures/kotlin/OrtTestData.kt

Fix snippet choice

---

.mailmap

The last entry just corrects the user name.

chore(mailmap): Add two more mail mapping entries

---

workers/config/src/main/kotlin/ConfigWorker.kt
workers/config/src/test/kotlin/ConfigWorkerTest.kt

fix(config): Ignore a missing validation script

---

.github/workflows/build-and-test.yml

Upload the test result html to help finding issues with failing tests.

feat(ci): Upload test results as build artifacts

---

.github/renovate.json

Disable Helm updates and fix eclipse-temurin < 18

---

api/v1/model/src/commonMain/kotlin/JobConfigurations.kt
model/src/commonMain/kotlin/JobConfigurations.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerRunner.kt

Minor Analyzer improvements

---

core/src/main/kotlin/services/OrchestratorService.kt
dao/src/main/kotlin/repositories/DaoReporterJobRepository.kt
dao/src/main/kotlin/tables/ReporterJobsTable.kt
logaccess/loki/src/main/kotlin/LokiLogFileProvider.kt
logaccess/spi/src/main/kotlin/LogFileService.kt
secrets/vault/src/main/kotlin/VaultConfiguration.kt
services/hierarchy/src/main/kotlin/OrganizationService.kt
services/hierarchy/src/main/kotlin/ProductService.kt
services/hierarchy/src/main/kotlin/RepositoryService.kt
transport/kubernetes-jobmonitor/src/main/kotlin/Scheduler.kt
transport/kubernetes/src/main/kotlin/KubernetesSenderConfig.kt
workers/common/src/main/kotlin/common/context/WorkerContextImpl.kt
workers/scanner/src/main/kotlin/scanner/OrtServerScanResultStorage.kt

Address some inspection hints when running Detekt with type resolution

---

.detekt.yml
.github/workflows/static-analysis.yml
core/src/test/kotlin/Extensions.kt
core/src/test/kotlin/api/AbstractIntegrationTest.kt
logaccess/spi/src/main/kotlin/LogFileService.kt
workers/common/src/test/kotlin/common/env/EnvironmentServiceTest.kt
workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt

More Detekt with type resolution fixes

---

workers/notifier/src/test/kotlin/NotifierRunnerTest.kt

Test whether correct objects are passed to the constructor of `Notifier`.

test(notifier): Improve test for NotifierRunner

---

.github/workflows/build-and-test.yml
ui/pnpm-lock.yaml

This will reduce lockfile conflicts going forward.

Upgrade PNPM and the lockfile version

---

workers/analyzer/src/main/kotlin/analyzer/AnalyzerWorker.kt
workers/notifier/src/main/kotlin/notifier/NotifierRunner.kt
workers/reporter/src/main/kotlin/reporter/ReporterRunner.kt

Simplify some code, mostly to avoid non-null assertions

---

core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/api/RepositoriesRoute.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerRunner.kt
workers/reporter/src/main/kotlin/reporter/ReportNameMapper.kt
workers/scanner/src/main/kotlin/scanner/OrtServerScanResultStorage.kt

Avoid non-null assertions, part 1

---

.detekt.yml
.github/workflows/static-analysis.yml
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/main/kotlin/plugins/OpenApi.kt
dao/src/main/kotlin/Exceptions.kt
dao/src/main/kotlin/tables/ScanResultsTable.kt
dao/src/main/kotlin/tables/SnippetsTable.kt
dao/src/main/kotlin/tables/provenance/PackageProvenancesTable.kt
dao/src/main/kotlin/tables/runs/repository/PackageCurationDataTable.kt
dao/src/test/kotlin/tables/PackageProvenancesTableTest.kt
workers/common/src/main/kotlin/common/Extensions.kt
workers/common/src/main/kotlin/common/OrtMappings.kt

Avoid non null assertions, part 2

---

core/src/main/kotlin/api/RepositoriesRoute.kt

Introduce `jobSummaries` to simplify the code.

refactor(core): Introduce a local variable for job summaries

---

core/src/main/kotlin/plugins/HTTP.kt
core/src/main/resources/application.conf
core/src/test/resources/application-test-auth.conf
core/src/test/resources/application-test.conf
docker-compose.yml

refactor(cors): Disallow anyHost from CORS

---

ui/.gitignore
ui/src/components/providers.tsx

ui: Configure Server UI with environment variables

---

.github/workflows/docker-build.yml
README.md
docker-compose.yml

Make the Docker images and the API port configurable for Docker Compose. Please see the commit messages for details.

Add configuration options to Compose

---

scripts/docker/keycloak/master-realm.json
ui/README.md

While in longer term this should probably be done with Terraform/Pulumi, configure it with the JSON to ease development.

feat(compose): Auto-configure Keycloak in Docker Compose for UI

---

transport/kubernetes-jobmonitor/src/main/resources/logback.xml
transport/kubernetes/src/main/kotlin/KubernetesSenderConfig.kt

Refer to the single commits for further details.

Logging improvements

---

.github/workflows/build-and-test.yml

See [1].
[1]: https://github.com/pnpm/action-setup/releases/tag/v4.0.0

deps(github): Upgrade to `pnpm/action-setup` version 4

---

api/v1/model/src/commonMain/kotlin/Repository.kt
core/src/main/kotlin/plugins/Validation.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
dao/src/main/resources/db/migration/V65__removeUserInfoFromRepositoryUrl.sql
dao/src/test/kotlin/tables/CleanRepositoryUrlMigrationTest.kt
dao/src/testFixtures/kotlin/DatabaseMigrationTestExtension.kt
dao/src/testFixtures/kotlin/DatabaseTestExtension.kt

feat(backend): Add URL validation for `Repository`s 

---

orchestrator/src/main/kotlin/WorkerScheduleInfo.kt
orchestrator/src/test/kotlin/OrchestratorTest.kt

When checking whether a worker can be executed in the current phase of an ORT run, all its transitive dependencies must be taken into account. Otherwise, it can happen that it is started too early if its direct dependencies are configured to be skipped.
Fixes #236.

fix(orchestrator): Fix a problem in the scheduler algorithm

---

core/src/main/kotlin/api/RunsRoute.kt
dao/src/main/kotlin/tables/ScanSummariesTable.kt
dao/src/main/kotlin/tables/SnippetFindingsTable.kt
dao/src/main/kotlin/tables/runs/analyzer/AnalyzerRunsTable.kt
dao/src/main/kotlin/tables/runs/analyzer/ProjectsTable.kt
orchestrator/src/main/kotlin/WorkerScheduleInfo.kt
workers/common/src/main/kotlin/common/OrtRunService.kt

Address some chores

---

config/github/src/test/kotlin/GitHubConfigFileProviderTest.kt
core/src/test/kotlin/testutils/AuthenticationTestHelper.kt
secrets/file/src/main/kotlin/FileBasedSecretsProvider.kt
secrets/file/src/test/kotlin/FileBasedSecretStorageTest.kt
workers/common/src/main/kotlin/common/env/NpmRcGenerator.kt
workers/reporter/src/main/kotlin/reporter/ReportDownloadLinkGenerator.kt
workers/reporter/src/test/kotlin/reporter/ReportDownloadLinkGeneratorTest.kt

Use Kotlin's Base64 coding

---

clients/keycloak/src/main/kotlin/ClientHelper.kt
clients/keycloak/src/main/kotlin/DefaultKeycloakClient.kt
config/github/src/main/kotlin/GitHubConfigFileProvider.kt

Ktor chores

---

api/v1/mapping/build.gradle.kts
build.gradle.kts
core/src/main/kotlin/di/Module.kt
dao/src/main/kotlin/utils/JsonbSupport.kt
secrets/spi/build.gradle.kts
storage/database/build.gradle.kts
storage/s3/build.gradle.kts
storage/spi/build.gradle.kts
transport/rabbitmq/build.gradle.kts

Opt-in to `ExperimentalSerializationApi` automatically

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/components/ui/separator.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.create-run.tsx

ui: Improvements to the ORT Run creation page

---

.github/workflows/docker-build.yml
README.md
docker-compose.yml

Publish UI Docker image and add it to Docker Compose.
The image build was tested in a fork, the resulting image can be found here:
https://github.com/mnonnenmacher/ort-server/pkgs/container/ort-server-ui

Publish UI Docker image

---

storage/s3/build.gradle.kts
storage/s3/src/test/kotlin/S3StorageTest.kt

S3 test improvements

---

.reuse/dep5
CONTRIBUTING.md

Add an initial `CONTRIBUTING.md` describing how to sign the ECA, how to make contributions to the project, and how to become a committer.

docs: Add a contributing guide

---

transport/activemqartemis/build.gradle.kts
transport/activemqartemis/src/test/kotlin/ArtemisMessageReceiverFactoryTest.kt
transport/activemqartemis/src/test/kotlin/ArtemisMessageSenderFactoryTest.kt
transport/activemqartemis/src/test/kotlin/ArtemisTestContainer.kt
transport/rabbitmq/build.gradle.kts
transport/rabbitmq/src/test/kotlin/RabbitMqMessageReceiverFactoryTest.kt
transport/rabbitmq/src/test/kotlin/RabbitMqMessageSenderFactoryTest.kt
transport/rabbitmq/src/test/kotlin/RabbitMqTestContainer.kt
transport/spi/src/testFixtures/kotlin/Utils.kt

Transport test refactoring

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/JobConfigurations.kt
model/src/commonMain/kotlin/JobConfigurations.kt
workers/reporter/src/main/kotlin/reporter/ReporterRunner.kt
workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt

feat(reporter): Add support for how-to-fix texts

---

core/build.gradle.kts
orchestrator/build.gradle.kts
transport/kubernetes-jobmonitor/build.gradle.kts
workers/advisor/build.gradle.kts
workers/analyzer/build.gradle.kts
workers/config/build.gradle.kts
workers/evaluator/build.gradle.kts
workers/notifier/build.gradle.kts
workers/reporter/build.gradle.kts
workers/scanner/build.gradle.kts

Add Scaleway runtime dependencies

---

workers/common/src/main/kotlin/common/env/ConfigFileBuilder.kt
workers/common/src/main/kotlin/common/env/NpmRcGenerator.kt
workers/common/src/main/kotlin/common/env/YarnRcGenerator.kt
workers/common/src/test/kotlin/common/env/ConfigFileBuilderTest.kt
workers/common/src/test/kotlin/common/env/YarnRcGeneratorTest.kt

Refer to the individual commits for further information.

Yarn proxy support

---

workers/common/src/main/kotlin/common/env/ConfigFileBuilder.kt
workers/common/src/main/kotlin/common/env/MavenSettingsGenerator.kt
workers/common/src/test/kotlin/common/env/MavenSettingsGeneratorTest.kt

Create _proxies_ section in Maven configuration file _settings.xml_ as one additional method (next to environment variables like _HTTP_PROXY_ and system properties like _http.proxyHost_) for Java tools like Eclipse Tycho to find out which proxy to use for outgoing connections.
Such a <proxies> section typically looks as follows:
```
<settings ... >
...
<proxies>
<proxy>
<id>http-proxy</id>
<active>true</active>
<protocol>http</protocol>
<host>proxy.example.com</host>
<port>8080</port>
<nonProxyHosts>*.example.com|*.svc.cluster.local</nonProxyHosts>
</proxy>
<proxy>
<id>https-proxy</id>
<active>true</active>
<protocol>https</protocol>
<host>proxy.example.com</host>
<port>8080</port>
<nonProxyHosts>*.example.com|*.svc.cluster.local</nonProxyHosts>
</proxy>
</proxies>
</settings>
```

feat(workers): Create <proxies> section in settings.xml

---

docker-compose.yml
ui/README.md
ui/docker/UI.Dockerfile
ui/docker/entrypoint.sh
ui/docker/nginx.conf.template
ui/src/app.tsx

Improve configuration of UI Docker image

---

transport/kubernetes-jobmonitor/src/main/kotlin/JobHandler.kt
transport/kubernetes-jobmonitor/src/main/kotlin/LostJobsFinder.kt
transport/kubernetes-jobmonitor/src/main/kotlin/MonitorComponent.kt
transport/kubernetes-jobmonitor/src/main/resources/logback.xml
transport/kubernetes-jobmonitor/src/test/kotlin/JobHandlerTest.kt
transport/kubernetes-jobmonitor/src/test/kotlin/LostJobsFinderTest.kt
transport/kubernetes-jobmonitor/src/test/kotlin/MonitorComponentTest.kt
transport/spi/src/main/kotlin/Endpoint.kt
transport/spi/src/test/kotlin/EndpointTest.kt

Job monitor delete server jobs only

---

ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.create-run.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.runs.$runIndex.index.tsx

Add VCS path to UI

---

core/src/main/kotlin/services/OrchestratorService.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
dao/src/main/kotlin/Database.kt
services/infrastructure/build.gradle.kts
services/infrastructure/src/test/kotlin/InfrastructureServiceServiceTest.kt

Fix creating ORT runs concurrently

---

config/git/src/main/kotlin/GitConfigFileProvider.kt

Git config improvements

---

workers/common/src/main/kotlin/common/Extensions.kt
workers/common/src/test/kotlin/common/ExtensionsTest.kt
workers/evaluator/src/main/kotlin/evaluator/EvaluatorRunner.kt
workers/notifier/src/main/kotlin/notifier/NotifierRunner.kt
workers/reporter/src/main/kotlin/reporter/ReporterRunner.kt
workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt

reporter: Do not fail if no how to fix text provider script exists

---

workers/config/src/main/kotlin/ConfigComponent.kt
workers/config/src/main/kotlin/ConfigWorker.kt
workers/config/src/test/kotlin/ConfigWorkerTest.kt

Fix config worker without validation script

---

README.md
build.gradle.kts

README improvements

---

config/github/src/main/kotlin/GitHubConfigCache.kt
config/github/src/main/kotlin/GitHubConfigFileCache.kt
config/github/src/main/kotlin/GitHubConfigFileProvider.kt
config/github/src/main/kotlin/GitHubConfigNoCache.kt
config/github/src/test/kotlin/GitHubConfigFileCacheTest.kt
config/github/src/test/kotlin/GitHubConfigFileProviderTest.kt
config/github/src/test/kotlin/GitHubConfigNoCacheTest.kt
workers/advisor/src/main/resources/application.conf
workers/analyzer/src/main/resources/application.conf
workers/config/src/main/resources/application.conf
workers/evaluator/src/main/resources/application.conf
workers/notifier/src/main/resources/application.conf
workers/reporter/src/main/resources/application.conf
workers/scanner/src/main/resources/application.conf

This PR further improves the support for caching for `GitHubConfigFileProvider`. The content of folders is now cached as well, and the cache is periodically cleaned.

GitHub caching

---

core/src/main/kotlin/api/RunsRoute.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt

Runs route chores

---

.github/workflows/docker-build.yml

Add Java variants to Docker builds

---

ui/src/app.tsx
ui/src/components/loading-indicator.tsx
ui/src/routes/_layout/index.tsx
ui/src/routes/_layout/organizations/$orgId.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.runs.$runIndex.index.tsx

UI: Indicate loading state properly to the user

---

ui/src/routes/_layout/index.tsx
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

ui: Fix DOM errors for index pages

---

ui/src/app.tsx
ui/src/components/header.tsx
ui/src/hooks/useUser.ts
ui/src/routes/_layout/admin/index.tsx
ui/src/routes/_layout/admin/route.tsx

Improvements to user hooks and admin guarding

---

.github/workflows/docker-build.yml

ci: Fix Docker images tags

---

ui/src/routes/_layout/create-organization.tsx
ui/src/routes/_layout/organizations/$orgId/create-product.tsx
ui/src/routes/_layout/organizations/$orgId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/create-repository.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

Please see the commit message for details.

feat(ui): Add entity names to some toast messages

---

ui/src/routes/_layout/about/index.tsx

feat(ui): Show version information on about page

---

ui/src/components/header.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx
ui/src/routes/_layout/runs/$runId/index.tsx

Add shortcut to ORT run details page

---

ui/src/routes/_layout/create-organization.tsx
ui/src/routes/_layout/organizations/$orgId/create-product.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/create-repository.tsx

feat(ui): Redirect to detail pages after creating new entities

---

ui/src/components/header.tsx

Minor about menu improvements

---

ui/src/helpers/get-run-duration.ts

Also show days as part of the duration 

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx

fix(ui): Fix Notifier rerun and uncontrolled->controlled errors

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx

This is a critical fix for the UI, so a quick review would be very appreciated.
Please see the commit message for details.

fix(ui): Wrong base default value given in Notifier config

---

api/v1/model/src/commonMain/kotlin/JobConfigurations.kt
model/src/commonMain/kotlin/JobConfigurations.kt

Job config chores

---

ui/src/app.tsx
ui/src/components/data-table/data-table-pagination.tsx
ui/src/components/data-table/data-table.tsx
ui/src/routes/_layout/index.tsx
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx
ui/src/schemas/index.ts

Please see individual commit messages for details.
As discussed in the frontend alignment meeting, the lists are rendered as before.

ui: Implement pagination for lists

---

docker-compose.yml
scripts/compose/secrets-provider/.gitignore
scripts/requests/organizations.http

Fix compose secrets provider configuration

---

orchestrator/src/main/kotlin/Orchestrator.kt
orchestrator/src/test/kotlin/OrchestratorTest.kt

The orchestrator adds an `Issue` to the current `OrtRun` whenever it receives an error message from a worker. This helps to track any failures that occur.

feat(orchestrator): Add an `Issue` to the `OrtRun` in case of a failure

---

workers/analyzer/docker/Analyzer.Dockerfile

Align with ORT (see [1]).
[1]: https://github.com/oss-review-toolkit/ort/pull/8909/commits/0c06c18c7cb231ce48f40f04a49ef5c382f53e76

chore(docker): Replace Bazel by Bazelisk

---

workers/reporter/src/main/kotlin/reporter/SourceCodeBundleReporter.kt
workers/reporter/src/test/kotlin/reporter/SourceCodeBundleReporterTest.kt

`SourceCodeBundleReporter` used to ignore the `path` attribute in the VCS info of packages downloaded from a source code repository. Therefore, the source code archives for such packages included the whole content of the repository. Fix this by checking for a path, and only including files that are direct or indirect children of this path.

fix(reporter): Handle sub paths in the source code bundle reporter

---

workers/config/src/main/kotlin/ConfigValidator.kt
workers/config/src/main/kotlin/ValidationScriptTemplate.kt

This reverts commit 43767ba until [1] is resolved.
[1]: https://youtrack.jetbrains.com/issue/KTIJ-30059

Revert "refactor(config): Migrate from `constructorArgs` to `providedProperties`"

---

ui/src/routes/_layout/about/index.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/$serviceName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/reports/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/index.tsx

ui: Fix query keys and route loaders

---

.github/workflows/static-analysis.yml
dao/src/testFixtures/kotlin/Fixtures.kt
storage/spi/src/testFixtures/kotlin/StorageProviderFactoryForTesting.kt
workers/common/src/testFixtures/kotlin/OrtTestData.kt

Address remaining Detekt issues

---

dao/src/main/kotlin/repositories/DaoOrtRunRepository.kt

The code to determine the next run index when creating a new ORT run was unnecessarily loading the complete list of ORT runs for the repository and mapping it to the business model. Therefore a lot of unnecessary data was loaded not only from the `ort_runs` table, but also from associated tables like `labels` or `issues`.
To fix this, replace the call to `listForRepository` with a custom query that loads only the last index. This increases performance especially for repositories with a lot of runs and makes it also a lot less likely that the transaction has to be reattempted when runs are created concurrently.

fix(dao): Do not load unnecessary data when creating ORT run

---

workers/analyzer/docker/Analyzer.Dockerfile

This is required to align with ORT (see [1]).
[1]: https://github.com/oss-review-toolkit/ort/pull/9001

feat(docker): Add `Buildozer` to the Analyzer worker Docker image

---

ui/src/routes/_layout/about/index.tsx

Make it look a bit similar to [1].
[1]: https://v0.dev/t/LoBns0Spg7G

feat(ui): Beautify the look of version information a bit

---

ui/src/components/data-table/data-table-pagination.tsx

ui: Remove the unnecessary spinners from table pagination component

---

core/src/main/kotlin/api/RunsRoute.kt
logaccess/spi/src/main/kotlin/LogSource.kt
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx
workers/analyzer/src/main/kotlin/analyzer/AnalyzerWorker.kt

Improve downloading of logs

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/EnvironmentVariableDeclaration.kt
model/src/commonMain/kotlin/EnvironmentVariableDeclaration.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerRunner.kt
workers/analyzer/src/test/kotlin/AnalyzerRunnerTest.kt
workers/common/src/main/kotlin/common/env/config/EnvironmentConfigLoader.kt
workers/common/src/main/kotlin/common/env/config/RepositoryEnvironmentVariableDefinition.kt
workers/common/src/main/kotlin/common/env/definition/EnvironmentVariableDefinition.kt
workers/common/src/test/kotlin/common/env/config/EnvironmentConfigLoaderTest.kt
workers/common/src/test/resources/.ort.env.direct-variables.yml

Add option to define non-secret Env Variables in .ort.yml

Non secret env variables

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx

ui: Choose the log level for ORT Run logs

---

ui/src/components/ort-run-job-status.tsx
ui/src/components/run-duration.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

Please have a look at the individual commits.
Resolves #833.

Show the ongoing duration for active runs

---

core/src/main/kotlin/plugins/Lifecycle.kt
transport/kubernetes-jobmonitor/build.gradle.kts
transport/kubernetes-jobmonitor/src/main/kotlin/Scheduler.kt

Fix role sync and jobmonitor issues

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

feat(ui): Add a dedicated button to view a run's details

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/app.tsx
ui/src/components/providers.tsx
ui/src/config.ts
ui/src/hooks/use-user.ts
ui/src/routes/_layout/admin/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx
ui/src/ui-env.ts

ui: Refactor UI config

---

ui/src/components/sidebar.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/logs/index.tsx

ui: Implement log downloading for the runs2 route

---

ui/src/routes/_layout/create-organization.tsx
ui/src/routes/_layout/index.tsx
ui/src/routes/_layout/organizations/$orgId/create-product.tsx
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/create-repository.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx

From a user perspective, these are not "new" and do not need to be "created", but the UI just refers to existing repositories etc.
So to avoid any confusion, use "Add" instead of "Create" or "New".

docs(ui): Align on "Add" as the term for adding hierarchy elements

---

ui/src/routes/_layout/organizations/$orgId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/$serviceName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/$secretName/edit.tsx

ui: Enter key submits also the edit forms

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx

ui: Include traffic lights in ORT Run results page

---

ui/src/routes/_layout/create-organization.tsx
ui/src/routes/_layout/organizations/$orgId/create-product.tsx
ui/src/routes/_layout/organizations/$orgId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/$serviceName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/create.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/create-repository.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/create-secret.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/create-secret.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/create-secret.tsx

ui: Improve form readability

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx

ui: Align labels and parameters in ORT Run context information

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/route.tsx
ui/src/routes/_layout/organizations/$orgId/route.tsx

ui: Add some icons to sidebars

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/components/header.tsx
ui/src/components/ui/avatar.tsx
ui/src/hooks/use-user.ts

ui: Display the (user)name of the currently logged in user

---

.detekt.license.template
core/build.gradle.kts
core/src/main/kotlin/plugins/OpenApi.kt
core/src/test/kotlin/utils/GenerateOpenApiSpec.kt
gradle/libs.versions.toml
ui/src/components/ort-run-job-status.tsx

Apply some fixes to make the generated OpenAPI pass validation with https://apitools.dev/swagger-parser/online/. See the commit messages for details.

Fix issues in OpenAPI spec

---

ui/src/routes/_layout/about/index.tsx
ui/src/routes/_layout/admin/index.tsx
ui/src/routes/_layout/index.tsx
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/config/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/issues/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/logs/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/reports/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/index.tsx

ui: Use custom hooks for queries

---

ui/src/components/toast-error.tsx
ui/src/routes/__root.tsx
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/index.tsx

ui: Fix pagination on tables

---

ui/src/components/data-table/data-table.tsx
ui/src/helpers/calc-overall-vulnerability.ts
ui/src/helpers/get-status-colors.ts
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx
ui/src/types/status-types-and-constants.ts

ui: Show vulnerabilities

---

workers/analyzer/src/main/kotlin/analyzer/AnalyzerWorker.kt
workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/analyzer/src/test/kotlin/AnalyzerWorkerTest.kt
workers/common/src/main/kotlin/common/env/EnvironmentService.kt
workers/common/src/main/kotlin/common/env/config/EnvironmentConfigLoader.kt
workers/common/src/test/kotlin/common/env/EnvironmentServiceTest.kt
workers/common/src/test/kotlin/common/env/config/EnvironmentConfigLoaderTest.kt

feat(analyzer): Enhance environment setup

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx

ui: Add proper error handling to vulnerabilities page

---

.github/workflows/build-and-test.yml
.github/workflows/static-analysis.yml
.github/workflows/website-test.yml

Add a workflow to test the website build

---

.github/workflows/website-test.yml

ci: Run the website-test also in the merge queue

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx

@mnonnenmacher this is an easy & quick first fix for showing the vulnerability descriptions.

fix(ui): Fix line breaks in vulnerability descriptions

---

ui/src/components/data-table/data-table.tsx
ui/src/routes/_layout/index.tsx
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/index.tsx

ui: Get rid of violating props passed to DOM elements

---

ui/src/components/statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx

ui: Add basis for progress information of an ORT Run

---

core/src/main/kotlin/plugins/HTTP.kt

Add PUT to the allowed methods in CORS config

---

scripts/docker/keycloak/master-realm.json

Compose: Do not map client roles to access token

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/users/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/users/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/users/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/users/route.tsx
ui/src/routes/_layout/organizations/$orgId/route.tsx
ui/src/routes/_layout/organizations/$orgId/users/index.tsx
ui/src/routes/_layout/organizations/$orgId/users/route.tsx
ui/src/schemas/index.ts

Please note that this implementation is pretty crude: the admin needs to fill in the usernames manually, and they need to exist in Keycloak, see issue #1055.
Resolves #1031.

Add an admin UI for adding / removing users from groups

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/analyzer-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/config/-components/analyzer-job-details.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx

ui: Add support for repository configuration path to ORT Runs

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/Package.kt
api/v1/model/src/commonMain/kotlin/ProcessedDeclaredLicense.kt
api/v1/model/src/commonMain/kotlin/RemoteArtifact.kt
api/v1/model/src/commonMain/kotlin/VcsInfo.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/main/kotlin/di/Module.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/tables/runs/analyzer/PackagesTable.kt
scripts/requests/runs.http
services/hierarchy/src/main/kotlin/PackageService.kt
services/hierarchy/src/test/kotlin/PackageServiceTest.kt

Please see the individual commit messages for details.

Add endpoint to get packages found in an ORT run

---

workers/reporter/src/main/kotlin/reporter/ReporterWorker.kt
workers/reporter/src/test/kotlin/reporter/ReporterWorkerTest.kt

If the Analyzer worker has failed, the Reporter fails as well because it tries to obtain VCS information which is not available. The generated notifications then state that the run failed in the phases Analyzer and Reporter. Because this is misleading, the Reporter worker should handle this case gracefully, i.e. go to the `FINISHED_WITH_ISSUES` state instead.

fix(reporter): Do not crash the reporter if there is no analyzer result

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-create-run-utils.ts

ui: Don't send an empty repository configuration path to the back-end

---

workers/advisor/src/main/kotlin/advisor/AdvisorWorker.kt
workers/analyzer/src/test/kotlin/AnalyzerWorkerTest.kt
workers/config/src/test/kotlin/ConfigWorkerTest.kt
workers/evaluator/src/main/kotlin/evaluator/EvaluatorWorker.kt
workers/notifier/src/main/kotlin/notifier/NotifierWorker.kt
workers/notifier/src/test/kotlin/NotifierEndpointTest.kt
workers/reporter/src/main/kotlin/reporter/ReporterWorker.kt
workers/scanner/src/main/kotlin/scanner/ScannerWorker.kt

Coroutine chores

---

ui/src/helpers/calc-overall-vulnerability.ts
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx

NOTE: The vulnerability view could, with the additional data now available, also be developed into something more visual and useful in a future PR.

ui: Fix vulnerability details view

---

ui/src/routes/_layout/admin/index.tsx

This is the frond-end counterpart of #1114.

ui: Add a form for creating a new user

---

config/github/src/main/kotlin/GitHubConfigFileCache.kt
config/github/src/test/kotlin/GitHubConfigFileCacheTest.kt

It is not clear why it was implemented with a probabilistic approach in the first place, so change the implementation to deterministically perform the cleanup at the configured ratio. This improves test stability as it was not possible to guarantee that the tests would succeed with the previous approach.

refactor(github): Make `cleanupRatio` deterministic

---

core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
dao/src/main/kotlin/tables/runs/evaluator/RuleViolationsTable.kt

Please have a look at the commit for details.

Implement sorting for rule violations endpoint

---

buildSrc/src/main/kotlin/ort-server-publication-conventions.gradle.kts

Improve the publishing configuration as a preparation to create the release workflow for Maven Central.

Improve publishing configuration

---

.github/workflows/build-and-test.yml
.github/workflows/docker-build.yml
.github/workflows/publish-artifacts.yml
.github/workflows/release.yml
.github/workflows/static-analysis.yml

Add a release workflow, see the commit messages for details.

Release workflow

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/VcsInfo.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
dao/src/main/resources/db/migration/V80__fixGitVcsInfoType.sql

Fixes for handling unknown VCS types in the API

---

build.gradle.kts

The previous implementation had the problem that pre-releases always got the revision appended. Also, the logic to remove the pre-release identifier did not work with versioned pre-releases like "RC1".
Fix this by completely customizing the logic to determine the version:
- Releases only contain the semantic version, like "1.2.3".
- Pre-releases additionally contain the pre release version, like "1.2.3-RC1".
- Commits ahead of the last release tag get the commit count and revision appended, like "1.2.3-RC1.001.sha.0123456".
The implementation is more verbose than before but makes it easier to understand how the version is constructed.

build: Customize the logic to determine the version

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/OrtRun.kt
api/v1/model/src/commonMain/kotlin/OrtRunSummary.kt
build.gradle.kts
core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/main/kotlin/services/OrchestratorService.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/DaoOrtRunRepository.kt
dao/src/main/kotlin/tables/OrtRunsTable.kt
dao/src/main/resources/db/migration/V81__addEnvironmentConfigPath.sql
dao/src/test/kotlin/repositories/DaoOrtRunRepositoryTest.kt
dao/src/test/kotlin/utils/ListQueryTest.kt
dao/src/testFixtures/kotlin/Fixtures.kt
model/src/commonMain/kotlin/OrtRun.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
orchestrator/src/test/kotlin/OrchestratorEndpointTest.kt
workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/common/src/main/kotlin/common/env/EnvironmentService.kt
workers/common/src/main/kotlin/common/env/config/EnvironmentConfigLoader.kt
workers/common/src/test/kotlin/OrtServerMappingsTest.kt
workers/common/src/test/kotlin/common/env/EnvironmentServiceTest.kt
workers/common/src/test/kotlin/common/env/config/EnvironmentConfigLoaderTest.kt

Allow to specify an alternative ort.env.yml file path 

---

.github/workflows/release.yml

Release improvements

---

ui/src/components/data-table/data-table.tsx
ui/src/components/delete-dialog.tsx
ui/src/components/ort-run-job-status.tsx
ui/src/components/providers.tsx
ui/src/routes/_layout/index.tsx
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/index.tsx

ui: Wrap the UI app with tooltip provider

---

.github/workflows/release.yml

Release changes

---

.github/workflows/publish-website.yml
.github/workflows/website-test.yml
core/src/main/kotlin/apiDocs/AdminDocs.kt
website/README.md
website/api/.gitignore
website/docusaurus.config.ts
website/package.json
website/pnpm-lock.yaml
website/sidebarsApi.ts

Add the API docs to the website, see the commit messages for details.

Show the OpenAPI spec on the website

---

ui/src/routes/_layout/admin/index.tsx
ui/src/routes/_layout/admin/route.tsx
ui/src/routes/_layout/admin/users/authorization.tsx
ui/src/routes/_layout/admin/users/create-user.tsx

ui: Align admin dashboard layout with the rest of the UI

---

ui/src/components/ort-run-job-status.tsx
ui/src/components/run-duration.tsx
ui/src/routes/_layout/admin/runs/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/last-job-status.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/last-run-date.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/last-run-status.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

ui: Add refetch intervals and update duration more frequently for running jobs

---

.github/workflows/build-and-test.yml
.github/workflows/docker-build.yml
.github/workflows/publish-artifacts.yml
.github/workflows/static-analysis.yml
REUSE.toml
build.gradle.kts
buildSrc/src/main/kotlin/ort-server-kotlin-jvm-conventions.gradle.kts
gradle.properties
gradle/gradle-daemon-jvm.properties
gradle/libs.versions.toml
settings.gradle.kts
workers/analyzer/docker/Analyzer.Dockerfile
workers/config/docker/Config.Dockerfile
workers/evaluator/docker/Evaluator.Dockerfile
workers/notifier/docker/Notifier.Dockerfile
workers/reporter/docker/Reporter.Dockerfile
workers/scanner/docker/Scanner.Dockerfile

Build all artifacts with Java 21.

Upgrade Java version for ORT Server to 21

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-create-run-utils.ts

fix(ui): Fix the form schema for new ORT runs

---

CONTRIBUTING.md

docs: Add some important rules to Contributing Guide

---

ui/src/components/ui/badge-variants.ts
ui/src/routes/_layout/admin/runs/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/last-run-status.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/issues/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx

ui: Tune badge colors

---

ui/src/helpers/calc-overall-vulnerability.ts
ui/src/helpers/get-status-class.ts
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx

ui: Fix calculation of the overall vulnerability rating

---

ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/total-runs.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx

ui: Display number of ORT runs in some views

---

ui/src/components/markdown-renderer.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/rule-violations/index.tsx

ui: Markdown tweaks

---

ui/src/components/data-table/data-table.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx
ui/src/schemas/index.ts

Please have a look at the commits for details.

ui: Sort vulnerabilities table

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/issues/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx

Plus / minus icons for buttons feel too much like add / remove.

chore(ui): Use chevron icons to expand / collapse panels

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/packages/index.tsx

ui: Show first crude version of packages table

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/packages/index.tsx

This is a follow-up for #1380.

ui: Show more package information

---

ui/src/helpers/calc-overall-vulnerability.ts
ui/src/helpers/get-status-class.ts
ui/src/helpers/identifier-to-string.ts
ui/src/helpers/sorting-functions.ts
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/issues/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/packages/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx

This is a repetition of an earlier PR (#1386), with change requests addressed.

ui: Table sorting and improvements

---

ui/src/config.ts

See https://github.com/authts/react-oidc-context/issues/1386.
Resolves #1400.

fix(ui): Remove authentication parameters from URL after signing in

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/rule-violations/index.tsx

Small refactoring, see commits.

Small rule violation table refactoring

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/advisor-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/analyzer-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/evaluator-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/notifier-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/reporter-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/scanner-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-create-run-utils.ts
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx

ui: Improve error handling in ORT Run creation form

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/components/markdown-renderer.tsx
ui/tailwind.config.js

Example of rule violation markdown:
Example of vulnerability markdown:

ui: Improve markdown rendering

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/issues/index.tsx

fix(ui): Fix a breaking layout

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

ui: Use columnHelper in runs overview table

---

config/github/README.md
config/github/src/main/kotlin/GitHubConfigFileProvider.kt
config/github/src/test/kotlin/GitHubConfigFileProviderTest.kt

Get the default branch for the GitHub config provider from the API 

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/EcosystemStats.kt
api/v1/model/src/commonMain/kotlin/OrtRunStatistics.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
model/src/commonMain/kotlin/EcosystemStats.kt
services/hierarchy/src/main/kotlin/IssueService.kt
services/hierarchy/src/main/kotlin/PackageService.kt
services/hierarchy/src/main/kotlin/RuleViolationService.kt
services/hierarchy/src/main/kotlin/VulnerabilityService.kt
services/hierarchy/src/test/kotlin/IssueServiceTest.kt
services/hierarchy/src/test/kotlin/PackageServiceTest.kt
services/hierarchy/src/test/kotlin/RuleViolationServiceTest.kt
services/hierarchy/src/test/kotlin/VulnerabilityServiceTest.kt

Add statistics endpoint

---

ui/src/routes/_layout/admin/index.tsx
ui/src/routes/_layout/admin/runs/index.tsx
ui/src/routes/_layout/admin/users/index.tsx
ui/src/routes/_layout/index.tsx
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/issues/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/packages/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/index.tsx
ui/src/schemas/index.ts

refactor(ui): Align validation schemas

---

config/build.gradle.kts
logaccess/build.gradle.kts
secrets/build.gradle.kts
storage/build.gradle.kts
transport/build.gradle.kts

build: Set group id for platform modules

---

core/src/main/resources/application.conf
dao/src/main/resources/application.conf
kubernetes/jobmonitor/src/main/resources/application.conf
orchestrator/src/main/resources/application.conf
secrets/file/src/main/resources/application.conf
secrets/scaleway/src/main/resources/application.conf
secrets/spi/src/main/resources/application.conf
secrets/vault/src/main/resources/application.conf
workers/advisor/src/main/resources/application.conf
workers/analyzer/src/main/resources/application.conf
workers/config/src/main/resources/application.conf
workers/evaluator/src/main/resources/application.conf
workers/notifier/src/main/resources/application.conf
workers/reporter/src/main/resources/application.conf
workers/scanner/src/main/resources/application.conf

This PR reduces redundancy in configuration settings by moving shared settings to the modules that define them.

Deduplicate configuration settings

---

api/v1/model/src/commonMain/kotlin/InfrastructureService.kt
api/v1/model/src/commonMain/kotlin/Organization.kt
api/v1/model/src/commonMain/kotlin/Product.kt
api/v1/model/src/commonMain/kotlin/Repository.kt
api/v1/model/src/commonMain/kotlin/Secret.kt
api/v1/model/src/commonMain/kotlin/validation/ValidationHelper.kt

Update code that uses Konform API that was deprecated in 0.9.0 [1].
[1]: https://github.com/konform-kt/konform/releases/tag/v0.9.0

chore(api): Address depecrations of the Konform library

---

ui/src/config.ts
ui/src/helpers/calc-overall-vulnerability.ts
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/last-job-status.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/last-run-date.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/last-run-status.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/total-runs.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/package-manager-field.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/analyzer-job-details.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx
ui/tsconfig.json

This requires possible undefined values to be handled if accessing items in
arrays with index numbers, which makes the codebase a lot more type-safe.

build(ui): Forbid unchecked indexed access with TypeScript

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

For some reason using the query directly sometimes froze the navigation.
Using the query client fixes it, but then a query invalidation is needed to
always have fresh data.
This is a fixup for aa31b4b.

fix(ui): Fix router getting stuck when redirecting to latest run

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

Fix back button when redirecting to latest run

---

workers/common/src/main/kotlin/common/OrtRunService.kt
workers/common/src/test/kotlin/common/OrtRunServiceTest.kt

The scanner does not take care for the VCS path of a repository provenance, it just scans **everything** and puts the scan results to persistent storage (scanner cache). This is the desired behaviour and nothing wrong about it.
But when scan results from this persistent storage are used, scanner findings outside the VCS path must be filtered before further processing.
For solving the issue, the first step was to isolate the respective code sections in ORT to a Util class.
With this change, re-use this code from the Util class in ORT Server in order to filter out scan results outside the VCS path. This ensures that ORT Server behaves in exactly the same way as ORT regarding scan results.

fix(reporter): Filter out scan results outside the VCS path

---

ui/src/routes/_layout/admin/runs/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/repository-runs-table.tsx

Create a more slick UI by removing the titles, the icons and tooltips should be enough. This makes room for more actions in the column, like deleting runs.

style(ui): Remove the titles from actions to only have icons

---

model/src/commonMain/kotlin/InfrastructureService.kt

This is a follow-up to f165294.

chore(model): Address another Konform deprecation

---

ui/src/components/markdown-renderer.tsx
ui/tailwind.config.js

fix(ui): Fix code block rendering

---

ui/src/components/header.tsx

Link to all runs from breadcrumb's repository url

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/index.tsx

fix(ui): Fix missing link

---

.github/CODEOWNERS

chore(github): Add Johanna to the list of UI code owners

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/secrets/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/routes/organizations/$orgId/secrets/index.tsx

fix(ui): Fix invalidation of secrets query cache

---

ui/src/components/delete-dialog.tsx
ui/src/routes/admin/users/index.tsx
ui/src/routes/organizations/$orgId/index.tsx
ui/src/routes/organizations/$orgId/infrastructure-services/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/secrets/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/settings/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/routes/organizations/$orgId/secrets/index.tsx

Simplify delete dialog

---

ui/src/components/delete-icon-button.tsx
ui/src/routes/organizations/$orgId/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/repository-runs-table.tsx

ui: Delete ORT runs

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/repository-runs-table.tsx

This is a specific run to delete.

chore(ui): Say "the run" instead of "a run" in deletion confirmation

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/reports/index.tsx

ui: Truncate long report filename

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/logs/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/reports/index.tsx

fix(ui): Do not download corrupt logs or reports

---

api/v1/client/build.gradle.kts
api/v1/client/src/commonMain/kotlin/HttpClientUtils.kt
api/v1/client/src/commonMain/kotlin/OrtServerClient.kt
api/v1/client/src/commonMain/kotlin/OrtServerClientConfig.kt
api/v1/client/src/commonMain/kotlin/api/RepositoriesApi.kt
api/v1/client/src/commonTest/kotlin/AuthServiceTest.kt
api/v1/client/src/commonTest/kotlin/RepositoriesApiTest.kt
api/v1/client/src/commonTest/kotlin/TestUtils.kt
cli/build.gradle.kts
cli/src/main/kotlin/OrtServerMain.kt
cli/src/main/kotlin/RunsCommand.kt
cli/src/main/kotlin/StartCommand.kt
cli/src/test/kotlin/StartCommandTest.kt

Add command to create an `OrtRun`

---

workers/advisor/build.gradle.kts
workers/advisor/src/main/resources/application.conf
workers/analyzer/build.gradle.kts
workers/analyzer/src/main/resources/application.conf
workers/common/build.gradle.kts
workers/common/src/main/kotlin/common/OrtRunService.kt
workers/common/src/main/kotlin/common/OrtRunServiceModule.kt
workers/common/src/main/kotlin/common/OrtServerFileListStorage.kt
workers/common/src/main/kotlin/common/Utils.kt
workers/common/src/main/resources/application.conf
workers/common/src/test/kotlin/common/OrtRunServiceTest.kt
workers/common/src/test/kotlin/common/OrtServerFileListStorageTest.kt
workers/common/src/test/kotlin/common/UtilsTest.kt
workers/config/src/main/resources/application.conf
workers/evaluator/src/main/kotlin/evaluator/EvaluatorWorker.kt
workers/evaluator/src/main/resources/application.conf
workers/evaluator/src/test/kotlin/EvaluatorWorkerTest.kt
workers/notifier/build.gradle.kts
workers/notifier/src/main/resources/application.conf
workers/reporter/src/main/resources/application.conf
workers/scanner/src/main/kotlin/scanner/ScannerComponent.kt
workers/scanner/src/main/kotlin/scanner/ScannerRunner.kt
workers/scanner/src/main/resources/application.conf

Support adding file lists to generated ORT results. See the commit messages for details.

Add file lists to generated ORT results

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx

Do not just omit source artifact information.

feat(ui): Make it explicit is a package is metadata-only

---

dao/src/main/kotlin/utils/Extensions.kt
model/src/commonMain/kotlin/VulnerabilityRating.kt
model/src/commonMain/kotlin/VulnerabilityWithAccumulatedData.kt
services/hierarchy/src/main/kotlin/VulnerabilityService.kt
services/hierarchy/src/test/kotlin/VulnerabilityServiceTest.kt

Add function to get vulnerabilities for ORT runs

---

workers/common/src/main/kotlin/common/OrtRunService.kt

File lists for repository provenances are always created for the full repositories, ignoring any VCS path. This means that the VCS paths must be removed from repository provenances before requesting the file lists from the storage. It also means that file lists must be filtered by the VCS paths so that no unnecessary entries are added to the created ORT result.
This is a fixup for e047d5a.

fix(workers): Fix the handling of file lists

---

ui/src/helpers/item-counts.ts
ui/src/hooks/use-issues-by-product-suspense.ts
ui/src/hooks/use-packages-by-product-suspense.ts
ui/src/hooks/use-violations-by-product-suspense.ts
ui/src/hooks/use-vulnerabilities-by-product-suspense.ts
ui/src/lib/constants.ts
ui/src/routes/organizations/$orgId/infrastructure-services/$serviceName/edit/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-issues-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-packages-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-violations-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-vulnerabilities-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/issues-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/packages-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/rule-violations-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/vulnerabilities-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx

ui: Tune and clean up ORT Run results page

---

ui/src/components/data-table/data-table-body.tsx
ui/src/components/data-table/data-table-header.tsx
ui/src/components/data-table/data-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/-components/product-vulnerability-table.tsx

To assist in further feature implementation for all data tables, divide the table into header and body subcomponents. This doesn't affect the UI.

refactor(ui): Refactor data table

---

.github/workflows/docker-build.yml

Run the Docker builds also as part of PR checks, see the commit messages for details.

ci: Run the Docker build as part of PR checks

---

scripts/docker/keycloak/HealthCheck.java
scripts/docker/keycloak/master-realm.json

This will have to be rebased after #1643 was merged.
@lamppu @Etsija FYI

Fix Keycloak health check in Compose

---

ui/src/routes/organizations/$orgId/products/$productId/-components/product-repository-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/-components/product-vulnerability-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/index.tsx

refactor(ui): Refactor product overview and product vulnerabilities pages

---

.github/workflows/docker-build.yml

Fix Docker cache for PRs

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/ProductVulnerability.kt
api/v1/model/src/commonMain/kotlin/VulnerabilityRating.kt
core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/apiDocs/ProductsDocs.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
dao/src/testFixtures/kotlin/Fixtures.kt
services/hierarchy/src/main/kotlin/ProductService.kt
services/hierarchy/src/test/kotlin/ProductServiceTest.kt
services/hierarchy/src/test/kotlin/VulnerabilityServiceTest.kt

Add endpoint to get vulnerabilities for a product

---

ui/src/routes/organizations/$orgId/products/$productId/-components/product-vulnerabilities-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/-components/product-vulnerability-table.tsx

ui: Use API endpoint for product vulnerabilities

---

website/docs/getting-started/docker-compose.md
website/docusaurus.config.ts

Website: Fix broken anchors

---

api/v1/model/src/commonMain/kotlin/OrtRunStatistics.kt
core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/ProductsDocs.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/testFixtures/kotlin/Fixtures.kt

Add run statistics endpoint for products

---

workers/analyzer/docker/Analyzer.Dockerfile
workers/scanner/docker/Scanner.Dockerfile

Align casing in Dockerfile:
The 'as' keyword should match the case of the 'from' keyword.

chore(docker): Align casing in Dockerfiles

---

ui/src/routes/organizations/$orgId/-components/organization-product-table.tsx
ui/src/routes/organizations/$orgId/-components/organization-products-statistics-card.tsx
ui/src/routes/organizations/$orgId/index.tsx

This PR starts the implementation of the organization-level dashboard, to pave way for future implementation and align the UI look-and-feel.

ui: Initial organization dashboard

---

ui/src/routes/runs/$runId/index.tsx

fix(ui): Fix one redirect

---

ui/src/components/header.tsx

ui: Set page titles

---

core/src/main/resources/logback.xml
dao/src/testFixtures/resources/logback-test.xml
docker-compose.yml
kubernetes/jobmonitor/src/main/resources/logback.xml
logaccess/loki/src/main/kotlin/LokiLogFileProvider.kt
logaccess/loki/src/test/kotlin/LokiLogFileProviderTest.kt
logaccess/spi/src/main/kotlin/LogSource.kt
orchestrator/src/main/resources/logback.xml
scripts/compose/grafana/provisioning/dashboards/dashboard.yaml
scripts/compose/grafana/provisioning/dashboards/log-viewer.json
scripts/compose/grafana/provisioning/datasources/datasource.yaml
scripts/compose/logstash/loki.conf
utils/logging/src/main/kotlin/MdcConverter.kt
utils/test/src/commonMain/resources/logback.xml
workers/common/src/main/resources/logback.xml

This PR applies several improvements to the Loki logging (see the commit messages for details):
* Change the log format to simplify parsing.
* Adapt the Loki query for better performance.
* Fix the Loki configuration in Compose and add a log dashboard.

Loki logging improvements

---

core/src/main/kotlin/utils/JobMetrics.kt
core/src/main/resources/application.conf
docker-compose.yml
scripts/compose/grafana/provisioning/dashboards/find-logs-without-component-label.json
scripts/compose/grafana/provisioning/dashboards/ort-run-and-job-status.json
scripts/compose/grafana/provisioning/datasources/datasource.yaml
scripts/compose/graphite/storage/.gitignore

Improve metric handling mainly for Compose and fix an MDC issue along the way. See the commit messages for details.

Metric related improvements

---

dao/src/main/kotlin/repositories/ortrun/DaoOrtRunRepository.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
services/hierarchy/src/main/kotlin/OrtRunService.kt
services/hierarchy/src/test/kotlin/OrtRunServiceTest.kt

feat(core): Add a function to delete runs older than a given timestamp

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/route.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/sbom/index.tsx

SBOM UI chores

---

ui/src/components/theme-provider-state.tsx
ui/src/components/theme-provider.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/sbom/index.tsx

fix(ui): Correctly apply system theme to decide CycloneDX icon variant

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/package-manager-field.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts

ui: Add mustRunAfter to analyzer configuration

---

website/docusaurus.config.ts
website/package.json
website/pnpm-lock.yaml

Add `@easyops-cn/docusaurus-search-local` [1] as a local search plugin for Docusaurus.
Fixes #1673.
[1]: https://github.com/easyops-cn/docusaurus-search-local

docs(website): Add a local search plugin

---

api/v1/client/build.gradle.kts
api/v1/client/src/commonMain/kotlin/api/RunsApi.kt
api/v1/client/src/commonTest/kotlin/RunsApiTest.kt
cli/build.gradle.kts
cli/src/main/kotlin/DownloadCommand.kt
cli/src/main/kotlin/LogsCommand.kt
cli/src/main/kotlin/ReportsCommand.kt
cli/src/main/kotlin/RunsCommand.kt
cli/src/test/kotlin/LogsCommandTest.kt
cli/src/test/kotlin/ReportsCommandTest.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
gradle/libs.versions.toml
logaccess/loki/build.gradle.kts
logaccess/loki/src/main/kotlin/LokiLogFileProvider.kt
logaccess/loki/src/test/kotlin/LokiLogFileProviderTest.kt
logaccess/spi/build.gradle.kts
logaccess/spi/src/main/kotlin/LogFileProvider.kt
logaccess/spi/src/main/kotlin/LogFileService.kt
logaccess/spi/src/test/kotlin/LogFileServiceTest.kt
logaccess/spi/src/test/kotlin/LogLevelTest.kt
logaccess/spi/src/testFixtures/kotlin/LogFileProviderFactoryForTesting.kt
model/src/commonMain/kotlin/LogLevel.kt
model/src/commonMain/kotlin/LogSource.kt

See commit messages for details.

CLI: Add commands to download reports and logs

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx

ui: Total number of items

---

ui/src/components/data-table/data-table-pagination.tsx

ui: Left-align the "Items per page" text on table pagination component

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx

ui: Make the Package ID in issues table filterable

---

dao/src/main/kotlin/repositories/analyzerrun/PackagesTable.kt
dao/src/main/kotlin/repositories/analyzerrun/ProjectsTable.kt
dao/src/main/kotlin/utils/ArrayAggUtils.kt
dao/src/test/kotlin/repositories/analyzerrun/DaoAnalyzerRunRepositoryTest.kt

Improve performance when looking for duplicate projects and packages. See the commit messages for details.

Fix inefficient project and package comparison

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/analyzer-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/analyzer-job-details.tsx

Open question (@sschuberth ): a more helpful text is needed for the environment variables description in the form. Code search didn't reveal any good descriptions to me.

ui: Add environment variable support for the Analyzer

---

ui/src/components/typography.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/analyzer-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx

Improvements of various descriptions in the UI

---

ui/src/helpers/get-issue-category.ts

refactor(ui): Refactor issue category calculation

---

cli/src/main/kotlin/DownloadCommand.kt
cli/src/main/kotlin/InfoCommand.kt
cli/src/main/kotlin/LogsCommand.kt
cli/src/main/kotlin/OrtServerMain.kt
cli/src/main/kotlin/ReportsCommand.kt
cli/src/main/kotlin/RunsCommand.kt
cli/src/main/kotlin/StartCommand.kt

Minor CLI improvements

---

.github/workflows/check-issue-links.yml

Reduce noise. Just complain if something is wrong.

chore(github): Do not comment on PRs when issue references are in sync

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/analyzer-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts

ui: Prevent sending empty environment variables to Analyzer

---

ui/docker/UI.Dockerfile
workers/analyzer/docker/Analyzer.Dockerfile

Pin PNPM to 9.15.4

---

ui/src/config.ts

fix(ui): Fix link sharing

---

workers/reporter/docker/Reporter.Dockerfile
workers/reporter/src/main/kotlin/reporter/SourceCodeBundleReporter.kt
workers/reporter/src/test/kotlin/reporter/SourceCodeBundleReporterTest.kt

feat(reporter): Make source code origin priority configurable

---

.github/workflows/check-issue-links.yml

See the commit messages for details. Note the fix only becomes active after merge, therefore it was verified in a fork, see: https://github.com/mnonnenmacher/ort-server/pull/2

Fix workflow to check issue links

---

cli/src/main/kotlin/model/AuthenticationStorage.kt

Ensure that only the owner can read and write this file.

fix(cli): Use the correct file permissions for the auth.yml file

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx

fix(ui): Fix inadvertent paste error

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/secrets/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/routes/organizations/$orgId/secrets/index.tsx

ui: Tweak secrets pages

---

workers/common/src/main/kotlin/common/Utils.kt

Parallelize the download of file lists when generating an ORT result to improve performance. In tests this made the download of file lists about 80% faster.

feat(workers): Parallelize file list downloads

---

ui/src/helpers/get-status-class.ts

[Screencast from 2025-02-18 14-38-27.webm](https://github.com/user-attachments/assets/d7a5d26f-092e-49c2-b500-6ae3c701cf8e)

fix(ui): Align traffic light sizes

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx

ui: Make the vulnerabilities table filterable by Package ID

---

.detekt.yml
api/v1/client/src/commonMain/kotlin/OrtServerClient.kt
api/v1/client/src/commonMain/kotlin/api/VersionsApi.kt
cli/src/main/kotlin/OrtServerMain.kt
core/src/main/kotlin/api/VersionsRoute.kt

See commit messages for details.

Add server version information to `--version`

---

ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/-components/product-vulnerability-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/index.tsx

ui: Show number of items in the title of product vulnerabilities page

---

.github/workflows/build-and-test.yml
cli/build.gradle.kts

See commit messages for details.

CLI: Build native binaries on their respective platforms

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/-components/product-vulnerability-table.tsx

ui: Some minor tweaks for showing vulnerabilities

---

README.md
website/docusaurus.config.ts
website/src/pages/index.tsx

Add trademark statement

---

services/hierarchy/src/main/kotlin/PackageService.kt
services/hierarchy/src/test/kotlin/PackageServiceTest.kt

Allow sorting packages by identifier, purl and the processed declared license SPDX expression. This will provide needed sorting options to allow sorting the packages table in the UI.

refactor(services): Use custom sorting for packages query

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx

fix(ui): Fix showing the resolved revision

---

secrets/scaleway/src/main/kotlin/ScalewaySecretsModel.kt

Improve Scaleway secret property handling

---

core/build.gradle.kts
core/src/main/kotlin/plugins/StatusPages.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt

While at it, also use collected details for the fallback case.

feat(core): Collect exception messages recursively for the details

---

ui/src/routes/admin/runs/index.tsx

ui: Show number of unfiltered/filtered runs in admin section

---

api/v1/model/src/commonMain/kotlin/OrganizationVulnerability.kt
core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/main/kotlin/apiDocs/OrganizationsDocs.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt

For the most parts, this is similar to #1632.

Add endpoint to get vulnerabilities for an organization

---

ui/src/helpers/get-issue-category.ts

Add a new categorization rule for infrastructure issues.

ui: Extend infrastructure issue categorization

---

ui/src/@types/@tanstack/react-table.d.ts
ui/src/components/data-table/data-table-filter.tsx
ui/src/components/data-table/data-table-header.tsx
ui/src/components/data-table/filter-multi-select.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/projects/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/route.tsx
ui/src/schemas/index.ts

Please note that due to lack of sufficient test data locally, the "Detected License" column might need some fine-tuning in a follow-up PR, as it uses a new way for filtering.

ui: Add projects table

---

.github/workflows/ort.yml

ORT workflow improvements

---

ui/src/components/data-table/data-table-pagination.tsx

Handle page changes only when the user presses the "Enter" key or loses focus on the input field.
Resolves #2135.

fix(ui): Improve page navigation in `DataTablePagination` component

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/repository-runs-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx

ui: Add a superuser-only test mode to ORT run creation form

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/FilterOperatorAndValue.kt
api/v1/model/src/commonMain/kotlin/Package.kt
api/v1/model/src/commonMain/kotlin/ProcessedDeclaredLicense.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/utils/Extensions.kt
dao/src/testFixtures/kotlin/Fixtures.kt
model/src/commonMain/kotlin/runs/Package.kt
model/src/commonMain/kotlin/util/FilterOperatorAndValue.kt
services/hierarchy/src/main/kotlin/PackageService.kt
services/hierarchy/src/test/kotlin/PackageServiceTest.kt

Add filtering to packages endpoint

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx

With #2199 merged, add a freetext filter to the Package ID column of the packages table. Filtering is server-side.
Once an endpoint to get the deduplicated processed declared licenses in an ORT run is implemented, a follow-up PR will be done to add a select filter to that column.

ui: Add filter to "Package ID" column of packages table

---

ui/src/components/header.tsx
ui/src/routes/organizations/$orgId/products/$productId/create-repository/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/settings/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/license-findings/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/logs/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/reports/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/settings/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/settings/index.tsx
ui/src/routes/organizations/$orgId/vulnerabilities/index.tsx

Run index and id stuff in the UI

---

.github/workflows/check-issue-links.yml

This should fix the parsing for multiple issues.

fix(github): Comma-separate multiple found issues

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/route.tsx

ui: Refactor run details sidebar

---

ui/src/components/page-layout.tsx

ui: Tweak the width of the top bar in run details

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/run-details-bar.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx

ui: Clean run overview page

---

ui/src/components/statistics-card.tsx

ui: Always display all stats for the color bars

---

ui/src/routes/organizations/$orgId/products/$productId/-components/last-run-date.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/repository-runs-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/run-details-bar.tsx

ui: Add user info to more tables

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx

ui: Use server-side filtering for declared licenses of the "packages" table

---

core/src/main/kotlin/di/Module.kt

Fix for: abdb98fcf753930413a8db7baf711ac05072c961

fix: Add missing singleton init to module

---

.github/workflows/docker-build.yml
buildSrc/src/main/kotlin/ort-server-kotlin-multiplatform-conventions.gradle.kts
cli/build.gradle.kts

build(cli): Remove JIB integration

---

ui/src/routes/about/index.tsx

Add a column based layout to the version information where key and value are properly vertically aligned.

feat(ui): Improve layout in About dialog

---

buildSrc/src/main/kotlin/ort-server-kotlin-jvm-conventions.gradle.kts
transport/activemqartemis/src/main/kotlin/ArtemisMessageReceiverFactory.kt
transport/sqs/src/main/kotlin/SqsMessageReceiverFactory.kt
utils/logging/src/main/kotlin/LoggingUtils.kt

Simplify breaking out of message loops a bit

---

config/git/src/main/kotlin/GitConfigFileProvider.kt
config/git/src/test/kotlin/GitConfigFileProviderFactoryTest.kt
config/git/src/test/kotlin/GitConfigFileProviderTest.kt
workers/config/docker/Config.Dockerfile
workers/evaluator/docker/Evaluator.Dockerfile
workers/notifier/docker/Notifier.Dockerfile

Several improvements to the `GitConfigFileProvider` to prepare for adding support for private repositories.

Git config file provider improvements

---

workers/analyzer/docker/Analyzer.Dockerfile

This command is available under the name 'conan2'. This is an alignment to follow latest changes in ORT (see [1]).
[1]: https://github.com/oss-review-toolkit/ort/pull/10039

feat(analyzer): Add Conan 2 to the Docker image

---

ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/-components/product-vulnerability-table.tsx
ui/src/routes/organizations/$orgId/vulnerabilities/-components/organization-vulnerability-table.tsx

ui: Simplify product and organization vulnerability tables

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx

fix(ui): Fix filtering state missing when PURL used for Packages table

---

ui/src/components/charts/job-durations.tsx
ui/src/components/ui/chart.tsx

ui: Fix chart tooltip

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/globals.css
ui/tailwind.config.js

build(ui): Replace the animation library

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/components/ui/badge-variants.ts
ui/src/components/ui/badge.tsx
ui/src/components/ui/button-variants.ts
ui/src/components/ui/button.tsx
ui/src/components/ui/checkbox.tsx
ui/src/components/ui/command.tsx

This is the second batch of updating the `shadcn-ui`, requiring some manual fixes after the upgrade.

ui: Update shadcn components, batch 2

---

core/src/main/kotlin/plugins/Authentication.kt

Clear the role cache for a user after a write operation as it could have changed the roles. For example, if a new product is created this also creates new roles for that product, therefore the role cache needs to be updated on the call.
Fixes #2413.

feat(core): Clear role cache after write operation

---

ui/src/hooks/use-user.ts
ui/src/routes/organizations/$orgId/create-product/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/create-repository/index.tsx

feat(ui): Refresh user roles after adding an entity

---

ui/src/components/ui/multiple-selector.tsx
ui/src/hooks/use-debounce.ts
ui/src/routes/admin/users/create-user/index.tsx
ui/src/routes/admin/users/index.tsx

"Create user" form with a mandatory input (the last field):
Some organizations selected from the dropdown list component:
Response messages showing the successful addition of the user to all selected organizations:
Logging in as "testuser", it can be seen the user indeed has READERS access to all selected organizations:

ui: Create user with mandatory organization selection

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx

Make rule violations go first and technical issues go last, similar to like in the left-hand menu.

chore(ui): Reorder overview cards to match the menu

---

cli/src/jvmMain/kotlin/Extensions.jvm.kt
cli/src/linuxMain/kotlin/Extensions.linux.kt
cli/src/linuxMain/kotlin/utils/FileHelpers.linux.kt
cli/src/macosMain/kotlin/Extensions.macos.kt
cli/src/macosMain/kotlin/utils/FileHelpers.macos.kt

CLI chores

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/components/charts/cvss23-radar-chart.tsx
ui/src/components/charts/cvss4-vector-card.tsx
ui/src/components/charts/epss-chart.tsx
ui/src/components/charts/vulnerability-metrics.tsx
ui/src/helpers/vulnerability-statistics.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/-components/product-vulnerability-table.tsx
ui/src/routes/organizations/$orgId/vulnerabilities/-components/organization-vulnerability-table.tsx

This PR takes one step further towards assessing the severity of the vulnerabilities found from a project, by providing graphical representation of the vulnerability data where possible.
CVSS 2&3 data and EPSS data:
CVSS 4.0 data:

ui: Graphical enrichment of vulnerability data

---

ui/src/routes/index.tsx

This improves the issue #2507 a bit, although doesn't solve the root cause of it. Please check the details from the issue ticket.
Before this PR:
After this PR:

refactor(ui): Use a non-suspended query hook for organizations list

---

ui/src/components/delete-icon-button.tsx
ui/src/routes/admin/users/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/repository-runs-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/users/-components/repository-users-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/users/-components/product-users-table.tsx
ui/src/routes/organizations/$orgId/users/-components/organization-users-table.tsx

Change the alignment of the Actions column to left, and change the color of the trash icon to red, in order to align it with the
User Management UI for Organizations, Products and Repositories.

refactor(ui): Align Action column widths

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/secrets/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/schemas/index.ts

feat(ui): Add inherited secrets to secrets page 

---

ui/src/components/formatted-value.tsx
ui/src/helpers/value-or-na.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/projects/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx

ui: Show placeholders for data where applicable

---

ui/src/helpers/get-status-class.ts
ui/src/lib/types.ts
ui/src/routes/organizations/$orgId/products/$productId/create-repository/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/advisor-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/package-manager-field.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/reporter-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/projects/index.tsx

ui: Repository type labels

---

api/v1/model/src/commonMain/kotlin/OrtRun.kt
core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/apiDocs/ProductsDocs.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt

Fixes https://github.com/eclipse-apoapsis/ort-server/issues/2439

feat(api): Modify endpoint to run selected repositories under a product

---

transport/azure-servicebus/src/main/kotlin/AzureServicebusMessageReceiverFactory.kt

Set the receive mode to `RECEIVE_AND_DELETE` to prevent that the message is sent to other receivers if it is not processed quickly enough. Also explicitly set `maxConcurrentCalls` to 1 and `prefetchCount` to 0 to avoid that messages could be processed in parallel.

fix(azure-servicebus): Prevent parallel processing of messages

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx

refactor(ui): Get rid of explicit typing of ORT run creation subforms

---

ui/src/components/charts/job-durations.tsx

Run not started:
Run ongoing (showing time counting up by seconds and pulsing):
Run finished (showing the total run time):

ui: Show total run duration in the runs duration chart tooltips

---

ui/src/routes/admin/colors/index.tsx
ui/src/routes/admin/route.tsx

ui: Add a Colors page to admin section

---

ui/src/components/header.tsx

fix(ui): Make the "Enter Run ID" field broader

---

components/plugin-manager/implementation/src/main/kotlin/Plugin.kt
components/plugin-manager/implementation/src/main/kotlin/PluginEvent.kt
components/plugin-manager/implementation/src/main/kotlin/PluginEventStore.kt
components/plugin-manager/implementation/src/main/kotlin/PluginService.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/DisablePlugin.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/EnablePlugin.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/GetInstalledPlugins.kt
components/plugin-manager/implementation/src/test/kotlin/PluginServiceTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/GetInstalledPluginsIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/PluginManagerAuthorizationTest.kt
core/src/main/kotlin/di/Module.kt

Some refactorings of the plugin-manager before adding more features. Please see the commit messages for details.

Plugin manager refactorings

---

components/plugin-manager/implementation/src/main/kotlin/PluginService.kt
components/plugin-manager/implementation/src/main/kotlin/Utils.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/DisablePlugin.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/EnablePlugin.kt
components/plugin-manager/implementation/src/test/kotlin/PluginServiceTest.kt
components/plugin-manager/implementation/src/test/kotlin/UtilsTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/DisablePluginIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/EnablePluginIntegrationTest.kt

Improve handling of plugin IDs

---

core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/utils/Utils.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
workers/analyzer/build.gradle.kts
workers/analyzer/src/main/kotlin/analyzer/AnalyzerComponent.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerWorker.kt
workers/analyzer/src/main/kotlin/analyzer/Utils.kt
workers/analyzer/src/test/kotlin/AnalyzerWorkerTest.kt
workers/analyzer/src/test/kotlin/UtilsTest.kt

Use only enabled plugins

---

ui/src/routes/admin/colors/index.tsx

feat(ui): Show current ecosystem colors in admin/colors page

---

ui/src/lib/constants.ts
ui/src/routes/about/index.tsx
ui/src/routes/admin/content-management/footer/index.tsx

ui: Download links to OSC

---

ui/src/components/header.tsx
ui/src/routes/settings/index.tsx

"Settings" usually refer to configurations that affect how an applications works. "Preferences", on the other hand, refer to user-specific choices that affect the look, feel, or behavior of an application.

chore(ui): Say "Preferences" instead of "User Settings"

---

api/v1/model/src/commonMain/kotlin/CredentialsType.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
model/src/commonMain/kotlin/CredentialsType.kt
ui/src/routes/organizations/$orgId/infrastructure-services/$serviceName/edit/index.tsx
workers/common/src/main/kotlin/common/auth/AuthenticationListener.kt
workers/common/src/main/kotlin/common/auth/OrtServerAuthenticator.kt
workers/common/src/main/kotlin/common/env/ConanGenerator.kt
workers/common/src/main/kotlin/common/env/EnvironmentForkHelper.kt
workers/common/src/main/kotlin/common/env/EnvironmentService.kt
workers/common/src/main/kotlin/common/env/NetRcManager.kt
workers/common/src/main/kotlin/common/env/definition/ConanDefinition.kt
workers/common/src/test/kotlin/auth/OrtServerAuthenticatorTest.kt
workers/common/src/test/kotlin/common/env/ConanGeneratorTest.kt
workers/common/src/test/kotlin/common/env/EnvironmentForkHelperTest.kt
workers/common/src/test/kotlin/common/env/EnvironmentServiceTest.kt
workers/common/src/test/kotlin/common/env/NetRcManagerTest.kt

This PR adds some more refactorings and improvements to the authentication mechanism of ORT Server.

Authentication improvements

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/projects/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx

This PR adds more linking possibilities to the tables of ORT run results: vulnerabilities, rule violations, projects and packages are now also provided a "copy URL to clipboard" button.
As an example, this package link is now copied to clipboard.
When the link is opened in a new browser tab/window, it opens the view with the linked package's sub-rows opened.
Note: linking isn't implemented in this PR to organization and product tables, as they will need some refactorings first. That will come in a follow-up.

ui: Add links to more items in the UI

---

workers/reporter/src/main/kotlin/reporter/ReporterRunner.kt
workers/reporter/src/main/kotlin/reporter/ReporterWorker.kt
workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt
workers/reporter/src/test/kotlin/reporter/ReporterWorkerTest.kt

This PR adds some improvements to the logs generated by the reporter with the aim to make it easier to detect reports that take long for their generation.
Refer to the single commits for further details.

Reporter log improvements

---

ui/src/components/charts/cvss23-radar-chart.tsx

ui: Some radar chart tweaks for the vulnerabilities

---

workers/reporter/src/main/resources/META-INF/services/org.ossreviewtoolkit.reporter.Reporter

chore: Remove obsolete service file

---

ui/src/components/header.tsx
ui/src/routes/organizations/$orgId/products/$productId/route.tsx
ui/src/routes/organizations/$orgId/route.tsx

fix(ui): Render empty breadcrumb items if no access rights to entities

---

ui/src/components/ort-run-job-status.tsx
ui/src/lib/types.ts
ui/src/routes/admin/colors/index.tsx
ui/src/routes/admin/index.tsx
ui/src/routes/admin/plugins/index.tsx
ui/src/routes/organizations/$orgId/infrastructure-services/create/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/advisor-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/package-manager-field.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/reporter-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/repository-runs-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx

Simplify and align the wording to just refer to a "run". Having "ORT" here does not really add any value, and the distinction between the similar terms "run ID" and "run index" is already confusing enough without "ORT".

docs(ui): Remove "ORT" from "ORT Run"

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/Package.kt
api/v1/model/src/commonMain/kotlin/PackageCurationData.kt
api/v1/model/src/commonMain/kotlin/VcsInfoCurationData.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
model/src/commonMain/kotlin/runs/PackageRunData.kt
services/ort-run/src/main/kotlin/PackageService.kt
services/ort-run/src/test/kotlin/PackageServiceTest.kt

Apply curations to packages and include the applied curations in the result. See the commit messages for details.

Apply curations in packages endpoint

---

core/src/main/kotlin/di/Module.kt
dao/src/main/kotlin/Database.kt
orchestrator/src/main/kotlin/Entrypoint.kt
tasks/src/main/kotlin/TaskRunner.kt
workers/advisor/src/main/kotlin/advisor/AdvisorComponent.kt
workers/common/src/main/kotlin/common/OrtRunServiceModule.kt
workers/common/src/main/kotlin/common/context/WorkerContextModule.kt

Koin refactorings

---

config/local/src/test/kotlin/LocalConfigFileProviderFactoryTest.kt
config/local/src/test/kotlin/LocalConfigFileProviderTest.kt
workers/common/src/test/kotlin/common/env/config/EnvironmentConfigLoaderTest.kt
workers/config/src/test/kotlin/EndpointTest.kt

Test spec chores

---

api/v1/model/src/commonMain/kotlin/FilterOperatorAndValue.kt
api/v1/model/src/commonMain/kotlin/JobConfigurations.kt
api/v1/model/src/commonMain/kotlin/JobStatus.kt
api/v1/model/src/commonMain/kotlin/OrtRun.kt
api/v1/model/src/commonMain/kotlin/OrtRunSummary.kt
api/v1/model/src/commonMain/kotlin/PagedResponse.kt
api/v1/model/src/commonMain/kotlin/User.kt
api/v1/model/src/commonMain/kotlin/VulnerabilityRating.kt
model/src/commonMain/kotlin/JobConfigurations.kt
model/src/commonMain/kotlin/JobStatus.kt

kotlinx-serialization chores

---

services/hierarchy/src/main/kotlin/IssueService.kt
workers/scanner/src/main/kotlin/scanner/OrtServerScanResultStorage.kt
workers/scanner/src/main/kotlin/scanner/ScannerWorker.kt
workers/scanner/src/test/kotlin/OrtServerScanResultStorageTest.kt
workers/scanner/src/test/kotlin/ScannerWorkerTest.kt

This PR addresses some problems with issues generated during the Scanner step that are not correctly assigned to the current ORT run.

Scanner issues

---

dao/src/main/kotlin/repositories/scannerrun/DaoScannerRunRepository.kt
dao/src/main/kotlin/repositories/scannerrun/ScannerRunsTable.kt
dao/src/test/kotlin/repositories/scannerrun/DaoScannerRunRepositoryTest.kt
model/src/commonMain/kotlin/repositories/ScannerRunRepository.kt
model/src/commonMain/kotlin/runs/scanner/ScannerRun.kt
services/ort-run/src/main/kotlin/OrtMappings.kt
services/ort-run/src/main/kotlin/OrtRunService.kt
services/ort-run/src/main/kotlin/OrtServerMappings.kt
services/ort-run/src/test/kotlin/OrtRunServiceTest.kt

See commit messages for details.

feat(scanner): Expose `ScannerRun`-level issues to users

---

services/admin-config/src/main/kotlin/AdminConfig.kt
services/admin-config/src/main/kotlin/AdminConfigService.kt
services/admin-config/src/main/kotlin/MavenCentralMirror.kt
services/admin-config/src/test/kotlin/AdminConfigServiceTest.kt
workers/analyzer/build.gradle.kts
workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/common/src/main/kotlin/common/auth/CredentialResolver.kt
workers/common/src/main/kotlin/common/env/ConfigFileBuilder.kt
workers/common/src/main/kotlin/common/env/EnvironmentModule.kt
workers/common/src/main/kotlin/common/env/EnvironmentService.kt
workers/common/src/main/kotlin/common/env/MavenSettingsGenerator.kt
workers/common/src/main/kotlin/common/env/NetRcManager.kt
workers/common/src/test/kotlin/common/env/ConfigFileBuilderTest.kt
workers/common/src/test/kotlin/common/env/EnvironmentServiceTest.kt
workers/common/src/test/kotlin/common/env/MavenSettingsGeneratorTest.kt
workers/common/src/test/kotlin/common/env/MockConfigFileBuilder.kt

feat(workers): Generate `mirrors` configuration in `settings.xml`

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/infrastructure-services/$serviceName/edit/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/infrastructure-services/create/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/infrastructure-services/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/infrastructure-services/route.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/route.tsx

Extend the UI to allow users to view and manage Infrastructure Services not only on Organization level, but now also directly at the Repository level.

feat(ui): Manage Infrastructure Services at Repository level

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/runs/index.tsx

feat(ui): Add repository ID to repository overview page

---

components/admin-config/backend/src/main/kotlin/routes/GetConfigByKey.kt
components/admin-config/backend/src/main/kotlin/routes/InsertOrUpdateConfig.kt
components/plugin-manager/backend/src/main/kotlin/routes/CreateTemplate.kt
components/plugin-manager/backend/src/main/kotlin/routes/GetInstalledPlugins.kt
components/plugin-manager/backend/src/main/kotlin/routes/GetTemplate.kt
components/plugin-manager/backend/src/main/kotlin/routes/GetTemplates.kt
components/plugin-manager/backend/src/main/kotlin/routes/UpdateTemplateOptions.kt
components/secrets/backend/src/main/kotlin/routes/organization/PatchSecretByOrganizationIdAndName.kt
components/secrets/backend/src/main/kotlin/routes/product/PatchSecretByProductIdAndName.kt
components/secrets/backend/src/main/kotlin/routes/repository/PatchSecretByRepositoryIdAndName.kt
core/src/main/kotlin/apiDocs/AdminDocs.kt
core/src/main/kotlin/apiDocs/Authentication.kt
core/src/main/kotlin/apiDocs/OrganizationsDocs.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/main/kotlin/plugins/OpenApi.kt

Improve OpenAPI generator

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/evaluatorrun/DaoEvaluatorRunRepository.kt
dao/src/main/kotlin/repositories/evaluatorrun/RuleViolationsTable.kt
dao/src/main/kotlin/repositories/ortrun/DaoOrtRunRepository.kt
dao/src/main/kotlin/repositories/ortrun/OrtRunsTable.kt
dao/src/main/kotlin/repositories/userDisplayName/UserDisplayNamesTable.kt
dao/src/testFixtures/kotlin/Fixtures.kt
model/src/commonMain/kotlin/ContentManagementSection.kt
model/src/commonMain/kotlin/OrtRunSummary.kt
model/src/commonMain/kotlin/Repository.kt
model/src/commonMain/kotlin/RepositoryType.kt
model/src/commonMain/kotlin/VulnerabilityWithIdentifier.kt
model/src/commonMain/kotlin/repositories/EvaluatorRunRepository.kt
model/src/commonMain/kotlin/runs/EvaluatorRun.kt
model/src/commonMain/kotlin/runs/Issue.kt
model/src/commonMain/kotlin/runs/RuleViolation.kt
model/src/commonMain/kotlin/runs/repository/RuleViolationResolution.kt
model/src/commonMain/kotlin/util/ListQueryParameters.kt
services/ort-run/src/main/kotlin/OrtMappings.kt
services/ort-run/src/main/kotlin/OrtServerMappings.kt
services/ort-run/src/main/kotlin/RuleViolationService.kt
services/ort-run/src/test/kotlin/OrtRunServiceTest.kt
services/ort-run/src/test/kotlin/RuleViolationServiceTest.kt

Minor Refactorings

---

dao/src/main/kotlin/repositories/repositoryconfiguration/DaoRepositoryConfigurationRepository.kt
dao/src/main/kotlin/repositories/repositoryconfiguration/PathIncludesTable.kt
dao/src/main/kotlin/repositories/repositoryconfiguration/RepositoryConfigurationsPathIncludes.kt
dao/src/main/kotlin/repositories/repositoryconfiguration/RepositoryConfigurationsTable.kt
dao/src/main/resources/db/migration/V114__addIncludes.sql
dao/src/test/kotlin/repositories/repositoryconfiguration/DaoRepositoryConfigurationRepositoryTest.kt
model/src/commonMain/kotlin/repositories/RepositoryConfigurationRepository.kt
model/src/commonMain/kotlin/runs/repository/Includes.kt
model/src/commonMain/kotlin/runs/repository/PathInclude.kt
services/ort-run/src/main/kotlin/OrtMappings.kt
services/ort-run/src/main/kotlin/OrtRunService.kt
services/ort-run/src/main/kotlin/OrtServerMappings.kt
services/ort-run/src/test/kotlin/OrtRunServiceTest.kt

Enable storing path include patterns from the .ort.yml with their associated reasons and comments.

feat(dao): Add support for path includes

---

core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/apiDocs/OrganizationsDocs.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
services/infrastructure/src/main/kotlin/InfrastructureServiceService.kt
services/infrastructure/src/test/kotlin/InfrastructureServiceServiceTest.kt
ui/src/routes/organizations/$orgId/infrastructure-services/$serviceName/edit/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/infrastructure-services/$serviceName/edit/index.tsx

Improve `InfrastructureService` edit

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/settings/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/settings/index.tsx
ui/src/routes/organizations/$orgId/settings/index.tsx

Please see the commit for details. 
Also do note that this is a sledgehammer way of resolving this long-pending bug - many solutions have been tried before, none of which have worked.

ui: Fix updating the UI after renaming items

---

ui/src/app.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

Thanks @mmurto for your valuable suggestions!

ui: Fix redirection from product overview page

---

ui/src/routes/admin/colors/index.tsx
ui/src/routes/create-organization/index.tsx
ui/src/routes/organizations/$orgId/-components/organization-issues-statistics-card.tsx
ui/src/routes/organizations/$orgId/-components/organization-packages-statistics-card.tsx
ui/src/routes/organizations/$orgId/-components/organization-product-table.tsx
ui/src/routes/organizations/$orgId/-components/organization-products-statistics-card.tsx
ui/src/routes/organizations/$orgId/-components/organization-violations-statistics-card.tsx
ui/src/routes/organizations/$orgId/-components/organization-vulnerabilities-statistics-card.tsx
ui/src/routes/organizations/$orgId/create-product/index.tsx
ui/src/routes/organizations/$orgId/index.tsx
ui/src/routes/organizations/$orgId/infrastructure-services/$serviceName/edit/index.tsx
ui/src/routes/organizations/$orgId/infrastructure-services/create/index.tsx
ui/src/routes/organizations/$orgId/infrastructure-services/index.tsx
ui/src/routes/organizations/$orgId/route.tsx
ui/src/routes/organizations/$orgId/secrets/$secretName/edit/index.tsx
ui/src/routes/organizations/$orgId/secrets/create-secret/index.tsx
ui/src/routes/organizations/$orgId/secrets/index.tsx
ui/src/routes/organizations/$orgId/settings/index.tsx
ui/src/routes/organizations/$orgId/users/-components/organization-users-table.tsx
ui/src/routes/organizations/$orgId/users/index.tsx
ui/src/routes/organizations/$orgId/users/route.tsx
ui/src/routes/organizations/$orgId/vulnerabilities/index.tsx

Also fix some imports in /colors page.

refactor(ui): Refactor the organizations/$orgId route

---

api/v1/mapping/src/commonMain/kotlin/ApiMappings.kt
api/v1/model/src/commonMain/kotlin/OrganizationVulnerability.kt
api/v1/model/src/commonMain/kotlin/ProductVulnerability.kt
core/src/main/kotlin/apiDocs/OrganizationsDocs.kt
core/src/main/kotlin/apiDocs/ProductsDocs.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
model/src/commonMain/kotlin/VulnerabilityWithAccumulatedData.kt
services/ort-run/src/main/kotlin/VulnerabilityService.kt
services/ort-run/src/test/kotlin/VulnerabilityServiceTest.kt
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/vulnerabilities/index.tsx

Return purl for organization and product vulnerabilities

---

ui/openapi-ts.config.ts
ui/src/routes/admin/index.tsx
ui/src/routes/admin/runs/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/create-repository/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/settings/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/index.tsx
ui/src/schemas/index.ts

refactor(ui): Remove the "hand-written" validation schemas from the UI 

---

core/src/main/kotlin/apiDocs/OrganizationsDocs.kt
core/src/main/kotlin/apiDocs/ProductsDocs.kt

fix(core): Add missing filters to API docs

---

dao/src/main/kotlin/repositories/scannerrun/DaoScannerRunRepository.kt

This looks nicer in the UI's issues table.

chore(dao): Capitalize the "Scanner" issue source

---

ui/src/globals.css
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/run-details-bar.tsx

ui: Add cursor-pointer to buttons globally
