.github/workflows/publish-artifacts.yml

Grant the `packages: write` permission to the `GITHUB_TOKEN` in the publish-artifacts workflow to fix the publishing of packages to the GitHub package registry.

ci: Add required permission to publish-artifacts worflow

---

.env.development
docker-compose.yml

Orchestrator and workers do not spin up with the current `docker-compose.yml`. The commits fix the errors to allow for launching a development environment with compose.

Fix failing services in Docker Compose

---

README.md

BuildKit is enabled by default in any recent Docker version, so shorten individual command line snippets by explaining only once in the beginning how to enable BuildKit for Docker.

docs(README): Explain only once how to enable Docker BuildKit

---

core/src/main/kotlin/apiDocs/ProductsDocs.kt

There is a typo in patchProductById, which leads to wrongly named hook generated for the Server UI, and this PR fixes the typo.

fix(apiDocs): Fix typo in ProductsDocs

---

.gitignore
README.md
scripts/requests/env/http-client.env.json
scripts/requests/liveness.http
scripts/requests/organizations.http
scripts/requests/products.http
scripts/requests/repositories.http

Add requests to read and create the basic ORT server entities with the IDEA HTTP client [1].
This setup expects a `http-client.private.env.json` file that configures the authentication.
[1]: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

feat(dev): Add basic environment and requests for IDEA HTTP client

---

workers/advisor/src/main/resources/application.conf
workers/analyzer/src/main/resources/application.conf
workers/common/build.gradle.kts
workers/common/src/main/kotlin/common/context/WorkerContextFactory.kt
workers/common/src/test/kotlin/common/context/WorkerContextFactoryTest.kt
workers/evaluator/src/main/resources/application.conf
workers/reporter/src/main/resources/application.conf
workers/scanner/src/main/resources/application.conf

This PR enables configuration of ORT's `EnvironmentVariableFilter` via environment variables in ORT Server. The configuration is read and applied in `WorkerContextFactory`; so it is available to all workers.
ORT Server did not provide a way to tweak this configuration, which may be required for certain environments.

Support configuration for the EnvironmentVariableFilter

---

.github/workflows/static-analysis.yml

Always use the latest REUSE version, which currently is 3.0.2 [1].
This aligns with the ORT core configuration.
[1]: https://github.com/fsfe/reuse-tool/releases/tag/v3.0.2

build(github): Update REUSE to the latest version

---

core/src/main/kotlin/plugins/StatusPages.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt

Respond 400 'Bad Request' on invalid JSON bodies instead of 500 'Internal Server Error'.

fix(api): Respond with 400 when receiving an invalid body

---

.github/renovate.json

Configure Renovate to only do weekly updates [1] of `aws.sdk.kotlin:s3` as the package is updated very often.
[1]: https://docs.renovatebot.com/configuration-options/#packagerules

ci(renovate): Configure schedule for `aws.sdk.kotlin:s3`

---

api/v1/model/src/commonMain/kotlin/Organization.kt
api/v1/model/src/commonMain/kotlin/Product.kt

The change in aa53753 was a bit too eager in that it inlined validation separately for `create` and `update` endpoints for the same entity, whereas these should use exactly the same validation. To solve this, make `update` calls imply use the `create` validation.

fix(validation): Make `update` use the same validation as `create`

---

workers/reporter/build.gradle.kts

The recent update of `kaml` dragged in a version of `snakeyaml` that was incompatible with jRuby and thus caused the generation of AsciiDoc reports to fail. Fix this by excluding the `kaml` library for the Reporter worker.

fix(reporter): Fix a version clash with YAML libraries

---

gradle.properties

With the default values of 512 MiB heap space and 384 MiB metaspace the Gradle daemon often expired, because it was running out of metaspace.
While at it, also set the file encoding to UTF-8.

build: Increase the memory for the Gradle daemon

---

dao/src/main/resources/db/migration/V62__licenseFindingsNullableScore.sql

Depending on the scanner the license finding `score` might not be present. E.g. FossID does not provide any score for its findings. The DAO representation of the `license_findings` already defined the `score` field as nullable.
Resolves #99.

fix(db): Drop the not null constraint on the score column

---

.github/renovate.json

Make auto-generated PRs by Renovate stand out more and label them with "dependencies" like also ORT core does.

ci(renovate): Label PRs with "dependencies"

---

.github/workflows/build-and-test.yml

Add UI building to the corresponding workflow, to automatically assess the buildability of the UI codebase after Renovate Bot 's suggested UI dependency updates. Use caching to reduce installation time.
This resolves #126.

ci: Add UI building to build and test workflow

---

dao/src/main/kotlin/tables/SnippetsTable.kt
dao/src/main/resources/db/migration/V63__removeSnippetIndex.sql
workers/scanner/src/main/kotlin/scanner/OrtServerScanResultStorage.kt

In production, there are some errors when inserting snippets in the table, because the column "additional_data" is too large for the index related to the unique constraint on this table's columns. This index is also growing and is currently taking more place than the snippet data itself.
However, this column `additional_data` is also containing the FossID snippet id, which is unique for every FossID scan. Therefore, this unique constraint does not make sense and can be removed.

fix(snippets): Remove the unique constraint on the snippets table

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/app.tsx
ui/src/components/header.tsx
ui/src/components/ui/select.tsx
ui/src/routeTree.gen.ts
ui/src/routes/_layout/organizations/$orgId.create-product.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.create-repository.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.edit.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.create-run.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.edit.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.route.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.runs.$runId.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.runs.$runId.route.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.route.tsx

This PR adds CRUD (Create, Read, Update, Delete) functionality for Products and Repositories to the ORT Server UI. It also adds minimal proof-of-concept functionality for creating, listing and inspecting ORT Runs for Repositories.  
Note that this has currently some limitations, as Runs cannot be deleted, so if you create an ORT Run for a Repository, the repo cannot be deleted, either.  This will be addressed at a later stage.

ui: Add Products, Repositories and ORT Runs

---

.github/actions/free-disk-space/action.yml
.github/workflows/docker-build.yml
gradle.properties
workers/analyzer/build.gradle.kts
workers/config/build.gradle.kts
workers/evaluator/build.gradle.kts
workers/notifier/build.gradle.kts
workers/reporter/build.gradle.kts
workers/scanner/build.gradle.kts

The workflow was tested in a fork: https://github.com/mnonnenmacher/ort-server
The resulting Docker images can be seen here (they are mixed with test artifacts, only those starting with "ort-server-" are relevant): https://github.com/mnonnenmacher?tab=packages

Add a GitHub workflow to build and publish Docker images

---

build.gradle.kts
gradle/libs.versions.toml

Dependency updates are now managed by Renovate bot.

build(Gradle): Remove the `versionCatalogUpdate` plugin

---

README.md
build.gradle.kts
gradle.properties

I plan to improve docs further with upcoming PRs that also pass Docker build args to the Gradle tasks, but I thought this could be useful already.

Add convenience tasks to build images

---

core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/main/kotlin/authorization/Authorization.kt
core/src/main/kotlin/utils/Extensions.kt
core/src/test/kotlin/api/AbstractIntegrationTest.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt

Change the `/organizations` endpoint to only require authentication instead of the superuser role, and to return only those organizations for which the user has `OrganizationPermission.READ`.
As the permissions are managed by Keycloak, the database does not know about them. Therefore the implementation fetches the whole list of organizations from the database and filters them afterward. For a very long list of organizations this might not perform well, so if required, a different solution has to be found later.

feat(core): Filter organizations based on permissions

---

build.gradle.kts

Splitting an empty string does not return an empty list, but a list with an empty string as the single entry, which results in `--build-arg` having an empty argument.
This only surfaced when running the task under WSL with Docker Desktop for Windows, apparently because empty arguments are handled differently there.

fix(gradle): Correctly parse blank `dockerBaseBuildArgs`

---

workers/common/src/main/kotlin/common/OrtRunService.kt
workers/common/src/test/kotlin/common/OrtRunServiceTest.kt
workers/notifier/src/main/kotlin/notifier/NotifierComponent.kt
workers/notifier/src/main/kotlin/notifier/NotifierOrtResultGenerator.kt
workers/notifier/src/main/kotlin/notifier/NotifierRunner.kt
workers/notifier/src/main/kotlin/notifier/NotifierWorker.kt
workers/notifier/src/test/kotlin/NotifierRunnerTest.kt
workers/notifier/src/test/kotlin/NotifierWorkerTest.kt
workers/notifier/src/test/kotlin/notifier/NotifierOrtResultGeneratorTest.kt

This PR extends Notifier to run successful even if the Analyzer step failed. The notifier script now has access to the failed steps and can produce better notifications.

Better notify for failed runs

---

.github/workflows/build-and-test.yml

The current command used in the Build UI step, `pnpm -C ui install build`
doesn't `install` and `build` the UI project, but it installs a package
named `build`. Use separate steps to actually build the project.

Fix the build UI job

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/JobConfigurations.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
model/src/commonMain/kotlin/JobConfigurations.kt
workers/common/src/main/kotlin/common/context/WorkerContext.kt
workers/common/src/main/kotlin/common/context/WorkerContextImpl.kt
workers/common/src/test/kotlin/common/context/WorkerContextFactoryTest.kt
workers/common/src/test/resources/config/dir/subConfig1.txt
workers/common/src/test/resources/config/dir/subConfig2.txt
workers/reporter/src/main/kotlin/reporter/ReporterRunner.kt
workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt

This PR adds the missing feature to Reporter to use custom license texts that are defined as files in a directory in the configuration.

Support custom license texts

---

core/src/main/kotlin/plugins/Authentication.kt
dao/src/main/kotlin/repositories/DaoInfrastructureServiceRepository.kt
dao/src/test/kotlin/repositories/DaoInfrastructureServiceRepositoryTest.kt
workers/common/src/main/kotlin/common/OrtServerMappings.kt
workers/common/src/main/kotlin/common/env/NetRcGenerator.kt
workers/common/src/testFixtures/kotlin/OrtTestData.kt

The `URI()` constructor has been deprecated in Java 20 [1], so use `URI.create()` instead to be prepared for that.
[1]: https://inside.java/2023/02/15/quality-heads-up/

chore: Prefer `URI.create()` over `URI()`

---

workers/reporter/docker/Reporter.Dockerfile

This is required for the special source code bundle reporter which may download artifacts to be included into the bundle from their VCS location.
Note that this is a quick fix. It is also not complete, since not all version control systems supported by ORT are added. For the long run, a more generic solution needs to be found.

fix(reporter): Add Git to the Reporter base image

---

.github/renovate.json

Stick to major version 8 for now, see [1].
[1]: https://github.com/eclipse-apoapsis/ort-server/pull/195#pullrequestreview-2062428978

ci(renovate): Renovate eslint in-range-only

---

.gitignore
ui/src/components/ort-run-job-status.tsx
ui/src/components/ui/badge-variants.ts
ui/src/components/ui/badge.tsx
ui/src/helpers/get-status-colors.ts
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.runs.$runId.index.tsx
ui/src/types/status-types-and-constants.ts

This PR brings in some UI improvements for logging the statuses of ORT runs and their respective job statuses, concentrating mainly on the repository index page:
- all statuses are now polled periodically and the UI is updated accordingly
- runs are shown in reversed order of creation ie. newest runs are shown on top of the list/page
- run statuses are shown with coloured badges to more clearly indicate the general status of a run
- job statuses of a run are shown in the page with a "traffic lights" type of component

ui: Show ORT run and job statuses more clearly in the UI

---

utils/test/build.gradle.kts
utils/test/src/commonMain/resources/logback.xml

Set a logger and the default log level to "debug" when running tests.

build(test-utils): Enable logging when running tests

---

logaccess/loki/src/main/kotlin/LokiConfig.kt
secrets/spi/src/main/kotlin/SecretsProvider.kt
secrets/vault/src/main/kotlin/VaultSecretsProvider.kt

KDoc uses Markdown syntax for that purpose [1]. Note that reference-style links are not supported, though [2]. Apply some slight rewording along the way to make text fit better.
[1]: https://kotlinlang.org/docs/kotlin-doc.html#external-links
[2]: https://youtrack.jetbrains.com/issue/KTIJ-21386

docs: Correctly link external docs

---

workers/common/src/main/kotlin/common/OrtRunService.kt
workers/common/src/test/kotlin/common/OrtRunServiceTest.kt
workers/notifier/src/main/kotlin/notifier/NotifierOrtResultGenerator.kt
workers/notifier/src/test/kotlin/notifier/NotifierOrtResultGeneratorTest.kt
workers/reporter/src/main/kotlin/reporter/ReporterWorker.kt
workers/reporter/src/test/kotlin/reporter/ReporterWorkerTest.kt

Add the id of the current ORT run as label to the ORT result in order to have it available during report and notification generation.

feat(reporter): Add id of current ORT run as label to ORT results

---

workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/common/src/main/kotlin/common/env/NuGetGenerator.kt
workers/common/src/test/kotlin/common/env/NuGetGeneratorTest.kt

Change path of NuGet config generation to one that complies to the NuGet specification [1].
[1]: https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file
Authored-by: Kamil Bielecki <kamil.bielecki@pl.bosch.com>

fix(workers): Fix NuGet config file generation path

---

workers/common/src/test/kotlin/OrtServerMappingsTest.kt
workers/common/src/testFixtures/kotlin/OrtTestData.kt
workers/reporter/src/main/kotlin/reporter/SourceCodeBundleReporter.kt
workers/reporter/src/test/kotlin/reporter/SourceCodeBundleReporterTest.kt

Similar to the ORT CLI [1], the SourceCode Bundle should only include packages from specified license categories.
[1]: https://github.com/oss-review-toolkit/ort/blob/8181666dc5d8bfd739b1260c171c4e707c0c7568/model/src/main/resources/reference.yml#L163-L165

feat(reporter): Only include specified categories in the sources bundle

---

workers/config/src/main/kotlin/ConfigValidator.kt
workers/config/src/main/kotlin/ValidationScriptTemplate.kt

The `constructorArgs` are deprecated to pass values to scripts. Use the generic `providedProperties` mechanism instead.

refactor(config): Migrate from `constructorArgs` to `providedProperties`

---

core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt

While it did not seem to make a difference regarding the success of the test, semantically the product id is the correct one to use.

fix(core): Use the correct product id in tests

---

.gitignore

See [1]. This is a fixup for 4f98209.
[1]: https://kotlinlang.org/docs/whatsnew20.html#new-directory-for-kotlin-data-in-gradle-projects

build(Gradle): Ignore K2's `.kotlin` directory

---

.detekt.yml

Allow to put annotations in enums on the same line as the enum entry.

style(detekt): Align with ORT core about annotation formatting

---

ui/src/components/header.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.runs.$runIndex.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.runs.$runIndex.route.tsx

ORT runs have a global id and a repository specific index. Use the index instead of the id when navigating to a run, as the index is used by the API endpoint to get ORT run details. For report downloads still the global id has to be used.
This fixes the issue that the links to ORT runs were broken if runs for multiple repositories exist.

fix(ui): Identify ORT runs by their index instead of id

---

.gitignore

Reduce potential side-effects due to matching in sub-directories.

chore(gitignore): Ignore some directories at the top-level only

---

README.md
ui/.prettierignore
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.create-run.tsx

Add Advisor job to the ORT runs (enabled by default, default advisors OSV and VulnerableCode).
It has been verified with [this repository](https://github.com/oss-review-toolkit/ort-test-data-npm.git) that the Advisor is started, it runs parallel to the Scanner, and the job running parallel is indicated correctly in the UI by "pulsing traffic lights" both for the Advisor and Scanner jobs. The Advisor produces Vulnerabilities into WebApp as indicated in this screenshot:

ui: Include advisor in an ORT Run

---

transport/activemqartemis/src/main/kotlin/ArtemisMessageConverter.kt
transport/activemqartemis/src/test/kotlin/ArtemisMessageReceiverFactoryTest.kt
transport/activemqartemis/src/test/kotlin/ArtemisMessageSenderFactoryTest.kt
transport/kubernetes/src/main/kotlin/KubernetesMessageReceiverFactory.kt
transport/kubernetes/src/main/kotlin/KubernetesMessageSender.kt
transport/kubernetes/src/test/kotlin/KubernetesMessageReceiverFactoryTest.kt
transport/kubernetes/src/test/kotlin/KubernetesMessageSenderTest.kt
transport/rabbitmq/src/main/kotlin/RabbitMqMessageConverter.kt
transport/rabbitmq/src/test/kotlin/RabbitMqMessageSenderFactoryTest.kt
transport/spi/src/main/kotlin/Message.kt

These properties name the properties of the `Message` class, so move them next to that class for general reuse.

refactor(transport): Move message property constants to a central place

---

ui/README.md

Align the value in the README with the actual default value.

docs(compose): Fix default `VITE_API_URL` in the README

---

workers/analyzer/docker/Analyzer.Dockerfile

Corepack [1] provides an alternative way to install the package managers it supports (Yarn2+ and PNPM). Projects can specify the concrete version number of the package manager they need; Corepack then handles the automatic installation of this version.
For this to work, the package managers must not be installed by any other means. So, remove them from the container image and explicitly enable Corepack.
[1]: https://nodejs.org/api/corepack.html

feat(Analyzer): Use Corepack to install Yarn2+ and PNPM

---

transport/sqs/src/test/kotlin/SqsMessageSenderFactoryTest.kt

This was contributed from the ORT core code base and is available since Kotest 5.9.1.

refactor(transport): Use Kotest's new `infix` version of `shouldNotBeNull`

---

.github/renovate.json

Change the configuration to schedule weekly updates for all `aws.sdk.kotlin` packages instead of only `aws.sdk.kotlin:s3`.

ci(renovate): Configure schedule for all `aws.sdk.kotlin` packages

---

core/src/main/kotlin/plugins/OpenApi.kt
core/src/main/resources/application.conf
core/src/test/resources/application-test-auth.conf
core/src/test/resources/application-test.conf

This change introduces three new configuration variables that are used for setting the "server" value in the Swagger UI configuration. The new variables have default values that keep the existing behaviour.
This enables using Swagger UI in environments with some kind of proxy or load balancer in front of the ORT Server API.

feat(core): Set Swagger UI server URL from config

---

config/github/src/test/kotlin/GitHubConfigFileProviderFactoryTest.kt
config/github/src/test/kotlin/GitHubConfigFileProviderTest.kt
secrets/vault/src/test/kotlin/VaultSecretsProviderRequestsTest.kt

Reduce indentation and minify overridden function signatures for a better overview. While at it, inline the only use of the `createConfigManager()` function.

style: Use a more compact formatting for several tests

---

core/src/main/kotlin/services/OrchestratorService.kt
orchestrator/src/test/kotlin/OrchestratorEndpointTest.kt
orchestrator/src/test/kotlin/OrchestratorTest.kt
transport/activemqartemis/src/main/kotlin/ArtemisMessageConverter.kt
transport/activemqartemis/src/test/kotlin/ArtemisMessageReceiverFactoryTest.kt
transport/activemqartemis/src/test/kotlin/ArtemisMessageSenderFactoryTest.kt
transport/kubernetes-jobmonitor/src/main/kotlin/FailedJobNotifier.kt
transport/kubernetes/src/main/kotlin/KubernetesMessageReceiverFactory.kt
transport/kubernetes/src/main/kotlin/KubernetesMessageSender.kt
transport/kubernetes/src/test/kotlin/KubernetesMessageReceiverFactoryTest.kt
transport/kubernetes/src/test/kotlin/KubernetesMessageSenderTest.kt
transport/rabbitmq/src/main/kotlin/RabbitMqMessageConverter.kt
transport/rabbitmq/src/test/kotlin/RabbitMqMessageReceiverFactoryTest.kt
transport/rabbitmq/src/test/kotlin/RabbitMqMessageSenderFactoryTest.kt
transport/spi/src/main/kotlin/Message.kt
transport/spi/src/test/kotlin/EndpointComponentTest.kt
transport/spi/src/test/kotlin/MessagePublisherTest.kt
transport/spi/src/testFixtures/kotlin/Utils.kt
transport/sqs/src/main/kotlin/SqsMessageReceiverFactory.kt
transport/sqs/src/main/kotlin/SqsMessageSender.kt
transport/sqs/src/test/kotlin/SqsMessageReceiverFactoryTest.kt
transport/sqs/src/test/kotlin/SqsMessageSenderFactoryTest.kt
workers/advisor/src/test/kotlin/AdvisorEndpointTest.kt
workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/config/src/test/kotlin/EndpointTest.kt
workers/evaluator/src/test/kotlin/EvaluatorEndpointTest.kt
workers/notifier/src/test/kotlin/NotifierEndpointTest.kt
workers/reporter/src/test/kotlin/reporter/ReporterComponentTest.kt
workers/scanner/src/test/kotlin/ScannerEndpointTest.kt

<strike>The header of messages exchanged between the various endpoints contains a field called "token". This change sets that field with the JWT from the "Authorization" HTTP header.</strike>
This change removes the "token" property from the header of messages exchanged between the various ORT Server endpoints. It is currently left empty and there are no changes planned that would make use of it.

chore: Remove unused property from MessageHeader

---

core/src/main/kotlin/services/OrchestratorService.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt

Creating multiple runs for the same repository concurrently could lead to a unique constraint violation exception because the computation of the run index is not thread-safe. Fix this by setting the transaction isolation level to `TRANSACTION_SERIALIZABLE`. Since runs are not created that frequently, this should not have a major impact on the performance.

fix(core): Fix a race condition when creating ORT runs

---

core/src/main/kotlin/plugins/OpenApi.kt

Since this URL is now configurable, the server is not always a local one.

fix(api): Remove the 'local' from the server description

---

workers/scanner/src/main/kotlin/scanner/OrtServerNestedProvenanceStorage.kt
workers/scanner/src/main/kotlin/scanner/PackageProvenanceCache.kt
workers/scanner/src/test/kotlin/OrtServerNestedProvenanceStorageTest.kt
workers/scanner/src/test/kotlin/OrtServerPackageProvenanceStorageTest.kt
workers/scanner/src/test/kotlin/scanner/PackageProvenanceCacheTest.kt

OrtServerNestedProvenanceStorage did not handle the constellation correctly that there are multiple root projects in a repository. In this case, only the last project was assigned the nested provenance correctly; the others were missed.
To prevent this, extend `PackageProvenanceCache` to store a list of provenance IDs that are found in a repository. Then the assignment can be done for all of these provenances.

fix(scanner): Fix assignments of provenances to nested provenances

---

ui/src/app.tsx

To sing the users in, the UI briefly redirects the browser to Keycloak when
loading the UI in browser. Keycloak redirects users back to the UI, so use
the current URL as the redirect URI to get the user to the same page they
tried to access before signing in.
Fixes #435.

fix(ui): Redirect back to same path after signing in

---

core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/main/kotlin/plugins/OpenApi.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/testFixtures/kotlin/Fixtures.kt

Add an endpoint to get the details of an ORT run at `/runs/{id}`.
For context see #406.

Add `/runs/{id}` endpoint

---

transport/spi/src/main/kotlin/EndpointComponent.kt
transport/spi/src/main/kotlin/Utils.kt
workers/advisor/src/main/kotlin/advisor/AdvisorComponent.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerComponent.kt
workers/config/src/main/kotlin/ConfigComponent.kt
workers/evaluator/src/main/kotlin/evaluator/EvaluatorComponent.kt
workers/notifier/src/main/kotlin/notifier/NotifierComponent.kt
workers/reporter/src/main/kotlin/reporter/ReporterComponent.kt
workers/scanner/src/main/kotlin/scanner/ScannerComponent.kt

The Ascii art uses a library from a small project "Kotlin Ink":
https://github.com/Derrick-Mwendwa/kotlin-ink
Is it ok to use it in ORT Server ? I reviewed the source code and it seems clean.
I also opened an issue for better integration:
https://github.com/Derrick-Mwendwa/kotlin-ink/issues/3

feat(workers): Log the ORT Server version when a worker starts

---

utils/test/src/commonMain/resources/kotest.properties

This should reduce test startup times yet more, see [1].
[1]: https://kantis.github.io/posts/Faster-Kotest-startup/

test: Disable scanning for Kotest project config in third-party JARs

---

ui/src/routes/_layout/admin/index.tsx
ui/src/routes/_layout/index.tsx
ui/src/routes/_layout/organizations/$orgId.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.index.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.index.tsx

Increase the limits when requesting list of organizations, products, repositories, and runs from the default 20 to 1000.
This mitigates the issue that not all entities can be accessed from the UI until #453 is implemented.

feat(ui): Increase the limits in API requests

---

api/v1/mapping/build.gradle.kts
api/v1/model/build.gradle.kts
build.gradle.kts
model/build.gradle.kts
utils/test/build.gradle.kts

This way no suppression of "UnusedPrivateMember" is required.

build(Gradle): Use a different syntax to configure common source sets

---

core/src/main/kotlin/api/VersionsRoute.kt
core/src/main/kotlin/apiDocs/VersionsDocs.kt
core/src/main/kotlin/plugins/Routing.kt
core/src/test/kotlin/api/VersionsIntegrationTest.kt

Add an endpoint `/versions` to return the ORT-Server version. The endpoint returns a map as later on more tool versions will be returned, for example, the version of ORT that is in use.
The endpoint requires authentication to not expose the version to arbitrary clients for security reasons.
Fixes #95.

feat(api): Add an endpoint to return the ORT-Server version

---

config/github/build.gradle.kts
config/github/src/main/kotlin/GitHubConfigCache.kt
config/github/src/main/kotlin/GitHubConfigFileCache.kt
config/github/src/main/kotlin/GitHubConfigFileProvider.kt
config/github/src/main/kotlin/GitHubConfigNoCache.kt
config/github/src/test/kotlin/GitHubConfigFileCacheTest.kt
config/github/src/test/kotlin/GitHubConfigFileProviderTest.kt
config/github/src/test/kotlin/GitHubConfigNoCacheTest.kt
workers/advisor/src/main/resources/application.conf
workers/analyzer/src/main/resources/application.conf
workers/config/src/main/resources/application.conf
workers/evaluator/src/main/resources/application.conf
workers/notifier/src/main/resources/application.conf
workers/reporter/src/main/resources/application.conf
workers/scanner/src/main/resources/application.conf

`GitHubConfigFileProvider` downloads multiple configuration files from a configurable GitHub repository during an ORT run. When there are many ORT runs, this can be an issue, since the GitHub REST API has some rate limiting applied (5000 requests per hour).
This PR therefore adds support for caching to this provider. This is rather effective for this use case, as files under a specific revision are immutable.
For now, configuration files are cached in a local directory, which can be a network share. This is going to be extended by also caching the content of folders and also by an automatic clean-up of old entries in the cache.

Caching for GitHubConfigFileProvider

---

ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.create-run.tsx
ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.runs.$runIndex.index.tsx

With this PR, parameters and labels can be added to an ORT run. If Rerun functionality for an old ORT run is used, the parameters and labels used for the old run are also pre-populated in the run creation form.
In anticipation of future implementation, job configuration context is also added to the run creation form.
All added properties of the ORT run are shown in the run details page.
This resolves #312.

ui: Add parameters, labels and job config context to ORT Run

---

workers/common/src/main/kotlin/common/Extensions.kt

Still allow this inline function to be used from public API via the `@PublishedApi` annotation [1].
[1]: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-published-api/

refactor(workers)!: Make the `getConfigFileWithDefault()` helper internal

---

api/v1/model/src/commonMain/kotlin/Repository.kt

CVS support was removed from ORT core in [1].
[1]: https://github.com/oss-review-toolkit/ort/pull/6932

fix(api): Remove CVS as a repository type

---

ui/src/routes/_layout/organizations/$orgId.products.$productId.repositories.$repoId.create-run.tsx

Add the possibility to specify evaluator rules, license classifications, copyright garbage, and resolutions files to the evaluator job.  The user can also specify a path within the repository where the configuration file is located.
Using `GitHubConfigFileProvider`, it was verified that all files (with their specific paths inside the repository) are properly passed to the Evaluator and Reporter.
By providing fallback files (copied from [oss-review-toolkit/ort-config](https://github.com/oss-review-toolkit/ort-config)) at the root directory of the GitHub config file provider, it was also verified that in case of empty fields, the files from the default directory were taken into the jobs correctly.

feat(ui): Add some configuration options to the evaluator job

---

.github/workflows/gradle-wrapper-validation.yml

This gets rid of a deprecation warning in CI logs.

ci(github): Upgrade to the new Gradle wrapper validation action

---

.github/workflows/docker-build.yml

The `latest` tag is widely used and expected in the Docker ecosystem.
Tag the latest builds from the main branch with the tag.

ci(docker): Enable `latest` tag for published images

---

.github/renovate.json

Node Docker image specified in UI's Dockerfile updates very often. It's
only used to build UI before serving it from NGINX, so update it only once
a week to reduce spam from Renovate.

chore(renovate): Update Node once a week

---

.detekt.yml

This reverts commit 9df9f85 as the false-positives cannot be reproduced anymore.

Revert "build(detekt): Disable the `RedundantSuspendModifier` rule"

---

secrets/vault/src/main/kotlin/VaultSecretsProvider.kt

Rework the token handling to not fetch a token initially, but deal with a missing token during request execution. While this slightly makes the logic more complex, it has the benefits that during creation of a `VaultSecretsProvider` instance no request is sent, and the `runBlocking` call to fetch the initial token can be dropped.

refactor(vault): Remove an unneeded `runBlocking` call

---

ui/src/routes/_layout/create-organization.tsx
ui/src/routes/_layout/organizations/$orgId/create-product.tsx
ui/src/routes/_layout/organizations/$orgId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/create-repository.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/edit.tsx

Add loading indicators in buttons when creating or updating organizations/products/repositories/runs. Decided not to add this for deleting yet, as this would've required changes that would become obsolete soon if the delete buttons are moved to a settings tab.

UI: Add loading indicators for post and patch requests

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/JobConfigurations.kt
api/v1/model/src/commonMain/kotlin/SourceCodeOrigin.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
model/src/commonMain/kotlin/JobConfigurations.kt
model/src/commonMain/kotlin/SourceCodeOrigin.kt
workers/common/src/main/kotlin/common/OrtServerMappings.kt
workers/scanner/src/main/kotlin/scanner/ScannerRunner.kt

Make the source code origins configurable via the
`ScannerJobConfiguration`. Previsouly, the configuration was hardcoded to prefer `SourceCodeOrigin.ARTIFACT` over `SourceCodeOrigin.VCS`.

feat: Make source code origin priority configurable

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-types.ts
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx

This helps declutter the page component. The `-` prefix in routes makes
files not create routes even though they're in the routes directory,
allowing to colocate helpers and components not used anywhere else.

refactor(ui): Move utility types in create run page to separate file

---

transport/sqs/src/main/kotlin/SqsMessageConverter.kt
transport/sqs/src/main/kotlin/SqsMessageReceiverFactory.kt
transport/sqs/src/main/kotlin/SqsMessageSender.kt
transport/sqs/src/test/kotlin/SqsMessageReceiverFactoryTest.kt
transport/sqs/src/test/kotlin/SqsMessageSenderFactoryTest.kt

Work around the SQS restriction to not allow empty message attribute values

---

workers/advisor/src/main/kotlin/advisor/AdvisorRunner.kt
workers/advisor/src/test/kotlin/AdvisorRunnerTest.kt
workers/advisor/src/test/kotlin/AdvisorWorkerTest.kt
workers/common/src/main/kotlin/common/context/WorkerContext.kt
workers/common/src/main/kotlin/common/context/WorkerContextImpl.kt
workers/common/src/test/kotlin/common/context/WorkerContextFactoryTest.kt
workers/evaluator/src/main/kotlin/evaluator/EvaluatorRunner.kt
workers/evaluator/src/test/kotlin/EvaluatorRunnerTest.kt
workers/evaluator/src/test/kotlin/EvaluatorWorkerTest.kt
workers/reporter/src/main/kotlin/reporter/ReporterRunner.kt
workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt
workers/scanner/src/main/kotlin/scanner/ScannerRunner.kt
workers/scanner/src/test/kotlin/ScannerRunnerTest.kt

Note that a similar fix for package curation providers will be done in a separate PR.

Fix resolution of package configuration provider secrets

---

.github/renovate.json

The lucide icon library is updated very often. As most updates do not affect the icons used by the ui, limit the updates to once a week.

ci(renovate): Update lucide-react once a week

---

workers/analyzer/src/main/kotlin/analyzer/AnalyzerRunner.kt
workers/analyzer/src/test/kotlin/AnalyzerRunnerTest.kt
workers/analyzer/src/test/kotlin/AnalyzerWorkerTest.kt

Resolve the secrets in the configurations of the package curation providers from the configured secret storage, instead of using the secret values directly.
As the `AnalyzerRunner` does not have access to the worker context when running in a fork, the secrets need to be resolved before creating the fork.

fix(analyzer): Resolve secrets of package curation providers

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/PagedResponse.kt
core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/DaoProductRepository.kt
dao/src/test/kotlin/repositories/DaoProductRepositoryTest.kt
model/src/commonMain/kotlin/repositories/ProductRepository.kt
model/src/commonMain/kotlin/util/ListQueryResult.kt

Add the total entity counts to organization endpoints to enable proper pagination in the UI. Please see the commit messages for details.
This is a first step to implement the requirements for #453, the remaining endpoints will be aligned in separate PRs.

Add total counts to organization endpoints that return lists

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/notifier-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx

This PR adds support for the Notifier job, by adding an own component for it to the ORT run creation form. The job is disabled by default.
Information about the Notifier job should also be seen in the run results, similar to the other jobs included in the run.  
Note:
- job information is so far only a JSON structure. Results showing will be fine-tuned in a later PR
- as I've never configured or used Notifier, the PR is not tested with an ORT run
- to me it is unclear what Notifier configuration parameters are needed, so I have made all configuration parameters mandatory. This means that if the user enables Notifier, then all configuration parameters need to have sensible values
For the above reasons, I'm expecting some conversation and guidance to this PR from the interested persons. …

ui: Add support for the Notifier

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx

Use browser language to decide on the exact format. Examples:
English:
Finnish:
Run details, English:

ui: Show the creation time in the ort runs table and run details page

---

.github/workflows/publish-artifacts.yml

Since 6fdc420 the artifacts were published with changing versions based on the revision. Set 1.0.0-SNAPSHOT as the fixed version for those artifacts, as they are only used for testing and not proper releases.

ci: Set 1.0.0-SNAPSHOT as fixed version for the Maven artifacts

---

ui/src/components/header.tsx

This PR fixes an undefined context error when refreshing the browser on index pages:

fix(ui): Guard against possible undefined context in header

---

.github/renovate.json

The Tanstack router and query dependencies are often updated daily. Limit this to weekly to not be overwhelmed.

ci(renovate): Check Tanstack updates at most once a week

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/components/header.tsx
ui/src/components/ui/tabs.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/-components/advisor-job-details.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/-components/analyzer-job-details.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/-components/evaluator-job-details.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/-components/notifier-job-details.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/-components/reporter-job-details.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/-components/scanner-job-details.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/-components/sidebar.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/route.tsx
ui/src/routes/_layout/route.tsx

This PR adds a temporary route `.../runs2/` that will be used for pages and (upcoming) subpages for viewing ORT run details results. The PR touches existing implementation very minimally:
- root layout has one added Tailwind class
- header has an additional (temporary) breadcrumb item, to make the breadcrumb show identical information as for the current run details page
As there already are ongoing discussions about the philosophy for showing the ORT run results, the purpose of this PR is to be more of a basis for discussion, rather than a polished and finalized way to show the results. (Think of it more like a Figma skeleton of a part of the UI.)
No links in the current UI lead directly to the new page, so should the users want to see it, it can be done by replacing `.../runs/...` in the …

ui: First skeleton version of new ORT run details page

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/OrtRun.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/main/kotlin/services/OrchestratorService.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/DaoOrtRunRepository.kt
dao/src/main/kotlin/tables/OrtRunsTable.kt
dao/src/main/resources/db/migration/V69__ortRunTraceId.sql
dao/src/test/kotlin/repositories/DaoOrtRunRepositoryTest.kt
dao/src/test/kotlin/utils/ListQueryTest.kt
dao/src/testFixtures/kotlin/Fixtures.kt
model/src/commonMain/kotlin/OrtRun.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
orchestrator/src/main/kotlin/WorkerScheduleContext.kt
orchestrator/src/test/kotlin/OrchestratorEndpointTest.kt
orchestrator/src/test/kotlin/OrchestratorTest.kt
workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/analyzer/src/test/kotlin/AnalyzerWorkerTest.kt
workers/common/src/test/kotlin/OrtServerMappingsTest.kt
workers/config/src/test/kotlin/ConfigWorkerTest.kt

This is required to handle certain scenarios with fatal worker crashes correctly. The functionality will also be needed if we were to support external trace IDs.

Store the trace ID together with the ORT run

---

workers/analyzer/docker/Analyzer.Dockerfile

The Docker build for Analyzer images was failing when it tried to add the non-privileged user and the associated group. The exit code '4' seems to indicate a conflict with an already existing user and group. So, use another user ID to circumvent the conflict.
In our CI the build was failing as well. I could verify that this fix actually solves the problem.

fix(Analyzer): Change the default user and group ID in Docker file

---

dao/src/testFixtures/kotlin/MockDatabaseModule.kt
dao/src/testFixtures/kotlin/MockTransaction.kt
orchestrator/src/main/kotlin/Entrypoint.kt
orchestrator/src/test/kotlin/OrchestratorEndpointTest.kt
transport/activemqartemis/src/main/kotlin/ArtemisMessageReceiverFactory.kt
transport/kubernetes/src/main/kotlin/KubernetesMessageReceiverFactory.kt
transport/rabbitmq/build.gradle.kts
transport/rabbitmq/src/main/kotlin/RabbitMqMessageReceiverFactory.kt
transport/spi/src/main/kotlin/EndpointComponent.kt
transport/spi/src/main/kotlin/MessageReceiverFactory.kt
transport/spi/src/testFixtures/kotlin/TransportForTesting.kt
transport/spi/src/testFixtures/kotlin/Utils.kt
transport/sqs/src/main/kotlin/SqsMessageReceiverFactory.kt
workers/advisor/src/main/kotlin/advisor/Entrypoint.kt
workers/advisor/src/test/kotlin/AdvisorEndpointTest.kt
workers/analyzer/src/main/kotlin/analyzer/Entrypoint.kt
workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/config/src/main/kotlin/Entrypoint.kt
workers/config/src/test/kotlin/EndpointTest.kt
workers/evaluator/src/main/kotlin/evaluator/Entrypoint.kt
workers/evaluator/src/test/kotlin/EvaluatorEndpointTest.kt
workers/notifier/src/main/kotlin/notifier/Entrypoint.kt
workers/notifier/src/test/kotlin/NotifierEndpointTest.kt
workers/reporter/src/main/kotlin/reporter/Entrypoint.kt
workers/reporter/src/test/kotlin/reporter/ReporterComponentTest.kt
workers/scanner/src/main/kotlin/scanner/Entrypoint.kt
workers/scanner/src/test/kotlin/ScannerEndpointTest.kt

Change the entry points into ORT Server components to use suspend functions, so that further usage of coroutines does not require additional effort.

Use suspend functions in Transport implementations

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/reports/index.tsx

This PR is for the temporary `.../runs2/...` route, which holds the implementation of the new ORT run details pages. It implements a sub-page, which is used for downloading all reports from the run.

ui: Create page for downloadable reports of ORT Run

---

api/v1/model/src/commonMain/kotlin/User.kt
clients/keycloak/src/main/kotlin/DefaultKeycloakClient.kt
clients/keycloak/src/main/kotlin/KeycloakClient.kt
clients/keycloak/src/testFixtures/kotlin/KeycloakTestClient.kt
core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/main/kotlin/apiDocs/OrganizationsDocs.kt
core/src/main/kotlin/plugins/StatusPages.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
services/authorization/src/main/kotlin/AuthorizationService.kt
services/authorization/src/main/kotlin/DefaultAuthorizationService.kt
services/hierarchy/src/main/kotlin/OrganizationService.kt
services/hierarchy/src/main/kotlin/ResourceNotFoundException.kt
services/hierarchy/src/test/kotlin/OrganizationServiceTest.kt

Add endpoints to add or remove users to groups on the level of an _Organization_ to assign the respective
roles and permissions to them. Available groups are _readers_, _writers_ and _admins_.

feat(api): Add endpoints for user management

---

gradle/libs.versions.toml

Align the Eclipse Temurin version used by Jib with the one used in Dockerfiles. This is a fixup for c99a428.

deps: Update Eclipse Temurin version for Jib

---

ui/package.json
ui/pnpm-lock.yaml

With Vite 5.4.0 the `VITE_` configuration variables do not appear anymore in the built JS file. For example, instead of:
Pe.BASE=nd.VITE_API_URL||"http://localhost:8080";
the output file now contains only:
Pe.BASE="http://localhost:8080";
This breaks the entrypoint script for the UI Docker image which makes it impossible to use the image with other than the default values.
Downgrade Vite to 5.3.5 until a proper solution is found.

deps: Downgrade Vite to 5.3.5

---

build.gradle.kts

This makes the tasks show up at `./gradlew tasks` without `--all`.

build(gradle): Add descriptions to compound tasks

---

transport/kubernetes-jobmonitor/src/main/kotlin/JobHandler.kt
transport/kubernetes-jobmonitor/src/main/kotlin/JobWatchHelper.kt
transport/kubernetes-jobmonitor/src/main/kotlin/LongRunningJobsFinder.kt
transport/kubernetes-jobmonitor/src/main/kotlin/LostJobsFinder.kt
transport/kubernetes-jobmonitor/src/main/kotlin/MonitorComponent.kt
transport/kubernetes-jobmonitor/src/main/kotlin/MonitorConfig.kt
transport/kubernetes-jobmonitor/src/main/kotlin/Reaper.kt
transport/kubernetes-jobmonitor/src/main/kotlin/TimeHelper.kt
transport/kubernetes-jobmonitor/src/main/resources/application.conf
transport/kubernetes-jobmonitor/src/test/kotlin/JobHandlerTest.kt
transport/kubernetes-jobmonitor/src/test/kotlin/JobWatchHelperTest.kt
transport/kubernetes-jobmonitor/src/test/kotlin/LongRunningJobsFinderTest.kt
transport/kubernetes-jobmonitor/src/test/kotlin/LostJobsFinderTest.kt
transport/kubernetes-jobmonitor/src/test/kotlin/MonitorComponentTest.kt
transport/kubernetes-jobmonitor/src/test/kotlin/MonitorConfigTest.kt
transport/kubernetes-jobmonitor/src/test/kotlin/ReaperTest.kt
transport/kubernetes-jobmonitor/src/test/kotlin/TimeHelperTest.kt

This PR adds a new "long-running jobs finder" component to Kubernetes Job Monitor. The component detects worker jobs that are running longer than a configured timeout and deletes them. This allows dealing with hanging jobs automatically. Different timeouts can be configured for the different worker types.

Job Monitor: Detect and delete jobs that exceed a timeout

---

workers/advisor/src/main/kotlin/advisor/Entrypoint.kt
workers/analyzer/src/main/kotlin/analyzer/Entrypoint.kt
workers/evaluator/src/main/kotlin/evaluator/Entrypoint.kt
workers/notifier/src/main/kotlin/notifier/Entrypoint.kt
workers/reporter/src/main/kotlin/reporter/Entrypoint.kt
workers/scanner/src/main/kotlin/scanner/Entrypoint.kt

Under some scenarios the property can be set to "?". Use ORT's helper function to fix that based on environment variables. See [1] for some background information.
[1]: https://bugs.openjdk.java.net/browse/JDK-8193433

fix(workers): Use ORT's function to fix the `user.home` system property

---

dao/src/main/kotlin/Database.kt

In rare cases, the database server may stop accepting incoming connection requests, causing the datasource module to throw an exception. This update adds an error log message to ensure the issue is clearly visible in logs and can be detected by monitoring systems.

feat: Log an error if unable to connect to database server

---

core/src/main/kotlin/plugins/OpenApi.kt

Fix some issues in generated OpenAPI spec

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs2/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

The "Redo2" icon [1] is supposed to be used in the context of "undo" operations, so use the better fitting "Repeat" icon [2] instead.
[1]: https://lucide.dev/icons/redo-2
[2]: https://lucide.dev/icons/repeat

chore(ui): Use the Lucide "Repeat" icon instead of "Redo2"

---

transport/spi/src/testFixtures/kotlin/Utils.kt

In CI, `SqsMessageReceiverFactoryTest` often fails with "Expected value to not be null, but was null" when polling the queue [1], which does return "null if the specified waiting time elapses before an element is available".
Triple the timeout to 15 seconds to try addressing that, and move the timeout to a constant while at it.
Hopefully fixes #720.
[1]: https://github.com/eclipse-apoapsis/ort-server/actions/runs/10488199036/job/29050829407?pr=861#step:5:3552

test(transport): Increase the queue timeout

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx

This avoids conflicts when downloading multiple archives.

feat(ui): Include the global run ID into the log archive download

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx

Otherwise align with [1] as a fallback.
[1]: https://github.com/eclipse-apoapsis/ort-server/blob/03f5738d78aacb1ef4814b3d3eb657cf641cbee8/core/src/main/kotlin/api/RunsRoute.kt#L98

feat(ui): Prefer the backend-provided log archive name

---

config/github/src/test/kotlin/GitHubConfigFileCacheTest.kt

Use the bigger default value of 1 second delays between retries, but in exchange try fewer times, and for a shorter duration.
This hopefully reduces test flakyness.

test(github): Tweak retry / delay values

---

buildSrc/src/main/kotlin/ort-server-kotlin-jvm-conventions.gradle.kts

Apply upcoming Kotlin 2.1 behavior to align the `copy()` function's visibility to the visibility of the primary constructor for data classes. This avoids the new compiler warning with Kotlin 2.0.20 if properties of a private primary constructor are exposed via `copy()`, even though the `copy()` function is not called.

build(gradle): Enable consistent `copy()` visibility

---

ui/src/components/header.tsx
ui/src/components/mode-toggle.tsx
ui/src/components/providers.tsx
ui/src/components/theme-provider-context.tsx
ui/src/components/theme-provider.tsx

Add support for the light and dark modes to the UI. The mode toggle is in the UI header.
The chosen mode is persisted to the browser's local storage, and defaults to light mode when there's nothing in the storage (eg. when the UI is opened up the first time).
Note that while the light mode should be unaffected, there probably is a need to fine-tune the dark mode in subsequent PRs, so this PR is an enabler for future user comments, and issues about the dark mode are welcome.
Also please note that the user experience of the dark mode is highly dependent on the display settings.

ui: Add theme support

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-types.ts
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx

While reporters are still hard-coded, add some more commonly required types, remove rarely used ones, and move prominent types to the top.

feat(ui): Rework the list of reports

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-types.ts

While the list of selectable package managers is still hard-coded, add a few more common ones.

feat(ui): Add a few more likely required package managers

---

.git-blame-ignore-revs

See [1].
[1]: https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

chore: Add a file to ignore certain Git commits when blaming

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/analyzer-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx

So far the `Unmanaged` package manager has always been disabled, causing unmanaged files (e.g. in a repository without definition files in the root, or no definition files at all) to be "swallowed" and disregarded when scanning. Address this by always enabling the `Unmanaged` package manager. While ORT allows to disable the `Unmanaged` package manager [1], there is a risk that users are unaware of the implications. As the use-cases for disabling the `Unmanaged` package manager are rather limited, simply do not allow to do that for now.
[1]: https://github.com/oss-review-toolkit/ort/commit/ba312efbeabdb32c225c13158703fb68414de106

feat(ui): Always enable the `Unmanaged` package manager

---

scripts/docker/keycloak/master-realm.json
ui/src/@types/oidc-client-ts.d.ts
ui/src/config.ts

Get user roles from userinfo endpoint instead of ID token

---

.github/renovate.json

Configure a custom manager for the Eclipse Temurin version defined in `libs.versions.toml` so that it gets updated automatically. This ensures that the version does not deviate from the version used in Dockerfiles.
Fixes #801.

ci(renovate): Configure custom manager for `libs.versions.toml`

---

core/src/main/kotlin/api/RunsRoute.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/logs/index.tsx

This helps to avoid archives being overwritten when different levels are downloaded for the same run.

feat: Include the log level into the archive download

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/Issue.kt
dao/src/main/kotlin/tables/runs/shared/IssuesTable.kt
dao/src/main/resources/db/migration/V70__addAffectedPathToIssue.sql
dao/src/test/kotlin/migrations/V70__addAffectedPathToIssueTest.kt
model/src/commonMain/kotlin/runs/Issue.kt
workers/common/src/main/kotlin/common/OrtMappings.kt
workers/common/src/main/kotlin/common/OrtServerMappings.kt

feat: Add `affectedPath` to `Issue`
The ORT `Issue` has the `affectedPath` property since version 9.0.0 [1].
Also add a database migration that sets the affected path for existing
issues based on the message in the same way that ORT does [2].
[1]: https://github.com/oss-review-toolkit/ort/releases/tag/9.0.0
[2]: https://github.com/oss-review-toolkit/ort/blob/b3c98bbf24907d36ca003d78f532054d3c7b12a5/model/src/main/kotlin/ScanSummary.kt#L151-L163
Depends on #923 to be merged first.

Add affected path to issues

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/route.tsx

Use [1] for dependencies to avoid a folder-look, use [2] for vulnerabilities to avoid a connection to smoking, and [3] for rule violations to match a bit ORT's evaluator logo [4].
[1]: https://lucide.dev/icons/list-tree
[2]: https://lucide.dev/icons/shield-question
[3]: https://lucide.dev/icons/scale
[4]: https://github.com/oss-review-toolkit/ort/blob/main/logos/evaluator.png

ui(routes): Use some more fitting icons

---

.github/workflows/docker-build.yml

If the `imageVariant` is configured in the build matrix, it is used as a suffix for the image tag. Also use the suffix for the cache image tag, otherwise the caches for different image variants overwrite each other.
This is a fixup for ab3657e.

ci(docker): Use tag suffix also for the base image cache

---

ui/src/routes/_layout/create-organization.tsx
ui/src/routes/_layout/organizations/$orgId/create-product.tsx
ui/src/routes/_layout/organizations/$orgId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/$serviceName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/create.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/create-repository.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/advisor-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/analyzer-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/notifier-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/scanner-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/create-secret.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/create-secret.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/$secretName/edit.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/create-secret.tsx

Align the wording to have fewer different strings. Use punctuation even for single sentences.

docs(ui): Align form descriptions

---

config/github/src/test/kotlin/GitHubConfigFileCacheTest.kt

With the current delay of 1 second, the test code exhausts all its retries in 9 seconds, and it leads to some occasional flakiness in the CI.
This should solve the occasional CI error:
```
org.eclipse.apoapsis.ortserver.config.github.GitHubConfigFileCacheTest > cleanup should > remove outdated revisions with the configured probability FAILED
java.lang.AssertionError: Test failed after 9 seconds; attempted 10 times; underlying cause was expected:<false> but was:<true>
at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:101)
at io.kotest.engine.test.interceptors.InvocationTimeoutInterceptor.intercept(InvocationTimeoutInterceptor.kt:42)
at io.kotest.engine.test.TestInvocationInterceptor$runBeforeTestAfter$wrappedTest$1$1.invokeSuspe …
```

test(github): Increase the delay between retries

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/issues/index.tsx

NOTE: This PR is merely a factorization of the ORT run results pages and is by no means a complete implementation of the issues listing. Completing it needs at least #405 implemented, and depending on the issues endpoint and a possible run summary endpoint, the layout of the issues page will most probably need changes.

ui: Move issues of an ORT Run to a separate page

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/route.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/dependencies/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/license-findings/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/packages/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx

ui: Add results sub-pages for all ORT Run results

---

logaccess/loki/src/main/kotlin/LokiLogFileProvider.kt
logaccess/loki/src/test/kotlin/LokiLogFileProviderTest.kt

Given Loki is used as log aggregation system, when multiple log statements are generated in quick succession (burst), these log statements potentially all carry the same timestamp. When the Loki HTTP API is used to fetch the log statements for a given time interval using chunks defined by a start timestamp, this leads to an endless loop in the ORT server if the chunk size is smaller than the number of log statements with identical timestamps. This bugfix prevents this endless loop by making sure that each chunk is fetched at most a single time.

fix(logaccess): Prevent a potential endless loop

---

.github/workflows/docker-build.yml

This allows to manually trigger the Docker build also for other branches than "main".

ci: Allow to manually trigger the Docker build

---

core/src/main/kotlin/plugins/Lifecycle.kt

Preserve the MDC context when starting new threads in `configureLifecycle`.

fix(core): Preserve MDC context in `configureLifecycle`

---

dao/src/main/resources/db/migration/V73__deduplicatePackagesAndProjects.sql

This is a fix for 3bef62c. If a property of a project contains a special character like a backslash, the migration could fail. This can be prevented by using the `convert_to()` function in the same way this was already done for packages.

fix(dao): Fix an issue in the deduplication migration

---

orchestrator/src/main/kotlin/Orchestrator.kt
orchestrator/src/main/kotlin/WorkerScheduleContext.kt
orchestrator/src/test/kotlin/OrchestratorTest.kt

If any of the workers finished with this status, and if no worker failed, the ORT run receives also this status.
This is a fixup for 3cc0a255010db9edb89e30d40229ace37c873679.

fix(orchestrator): Set the ORT run status to `FINISHED_WITH_ISSUES`

---

.github/workflows/ort.yml

Add a workflow to run ORT on the ORT Server. This will later be included in the release workflow to generate an SBOM and probably also in PR checks.
To be able to manually trigger a workflow, it must first be merged to the main branch. Therefore, only include the basics in this commit to download the image and run the requirements command. This makes it easier to prepare another PR which adds the execution of the ORT tools and the required configuration.

ci: Add a workflow to run ORT

---

.github/ort/config.yml
.github/workflows/ort.yml
.ort.yml

Configure the ORT workflow to acutally run ORT. See the commit messages for details.
Note that the workflow is still only used for testing, proper exit code handling will have to be done when integrating it in automatically triggered workflows. Also several findings still need to be addressed.
The results of a test run can be found here:
https://github.com/eclipse-apoapsis/ort-server/actions/runs/11036682245

Configure ORT workflow

---

dao/src/main/kotlin/utils/Extensions.kt

Make more clear that the one only needs to be done due to the other.

chore(dao): Do the typed array conversion next to the spread operator

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/IssueWithIdentifier.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/main/kotlin/di/Module.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/tables/runs/shared/IssuesTable.kt
dao/src/main/kotlin/utils/Extensions.kt
model/src/commonMain/kotlin/IssueWithIdentifier.kt
services/hierarchy/src/main/kotlin/IssueService.kt
services/hierarchy/src/test/kotlin/IssueServiceTest.kt

This PR currently misses the following functionality before being ready to review:

Issues endpoint

---

.github/actions/free-disk-space/action.yml
.github/workflows/build-and-test.yml
.github/workflows/docker-build.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/ort.yml
.github/workflows/publish-artifacts.yml
.github/workflows/renovate.yml
.github/workflows/static-analysis.yml
.github/workflows/website-test.yml

Use `ubuntu-24.04` for all GitHub workflows. Previously, some workflows used `ubuntu-latest` while others used `ubuntu-22.04`. Using a specific version avoids unwanted upgrades which could break CI.
Upgrading the Docker build to `ubuntu-24.04` requires updating the `free-disk-space` action as the ubuntu-24.04 runners do not have pre-installed Docker images anymore. Also the list of tools to delete needs to be updated.

ci: Consistently use Ubuntu 24.04

---

transport/spi/src/testFixtures/kotlin/Utils.kt

Previously, the `payload` argument of the function was overwriting the `payload` property of the message class with the same name. This caused the test to compare the `payload` argument with itself.

test(transport): Fix payload comparison in `checkMessage`

---

api/v1/model/src/commonMain/kotlin/User.kt
clients/keycloak/src/main/kotlin/DefaultKeycloakClient.kt
clients/keycloak/src/main/kotlin/KeycloakClient.kt
clients/keycloak/src/main/kotlin/UserCredentials.kt
clients/keycloak/src/main/kotlin/internal/Credential.kt
clients/keycloak/src/test/kotlin/AbstractKeycloakClientTest.kt
clients/keycloak/src/testFixtures/kotlin/KeycloakTestClient.kt
core/src/main/kotlin/api/AdminRoute.kt
core/src/main/kotlin/apiDocs/AdminDocs.kt
core/src/main/kotlin/di/Module.kt
core/src/test/kotlin/api/UsersRouteIntegrationTest.kt
model/src/commonMain/kotlin/User.kt
scripts/requests/users.http
services/authorization/src/main/kotlin/UserService.kt

A subsequent PR will implement a minimal admin UI for creating new users.
Resolves #1088.

Add an endpoint for creating new users

---

.github/workflows/publish-website.yml

This PR adds a workflow to build and publish the website to GH Pages upon pushed to the main branch.
I have also created a PR for the configuration change: https://github.com/eclipse-apoapsis/.eclipsefdn/pull/13

ci: Add workflow to publish the website to GH Pages

---

CONTRIBUTING.md

Add more details about the conventional commit types, the handling of breaking changes, and the versioning of the project.
Fixes #319.

docs(CONTRIBUTING): Improve the commit message documentation

---

transport/kubernetes-jobmonitor/src/main/resources/application.conf

Add the missing configuration options for sending messages to the orchestrator to `application.conf`. Note the configuration also works without it, but the options should there for reference and consistency.
Fixes #874.

fix(kubernetes-jobmonitor): Add missing config options for sender

---

core/src/main/kotlin/di/Module.kt

This is a fixup for 6701a1f. Fixes https://github.com/eclipse-apoapsis/ort-server/issues/1169.

fix(core): Inject the `RuleViolationService`

---

.github/workflows/docker-build.yml

With the upgrade of the GitHub action runners to ubuntu-24.04 in 1234567, the default Java version has changed to Java 17 (compare [1] and [2]). This breaks the build of the analyzer worker build using JDK 11, because the server code is now built with an incompatible class file version.
Fix this by switching back to using JDK 11 in the Docker build workflow. This is only a temporary solution, as the next ORT release will only be available for Java 21 [3]. With this upgrade the JDK bootstrapping mechanism introduced in recent ORT releases has to be used, instead of building analyzer worker images with different JDKs.
[1]: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#java
[2]: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404 …

ci(docker): Use Java 11 for the Docker build

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/last-job-status.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/last-run-status.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx

Show the status badge and the job status circles in the product details page to see a quick overview of runs in repositories.

UI: Show job statuses in repository list in the product page

---

.github/workflows/release.yml

The release workflow was using the wrong key id, see the commit messages for details.

Fix release artifact signing

---

ui/src/components/statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/-components/packages-statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx

ui: Show some basic information about found packages in the results main page

---

.github/renovate.json

This improves the reproducibility of builds.

ci(renovate): Enable pinning of GitHub action digests

---

ui/src/components/data-table/data-table.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/-components/rule-violations-statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/rule-violations/index.tsx
ui/src/schemas/index.ts

This is the first PR in a series of upcoming PRs, which implements the main view of rule violations.:
Statistics card in the ORT run results main page, showing the number of rule violations:
Rule violations main page, which is a grouped table, by default grouping is set for the severity:
Details modal (see pending issues):
Pending issues:
- as rule violation endpoint doesn't return unique IDs for rule violations, details routes cannot yet be created in the front-end. Therefore, as a first implementation, the details are shown in modals
- dynamic sorting needs to possibly be added to the rule violations table in an upcoming PR
- once the details are moved to their own separate sub-pages, we need a markup renderer for how-to-fix texts

ui: Show rule violations (main page)

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/route.tsx

Call `useParams` so that the correct path parameters are used in the sidebar links.
Resolves https://github.com/eclipse-apoapsis/ort-server/issues/1220.

fix(ui): Ensure path params are updated in links

---

core/src/test/kotlin/api/DownloadsRouteIntegrationTest.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
services/report-storage/src/main/kotlin/ReportStorageService.kt
services/report-storage/src/test/kotlin/ReportStorageServiceTest.kt
storage/database/src/main/kotlin/DatabaseStorageProvider.kt
storage/s3/src/main/kotlin/S3StorageProvider.kt
storage/spi/build.gradle.kts
storage/spi/src/main/kotlin/Storage.kt
storage/spi/src/main/kotlin/StorageProvider.kt
storage/spi/src/testFixtures/kotlin/StorageProviderFactoryForTesting.kt
workers/common/build.gradle.kts
workers/common/src/main/kotlin/common/OrtServerFileArchiveStorage.kt
workers/reporter/src/main/kotlin/reporter/ReportStorage.kt
workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt
workers/scanner/src/main/kotlin/scanner/OrtServerFileListStorage.kt

The `StorageProvider` interface from the storage abstraction defines some functions for reading and writing unstructured data. Some of the existing implementations implement those using HTTP requests, which are done using the suspendable functions of the HTTP client. This commit changes the API of the `StorageProvider` to make the functions suspendable. Please note that some of the Exposed transaction calls done by the `DatabaseStorageProvider.kt` have therefore to be adapted (see [1]).
[1]: https://jetbrains.github.io/Exposed/transactions.html#working-with-coroutines

feat(storage): Use suspend functions in the `StorageProvider`

---

ui/src/components/statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/-components/packages-statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/-components/rule-violations-statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx

This avoids e.g. 0 vulnerabilities being shown as "Failed" in the run overview.

fix(ui): Do not render 0 values as falsy values

---

ui/src/components/data-table/data-table-toolbar.tsx
ui/src/components/data-table/filter-multi-select.tsx
ui/src/components/sidebar.tsx
ui/src/lib/utils.ts
ui/src/routes/_layout/admin/index.tsx
ui/src/routes/_layout/admin/route.tsx
ui/src/routes/_layout/admin/runs/index.tsx
ui/src/schemas/index.ts

Add runs overview page for superusers to get a quick overview of the runs on the server instance.

ui: Add runs overview page for admins

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/analyzer-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/package-manager-field.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-create-run-utils.ts
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/config/-components/analyzer-job-details.tsx

This PR adds the ability to also set options for package managers as part of the analyzer job configuration. When using the rerun functionality, the options are copied to the new run and in the analyzer configuration section of the form, all package managers for which options are set are opened by default.
Setting options for package managers:
Options are also copied to the job configurations part of ORT run results:

ui: Add package manager options to ORT Run creation form

---

.github/workflows/docker-build.yml

Since the ORT Analyzer plugins Gradle, GradleInspector and SBT now support JDK bootstrapping, there is no more need
for building image variants for various JDK versions of the Analyzer worker.
For details on the change, see the respective commits.

Stop building jdk specific Analyzer worker images

---

.github/workflows/release.yml

This reverts commit ec42e5a as the issue has been fixed upstream in the version taken into use in e8dd7cc.

Revert "ci(release): Disable generation of release notes"

---

core/src/main/resources/application.conf
dao/src/main/kotlin/Database.kt
dao/src/main/kotlin/DatabaseConfig.kt
dao/src/main/kotlin/tables/ScanSummariesIssuesTable.kt
dao/src/main/kotlin/tables/ScanSummariesTable.kt
dao/src/main/kotlin/tables/runs/shared/IssuesTable.kt
dao/src/main/kotlin/utils/DigestFunction.kt
dao/src/main/resources/db/migration/V83__scannerSummariesIssuesTimestamps.sql
dao/src/main/resources/db/migration/V84__deduplicateIssues.sql
dao/src/main/resources/db/migration/V85__issuesIndexOnValueColumns.sql
dao/src/test/kotlin/DatabaseTest.kt
dao/src/test/kotlin/repositories/DaoOrtRunRepositoryTest.kt
dao/src/test/kotlin/tables/ScanSummariesIssuesTableTest.kt
orchestrator/src/main/resources/application.conf
transport/kubernetes-jobmonitor/src/main/resources/application.conf
workers/advisor/src/main/resources/application.conf
workers/analyzer/src/main/resources/application.conf
workers/config/src/main/resources/application.conf
workers/evaluator/src/main/resources/application.conf
workers/notifier/src/main/resources/application.conf
workers/reporter/src/main/resources/application.conf
workers/scanner/src/main/kotlin/scanner/OrtServerScanResultStorage.kt
workers/scanner/src/main/resources/application.conf

This PR further refactors the database model for issues to deduplicate entities, so that issues with matching properties are reused. It also contains a migration script to remove existing duplicates. Refer to the single commits for further information.

Deduplicate issues

---

api/v1/model/src/commonMain/kotlin/User.kt
core/src/main/kotlin/api/AdminRoute.kt
core/src/main/kotlin/apiDocs/AdminDocs.kt
core/src/test/kotlin/api/AdminRouteIntegrationTest.kt
services/authorization/src/main/kotlin/UserService.kt

fix(api): Fix users endpoints

---

dao/src/main/resources/db/migration/V84__deduplicateIssues.sql

This is a fix for #3ee6bb31. The `identifiers_issues` table needs to be processed by the migration as well.

fix(dao): Fix the migration to deduplicate issues

---

dao/src/main/resources/db/migration/V84__deduplicateIssues.sql

The fix in 2490be36 was still not sufficient. Add a `DISTINCT` to prevent a duplicate key constraint violation.

fix(dao): One more fix for the migration to deduplicate issues

---

ui/src/helpers/get-status-class.ts
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/-components/issues-statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/-components/packages-statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/-components/rule-violations-statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/-components/vulnerabilities-statistics-card.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/issues/index.tsx
ui/src/schemas/index.ts

An open question: I believe the issues are sorted by timestamp by default. It could make the issues table cleaner if the back-end sorting would be hard-coded in the UI into severity instead. Another possibility would be to do also sorting on client side, but this hasn't yet been implemented in this PR.

ui: Issues page

---

core/src/main/kotlin/api/RepositoriesRoute.kt
dao/src/main/kotlin/repositories/DaoOrtRunRepository.kt
dao/src/main/kotlin/tables/AdvisorJobsTable.kt
dao/src/main/kotlin/tables/AnalyzerJobsTable.kt
dao/src/main/kotlin/tables/EvaluatorJobsTable.kt
dao/src/main/kotlin/tables/OrtRunsTable.kt
dao/src/main/kotlin/tables/ReporterJobsTable.kt
dao/src/main/kotlin/tables/ScannerJobsTable.kt
model/src/commonMain/kotlin/OrtRunSummary.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
services/hierarchy/src/main/kotlin/RepositoryService.kt

Limit the fetched data for repository runs to only what is needed for the REST API response,
enhancing performance by avoiding excess loading of unused related entities.
Utilize lazy-loading in the Kotlin Exposed framework by no longer prematurely mapping of unused columns to object attributes.
Number of generated SQL statements in the BE is reduced at least by 50%.

fix(api): Optimize performance by reducing ORT run data fetching

---

storage/spi/src/main/kotlin/Storage.kt

In order to obtain the correct exception thrown by a provider, the code was using the `withContext` function. This, however, caused problems with hanging jobs. Therefore, use `supervisorScope` instead.

fix(storage): Replace `withContext` by `supervisorScope`

---

cli/build.gradle.kts
cli/src/main/kotlin/OrtServerMain.kt
gradle/libs.versions.toml
settings.gradle.kts

This commit introduces the new module `cli` for the ORT Server, intended to contain all upcoming implementations related to the CLI.

feat(cli): Add initial ORT Server CLI implementation

---

ui/src/routes/_layout/admin/runs/index.tsx
ui/src/routes/_layout/index.tsx
ui/src/routes/_layout/organizations/$orgId/index.tsx
ui/src/routes/_layout/organizations/$orgId/infrastructure-services/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/secrets/index.tsx
ui/src/routes/_layout/organizations/$orgId/secrets/index.tsx

Set the page search parameter to one when changing the filter or the page size to prevent the event where the user could be on the nth page, and a change to the filter or page size might lead to a result where the nth page doesn't contain any items.

fix(ui): Go to first page in tables if filter or page size changes

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/-components/packages-statistics-card.tsx

While at it, also use single-quotes instead of backticks for the `join` argument string as no interpolation is needed.

fix(ui): Use a space when joining ecosystems with a comma

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-components/evaluator-fields.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/create-run.tsx

The path is more related to the revision (as both related to the repository) than the job configuration, so swap the order of fields to account for that.

chore(ui): List the path after the revision

---

config/github/src/test/kotlin/GitHubConfigFileCacheTest.kt
config/github/src/test/kotlin/GitHubConfigFileProviderTest.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
storage/database/src/test/kotlin/LargeObjectsTest.kt
storage/spi/src/test/kotlin/StorageEntryTest.kt
workers/common/src/test/kotlin/common/context/WorkerContextFactoryTest.kt
workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt
workers/reporter/src/test/kotlin/reporter/SourceCodeBundleReporterTest.kt

Be indeterminate when checking for a file to not exist, and specific when checking for existence.

chore: Use dedicated file matchers in tests

---

config/github/src/main/kotlin/GitHubConfigFileProvider.kt
config/github/src/test/kotlin/GitHubConfigFileProviderTest.kt
config/spi/src/main/kotlin/ConfigManager.kt
config/spi/src/test/kotlin/ConfigManagerTest.kt
config/spi/src/testFixtures/kotlin/ConfigFileProviderFactoryForTesting.kt

Be more specific that the constant provides an empty context, which better matches the semantics of applying a default if the empty context is provided. Previously, `DEFAULT_CONTEXT` sounded as if it already contained e.g. the default branch name.

refactor(config): Rename `DEFAULT_CONTEXT` to `EMPTY_CONTEXT`

---

ui/src/components/timestamp-with-utc.tsx
ui/src/routes/_layout/admin/runs/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/-components/last-run-date.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/_layout/runs/$runIndex/issues/index.tsx
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/index.tsx

Please have a look at the individual commits for details.

ui: Timestamps with additional UTC information

---

ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-create-run-utils.ts
ui/src/routes/_layout/organizations/$orgId/products/$productId/repositories/$repoId/-types.ts

Support all package managers that are supported by ORT itself when triggering an ORT run via the UI.
As `Gradle` and `GradleInspector` are mutually exclusive, the legacy `Gradle` implementation is disabled by default.

feat(ui): Add missing package managers

---

core/src/main/resources/application.conf
logaccess/loki/src/main/kotlin/LokiConfig.kt
logaccess/loki/src/main/kotlin/LokiLogFileProvider.kt
logaccess/loki/src/test/kotlin/LokiConfigTest.kt
logaccess/loki/src/test/kotlin/LokiLogFileProviderTest.kt
logaccess/loki/src/test/resources/loki-response-multi-streams.json.template

If Loki is not correctly configured, it may return multiple log streams in query responses. This is problematic because there is no defined order between the entries in different streams. Therefore, the chunking algorithm does not work and may skip log entries.
Handle this by manually sorting log entries if multiple streams are detected. This will not fix all problems, the order of log statements over multiple chunks may still be mixed up; but the risk for dropping log entries is reduced.

fix(loki): Improve handling of responses with multiple streams

---

buildSrc/build.gradle.kts
gradle.properties

This should reduce time to configure builds, see [1].
[1]: https://docs.gradle.org/8.11/release-notes.html#configuration-cache-improvements

build(Gradle): Enable parallel configuration cache access

---

workers/common/src/main/kotlin/common/env/EnvironmentService.kt
workers/common/src/main/kotlin/common/env/config/EnvironmentConfigLoader.kt
workers/common/src/test/kotlin/common/env/EnvironmentServiceTest.kt
workers/common/src/test/kotlin/common/env/config/EnvironmentConfigLoaderTest.kt

This function was doing too many things. To simplify the tests, this commit breaks it up in two subfunctions.

chore(dao): Split the `parse` function of the `EnvironmentConfigLoader`

---

.github/workflows/docker-build.yml

Since a5b0131 and 9f942b4 the support for image variants and build args is not required anymore, so simplify the Docker build workflow again.

ci: Simplify Docker build

---

website/pnpm-lock.yaml

Run `pnpm dedupe` as a preparation for upgrading Docusaurus as suggested at [1].
[1]: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1013#issuecomment-2472827082

chore(website): Deduplicate dependencies

---

dao/src/main/kotlin/repositories/DaoOrtRunRepository.kt
dao/src/main/resources/db/migration/V86__ortRunDeleteCascade.sql
dao/src/test/kotlin/repositories/DaoOrtRunRepositoryTest.kt

This PR adds `ON DELETE CASCADE` constraints to the tables that depend on the `ort_runs` table to make sure that these entities are deleted automatically together with the associated ORT run. This is a first step to support manual and automatic removal of ORT runs.

Delete ORT runs

---

.github/workflows/docker-build.yml

The pattern `${{ is_default_branch }}` attempts to get a GitHub Actions
provided named value, but the default branch status is provided by the
Docker Metadata Action as a global expression to be used with Handlebars'
template format [1].
[1]: https://github.com/marketplace/actions/docker-metadata-action#global-expressions

ci: Fix variable reference in Docker build

---

dao/src/main/kotlin/Exceptions.kt
dao/src/test/kotlin/UniqueConstrainsViolationTest.kt
dao/src/test/kotlin/repositories/DaoAnalyzerRunRepositoryTest.kt

This PR fixes a subtle bug in the handling of unique constraint violation exceptions which could cause ORT runs to fail. Refer to the single commits for further details.

Unique constraint violations

---

workers/scanner/src/main/resources/application.conf

Add the missing configuration properties to use S3 as file list storage.

fix(scanner): Add missing configuration properties for S3 storage

---

core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/DaoOrtRunRepository.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
services/hierarchy/src/main/kotlin/OrtRunService.kt

Add REST API endpoint to delete ORT run by either the `ortRunId` or the combination of `repositoryId` and `ortRunIndex`. 
The database foreign key constraints option _CASCADE DELETE_ between the nodes of the directed graph where the ORT run is the root node are already established, so by deleting the ORT run, also all dependent other subordinate nodes are deleted.

feat(core): Add REST API endpoint to delete ORT run

---

workers/analyzer/docker/Analyzer.Dockerfile

This fixes the issue that the analyzer worker base image can not be built on macOS.
Error message before this fix:
```
RUN $GOBIN/go install github.com/bazelbuild/buildtools/buildozer@latest && chmod a+x $GOBIN/buildozer
go: downloading github.com/bazelbuild/buildtools v0.0.0-20240918101019-be1c24cc9a44
go: failed to initialize build cache at /home/ort/.cache/go-build: mkdir /home/ort/.cache/go-build: permission denied 
```

fix(docker): Ensure correct user for the cache directory

---

dao/src/main/kotlin/tables/ScanResultsTable.kt
dao/src/main/kotlin/utils/utils/JsonHashFunction.kt
dao/src/main/resources/db/migration/V87__deduplicateScanResults.sql
workers/scanner/build.gradle.kts
workers/scanner/src/main/kotlin/scanner/OrtServerScanResultStorage.kt
workers/scanner/src/test/kotlin/OrtServerScanResultStorageTest.kt

This PR prevents that duplicate scan results are stored if multiple scanner workers are run in parallel. It contains a migration that cleans up existing duplicates and introduces unique constraints. Note that the migration will take a while on larger databases (50 minutes in our setup).

Deduplicate scan results

---

core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/main/kotlin/di/Module.kt
dao/src/main/kotlin/repositories/ortrun/DaoOrtRunRepository.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
services/hierarchy/build.gradle.kts
services/hierarchy/src/main/kotlin/OrtRunService.kt
services/hierarchy/src/main/kotlin/RepositoryService.kt
services/hierarchy/src/test/kotlin/OrtRunServiceTest.kt
services/report-storage/src/main/kotlin/ReportStorageService.kt

On deletion of an ORT run via the REST API, also delete the associated reports from storage that were created during this ORT run.

feat(core): Delete reports in storage on deletion of ORT run

---

dao/src/main/resources/db/migration/V88__deleteObsoleteScanSummaries.sql

This is a follow-up for the migration that removed duplicate scan results. Since there is a (logic) 1:1 relation between scan results and scan summaries, the summaries for the duplicate results that have been removed can be deleted as well.
Note that it is beneficial to have these DELETE statements in a separate migration script and thus execute them in a separate transaction. When combined with the statements for deduplicating scan results, their execution time was increased dramatically. This is probably caused by the huge amount of data that is affected. Processing this in a single transaction - which could be rolled back - seems to be problematic for the database.

feat(dao): Add a migration script to delete obsolete scan summaries

---

workers/scanner/src/main/kotlin/scanner/OrtServerScanResultStorage.kt
workers/scanner/src/main/kotlin/scanner/ScanSummaryCompare.kt
workers/scanner/src/test/kotlin/OrtServerScanResultStorageTest.kt
workers/scanner/src/test/kotlin/ScanResultFixtures.kt
workers/scanner/src/test/kotlin/ScanSummaryCompareTest.kt

This PR prevents the creation of duplicate entities for scan summaries in cases where a single scan operation yields multiple results.

Deduplicate scan summaries

---

dao/src/main/kotlin/repositories/analyzerrun/DaoAnalyzerRunRepository.kt
dao/src/main/kotlin/repositories/analyzerrun/ProjectsTable.kt
dao/src/main/resources/db/migration/V89__addProjectDescription.sql
dao/src/test/kotlin/migrations/V73__deduplicatePackagesAndProjectsTest.kt
dao/src/test/kotlin/repositories/analyzerrun/DaoAnalyzerRunRepositoryTest.kt
dao/src/test/kotlin/repositories/scannerrun/DaoScannerRunRepositoryTest.kt
model/src/commonMain/kotlin/runs/Project.kt
workers/common/src/main/kotlin/common/OrtMappings.kt
workers/common/src/main/kotlin/common/OrtServerMappings.kt
workers/common/src/test/kotlin/OrtServerMappingsTest.kt
workers/common/src/testFixtures/kotlin/OrtTestData.kt

Add support for the new `description` property of projects which was introduced in ORT 42.0.0 [1].
[1]: https://github.com/oss-review-toolkit/ort/releases/tag/42.0.0

feat(model): Add project descriptions

---

model/src/commonMain/kotlin/JobStatus.kt
services/hierarchy/src/main/kotlin/RepositoryService.kt
services/hierarchy/src/test/kotlin/RepositoryServiceTest.kt

Add functions for getting the latest ORT run ID for a repository, where a particular job has finished (or failed). These functions will be used in upcoming endpoints that will provide the information for the product overview page (which currently gathers this data from various endpoints) and an upcoming organization overview page.

feat(services): Add functions for getting run ID in various cases

---

ui/src/components/data-table/data-table.tsx
ui/src/helpers/handle-multisort.ts
ui/src/routes/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/route.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/route.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/-components/product-vulnerability-table.tsx
ui/src/schemas/index.ts

This PR implements multisorting for all sortable tables in the UI. For product vulnerabilities, initial multisorting status is by overall vulnerability rating (descending), then by repository count (descending).

ui: Multisorting for all sortable tables

---

core/src/main/kotlin/di/Module.kt
core/src/main/kotlin/plugins/StatusPages.kt
core/src/test/kotlin/api/DownloadsRouteIntegrationTest.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/ortrun/DaoOrtRunRepository.kt
dao/src/main/kotlin/repositories/product/DaoProductRepository.kt
dao/src/main/kotlin/repositories/repository/DaoRepositoryRepository.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
model/src/commonMain/kotlin/repositories/ProductRepository.kt
model/src/commonMain/kotlin/repositories/RepositoryRepository.kt
services/hierarchy/src/main/kotlin/OrganizationService.kt
services/hierarchy/src/main/kotlin/ProductService.kt
services/hierarchy/src/main/kotlin/RepositoryService.kt
services/hierarchy/src/test/kotlin/ProductServiceTest.kt
services/hierarchy/src/test/kotlin/RepositoryServiceTest.kt

Enable the user to delete a repository by recursively deleting the ORT runs which are linked to this specific repository.
Resolves #100.

feat(core): Delete ORT runs before deleting the repository

---

dao/src/main/kotlin/repositories/advisorrun/AdvisorResultsTable.kt
dao/src/main/kotlin/repositories/analyzerrun/AnalyzerConfigurationsTable.kt
dao/src/main/kotlin/repositories/analyzerrun/PackageManagerConfigurationsTable.kt
dao/src/main/kotlin/repositories/infrastructureservice/InfrastructureServicesTable.kt
dao/src/main/kotlin/repositories/repositoryconfiguration/LicenseFindingCurationsTable.kt
dao/src/main/kotlin/repositories/repositoryconfiguration/RepositoryAnalyzerConfigurationsTable.kt
dao/src/main/kotlin/repositories/scannerrun/ScannerConfigurationsTable.kt
dao/src/main/kotlin/utils/Extensions.kt

The deprecation of the DAO transform API was reverted in Exposed 0.57.0, see [1] and [2].
[1]: https://github.com/JetBrains/Exposed/blob/main/CHANGELOG.md#0570
[2]: https://github.com/JetBrains/Exposed/pull/2309

chore(dao): Remove unnecessary suppression of `DEPRECATION`

---

buildSrc/src/main/kotlin/ort-server-kotlin-jvm-conventions.gradle.kts

This reverts commit 085e70b as both ORT core and ORT server by now use Exposed 0.57.0.

Revert "build(gradle): Force to use Exposed 0.52.0"

---

ui/tailwind.config.js

Convert the Tailwind CSS config file from CJS to ESM syntax to fix the build with Node 22.12.0 [1].
[1]: https://github.com/nodejs/node/issues/56155

fix(ui): Convert Tailwind CSS config to ESM

---

.github/workflows/docker-build.yml

Set `fetch-depth` to `0` to checkout the whole commit history including tags. This is required to correctly calculate the ORT Server version.
Fixes #1610.

ci(docker): Fix calculating the ORT Server version

---

core/src/main/kotlin/api/RunsRoute.kt
dao/src/testFixtures/kotlin/Fixtures.kt
services/hierarchy/src/main/kotlin/IssueService.kt
services/hierarchy/src/main/kotlin/PackageService.kt
services/hierarchy/src/main/kotlin/RuleViolationService.kt
services/hierarchy/src/main/kotlin/VulnerabilityService.kt
services/hierarchy/src/test/kotlin/IssueServiceTest.kt
services/hierarchy/src/test/kotlin/PackageServiceTest.kt
services/hierarchy/src/test/kotlin/RuleViolationServiceTest.kt
services/hierarchy/src/test/kotlin/VulnerabilityServiceTest.kt

Edit the count functions to count items for multiple runs to make the functions reusable for statistics endpoints on the product and organization levels. 
- The issues count is accumulated as a total sum from issues in all runs (as I wasn't sure if there should be some deduplication here)
- The vulnerabilities are counted as number of unique vulnerability+identifier pairs (could also be counted as vulnerabilities with unique external IDs, ignoring the identifiers?)
- The rule violations are counted as distinct rule violations found in runs
- The packages are counted as distinct packages found in runs, and ecosystems are counted similarly from distinct packages
Let me know if you think any of these should be counted differently.
Please see the individual commits for more details.

Refactor run statistics count functions to take in multiple run IDs

---

dao/src/main/kotlin/repositories/ortrun/DaoOrtRunRepository.kt
dao/src/test/kotlin/repositories/ortrun/DaoOrtRunRepositoryTest.kt
kubernetes/jobmonitor/src/main/kotlin/FailedJobNotifier.kt
kubernetes/jobmonitor/src/main/kotlin/LostJobsFinder.kt
kubernetes/jobmonitor/src/test/kotlin/FailedJobNotifierTest.kt
kubernetes/jobmonitor/src/test/kotlin/LostJobsFinderTest.kt
kubernetes/jobmonitor/src/test/kotlin/MonitorComponentTest.kt
model/src/commonMain/kotlin/ActiveOrtRun.kt
model/src/commonMain/kotlin/orchestrator/OrchestratorMessage.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
orchestrator/src/main/kotlin/Entrypoint.kt
orchestrator/src/main/kotlin/Orchestrator.kt
orchestrator/src/test/kotlin/OrchestratorEndpointTest.kt
orchestrator/src/test/kotlin/OrchestratorTest.kt
transport/kubernetes/src/main/kotlin/KubernetesMessageSender.kt
transport/kubernetes/src/test/kotlin/KubernetesMessageSenderTest.kt

This PR addresses a problem with Orchestrator. Under specific conditions, it is possible that a schedule of a worker job gets lost. The affected ORT run then stays in ACTIVE state forever. Kubernetes Job Monitor was not able to detect this situation.
Refer to the individual commits for further information.

Handle missed schedules in Orchestrator

---

.github/workflows/docker-build.yml

Use individual names for the Docker build jobs as the auto-generated unique names are based on the matrix parameters and are too long which makes it difficult to configure the required checks.

ci(docker): Improve the Docker job names

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/ort-server-kotlin-jvm-conventions.gradle.kts
gradle/libs.versions.toml

As of version 2 this needs to be applied to the individual projects instead of the root project. This makes the `projectHealth` task available again.
Also see [1].
[1]: https://github.com/autonomousapps/dependency-analysis-gradle-plugin/wiki/Adding-to-your-project

build(gradle): Fix applying the dependency analysis plugin

---

workers/reporter/src/main/kotlin/reporter/CustomLicenseTextProvider.kt
workers/reporter/src/main/kotlin/reporter/ReporterRunner.kt
workers/reporter/src/test/kotlin/reporter/CustomLicenseTextProviderTest.kt
workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt

This PR adds a special `LicenseTextProvider` implementation that optimizes loading of license texts from the config repository.

Optimize access to custom license texts in Reporter

---

.github/workflows/docker-build.yml

Always load the base images to the local registry as this is where Jib is looking for them since 808a3fc.

ci(docker): Always load the base images to the local registry

---

core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
model/src/commonMain/kotlin/authorization/OrganizationPermission.kt
model/src/commonMain/kotlin/authorization/ProductPermission.kt
model/src/commonMain/kotlin/authorization/RepositoryPermission.kt

Add dedicated permissions to add or remove users to the organization, product, and repository groups. The new `MANAGE_GROUPS` permissions are only added to the respective `ADMIN` groups.
Previously, members of the `WRITERS` group could elevate their own permissions by adding themselves to the `ADMIN` group.

fix(core): Add dedicated permissions for managing groups

---

docker-compose.yml

Keycloak 26 introduced a feature to bootstrap admin accounts [1]. This feature seem to interfere with specifying admin credentials explicitly via the Docker Compose environment, leading to
Detail: Key (realm_id, username)=(0b009e14-6671-4ae5-8e3f-ddcc98049624, admin) already exists.
when starting the Keycloak image. Removing these variables prevents that while still being able to log into Keycloak with "admin" / "admin".
Note that at the same time these variables were anyway deprecated in favor of `KC_BOOTSTRAP_ADMIN_USERNAME` / `KC_BOOTSTRAP_ADMIN_PASSWORD`, causing a separate deprecation warning in the logs. However, using those variables does not prevent the above error. But removing the original variables also gets rid of that deprecation warning.
[1]: …

fix(compose): Remove explicit admin credentials

---

dao/src/main/kotlin/repositories/ortrun/DaoOrtRunRepository.kt
services/hierarchy/src/main/kotlin/IssueService.kt

While at it, make a `delete` call a one-liner.

chore: Remove redundant qualifier names for `innerJoin`

---

ui/src/routes/organizations/$orgId/-components/organization-issues-statistics-card.tsx
ui/src/routes/organizations/$orgId/-components/organization-packages-statistics-card.tsx
ui/src/routes/organizations/$orgId/-components/organization-violations-statistics-card.tsx
ui/src/routes/organizations/$orgId/-components/organization-vulnerabilities-statistics-card.tsx
ui/src/routes/organizations/$orgId/index.tsx

This PR will further align the organization and product overview pages.
Please note that the endpoint for gathering all vulnerabilities in an organization hasn't yet been implemented, so this is yet missing from this overview page.

ui: Add statistics cards for organization overview page

---

dao/src/main/kotlin/repositories/infrastructureservice/DaoInfrastructureServiceRepository.kt
dao/src/test/kotlin/repositories/infrastructureservice/DaoInfrastructureServiceRepositoryTest.kt
model/src/commonMain/kotlin/repositories/InfrastructureServiceRepository.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerWorker.kt
workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/analyzer/src/test/kotlin/AnalyzerWorkerTest.kt
workers/common/src/main/kotlin/common/env/EnvironmentService.kt
workers/common/src/test/kotlin/common/env/EnvironmentServiceTest.kt

Instead of using a single `InfrastructureService` that matches the
repository, obtain all known services to generate the `.netrc` file
for checking out the repository. This is needed if the repository has
submodules that require additional credentials.

Use all available credentials for repository download

---

workers/reporter/docker/Reporter.Dockerfile

Dump the ScanCode license texts to directory _/opt/scancode-license-data_ when creating the reporter docker container.
This directory is used by ORT as fallback option if the ScanCode license texts cannot be located by the existing heuristic look-up algorithm.
See oss-review-toolkit/ort#9622.

fix(reporter): Add ScanCode license texts to reporter docker image

---

workers/advisor/src/main/kotlin/advisor/AdvisorWorker.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerWorker.kt
workers/common/src/main/kotlin/common/OrtRunService.kt
workers/common/src/test/kotlin/common/OrtRunServiceTest.kt
workers/evaluator/src/main/kotlin/evaluator/EvaluatorWorker.kt
workers/notifier/src/main/kotlin/notifier/NotifierWorker.kt
workers/reporter/src/main/kotlin/reporter/ReporterWorker.kt
workers/scanner/src/main/kotlin/scanner/ScannerWorker.kt

This PR moves the validation of job status values to a central place in `OrtRunService` to reduce redundancy. Refer to the single commits for further details.

Refactor validation of worker job states

---

.github/ort/config.yml
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-types.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts

This PR adds more output formats to CycloneDX, SPDX, and NOTICE file in Reporter.
Note: please also see issue #1745.  Earlier in ORT core, plugin naming was following the class naming convention, and therefore, `CycloneDx` was used as an id. With the new plugin structure in ORT core, each plugin should have an id which should be used when configuring the plugin for an ORT Run.  For CycloneDX, [the correct id is actually now "CycloneDX"](https://github.com/oss-review-toolkit/ort/blob/8ebd8c0aea0ffb0770edc92a8c477a4e2f4f0586/plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt#L98-L103), not "CycloneDx". Therefore, it needed to be changed in the UI as well, which is done as part of this PR.

ui: More report formats

---

REUSE.toml

The migration in 6a9e50a added `precedence = "aggregate"`, probably to resemble the old behavior. However, the most natural and also new default behavior is to use the license declaration that is closest [1] to the file.
[1]: https://reuse.software/spec-3.3/#reusetoml

chore(reuse): Use the default "precedence" of "closest"

---

ui/index.html

This fixes loading the favicon if the UI is not hosted at the root of a domain.

fix(ui): Make the favicon path relative

---

cli/build.gradle.kts
cli/src/main/kotlin/OrtServerMain.kt

At the moment the CLI and the Server use the same version, therefore this is the version which is printed.

feat(cli): Add a `--version` option to show the used CLI version

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/sbom/index.tsx

Create a slicker look by not using a title. All information is included elsewhere (breadcrumb bar, menu item) anyway.

chore(ui): Remove the title from the SBOM page

---

dao/src/main/kotlin/repositories/ortrun/DaoOrtRunRepository.kt
dao/src/test/kotlin/repositories/ortrun/DaoOrtRunRepositoryTest.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
services/hierarchy/src/main/kotlin/OrtRunService.kt

This PR introduces a new function to find ORT runs before a given reference time that only returns the IDs of matched runs. For the use case of deleting old ORT runs, this is way more efficient. Previously, fully initialized ORT run objects were retrieved with all their associations. For a larger number of affected runs, this took very long and consumed lot of resources.

Make deleting old ort runs more efficient

---

buildSrc/src/main/kotlin/ort-server-kotlin-conventions.gradle.kts

When detekt runs with type resolution, it executes a superset of the rules compared to running without type resolution. So it does not make sense to additionally run the vanilla "detekt" task.

build(gradle): Make `detektAll` only run tasks with type resolution

---

logaccess/spi/src/main/kotlin/LogFileService.kt
logaccess/spi/src/test/kotlin/LogFileServiceTest.kt

When downloading log file archives the user can specify the components for which logs should be retrieved. If here a worker was specified that did not run, the archive contained an empty log file. Since this is confusing, just filter out empty files when creating the archive with logs.

fix(logaccess): Do not include empty log files in the log archive

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/JobConfigurations.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
model/src/commonMain/kotlin/JobConfigurations.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerDownloader.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerWorker.kt
workers/analyzer/src/test/kotlin/AnalyzerDownloaderTest.kt

Add a parameter `submoduleFetchStrategy`to the Analyzer JobConfiguration that allows specifying how repository submodules should be fetched. This includes the options to fetch submodules recursively or to fetch only the top level  submodules, providing greater flexibility in submodule handling.
Don't fetch submodules at all: _DISABLED_ (same as _recursiveCheckout_ = false)
Fetch all nested submodules recursively: _FULLY_RECURSIVE_ (same as _recursiveCheckout_ = true)
New: Only fetch the top level submodules: _TOP_LEVEL_ONLY_ 
I decided to keep the parameter _recursiveCheckout_ working for now and mark it as deprecated, because there exist job configurations in the database that still hold it, and these would no longer work after an ORT Server update. Additionally, this allows to relaxed …

feat(analyzer): Introduce new JobConfiguration parameter for submodules

---

storage/s3/build.gradle.kts
storage/s3/src/main/kotlin/S3StorageProvider.kt

New versions of the AWS SDK changed the default integrity protection, see [1]. This caused errors in our environment using Dell ECS when uploading reports as described under [2].
The upload works again when providing a checksum. Therefore, calculate such a checksum and specify it when uploading data.
[1]: https://github.com/awslabs/aws-sdk-kotlin/discussions/1504
[2]: https://github.com/aws/aws-sdk-java-v2/issues/5711

fix(s3): Provide a checksum when uploading data

---

.github/workflows/docker-build.yml
tasks/build.gradle.kts
tasks/src/main/kotlin/TaskRunner.kt
tasks/src/main/kotlin/impl/DeleteOldOrtRunsTask.kt
tasks/src/main/resources/application.conf
tasks/src/test/kotlin/TaskRunnerTest.kt
tasks/src/test/kotlin/impl/DeleteOldOrtRunsTaskTest.kt

This PR adds a first task to the recently introduced project for maintenance tasks which enforces the data retention policy for ORT runs.

Add a task to delete old ORT runs

---

cli/build.gradle.kts
cli/src/main/kotlin/OrtServerMain.kt

The new name is `osc` which was decided in a public vote, see [1].
[1]: https://github.com/eclipse-apoapsis/ort-server/discussions/1794

feat(cli): Change the name of the ORT Server CLI executable

---

dao/src/main/kotlin/tables/ScanSummariesTable.kt
workers/scanner/src/main/kotlin/scanner/OrtServerScanResultStorage.kt
workers/scanner/src/test/kotlin/OrtServerScanResultStorageTest.kt
workers/scanner/src/test/kotlin/ScanResultFixtures.kt

When reading scan results, do not include the findings of the results,
but return stripped down `ScanResult` objects with only basic properties
initialized. The findings are never evaluated because they are already
contained in the database. This is a significant optimization since
loading and mapping large scan results is an expensive operation.

Scan storage read optimization

---

cli/src/main/kotlin/StartCommand.kt
cli/src/test/kotlin/StartCommandTest.kt

The command now accepts the CreateOrtRun object either as a JSON string or as a path to a JSON file.

feat(cli): Accept CreateOrtRun object in run command

---

.github/workflows/check-issue-links.yml

This fixes the check for PRs from forks.

fix(github): Do not assume PR heads to come from `origin`

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx

The note sounded a bit as if there were immediate plans to be able to run without the analyzer, but this is not the case.

chore(ui): Remove the note about the analyzer job being mandatory

---

.github/workflows/check-issue-links.yml

This should fix another permission issue [1] when creating a PR from a fork, see the docs at [2].
[1]: https://github.com/eclipse-apoapsis/ort-server/actions/runs/12989497197/job/36222632642#step:7:22
[2]: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target

fix(github): Check issue links in the context of the base of the PR

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt

The `value` property was not mapped when converting an API object to a model object.
Fixes #1894.

fix(mapping): Fix mapping of environment variable declarations

---

workers/common/src/main/kotlin/common/env/EnvironmentModule.kt
workers/common/src/main/kotlin/common/env/GitConfigGenerator.kt
workers/common/src/main/kotlin/common/env/GitCredentialsGenerator.kt
workers/common/src/test/kotlin/common/env/GitConfigGeneratorTest.kt
workers/common/src/test/kotlin/common/env/GitCredentialsGeneratorTest.kt
workers/scanner/src/main/resources/application.conf

Before a scan starts in a Scanner pod, generate a `.gitconfig` environment file containing URL `insteadOf` sections. These are required if the repository contains submodules specified using SSH URLs.
The `insteadOf` sections can either be generated using default values in `application.conf` or customized via the environment variable `GIT_CONFIG_URL_INSTEAD_OF`. This allows flexibility in defining what URL `insteadOf` sections are created in `.gitconfig`.

feat(scanner): Generate .gitconfig file with URL insteadOf sections

---

dao/src/main/kotlin/tables/ScanSummariesTable.kt
dao/src/main/kotlin/tables/shared/IssuesTable.kt
services/hierarchy/src/main/kotlin/IssueService.kt
workers/scanner/src/main/kotlin/scanner/OrtServerScanResultStorage.kt
workers/scanner/src/main/kotlin/scanner/ScannerRunner.kt
workers/scanner/src/main/kotlin/scanner/ScannerWorker.kt
workers/scanner/src/test/kotlin/OrtServerScanResultStorageTest.kt
workers/scanner/src/test/kotlin/ScanResultFixtures.kt
workers/scanner/src/test/kotlin/ScannerRunnerTest.kt
workers/scanner/src/test/kotlin/ScannerWorkerTest.kt

This PR further optimizes the storing of scan results by preventing that issues are unnecessarily loaded when constructing an ORT scanner run. Refer to the single commits for further information.

Scan storage read issues optimization

---

ui/src/helpers/get-status-class.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/package-manager-field.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/reporter-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-types.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts

This PR adds an option (off by default) to deduplicate the dependency tree for the different reports. This is a global option currently, but only used for the WebApp due to none of the other supported reports having the option implemented in ORT. 
When creating a new ORT run from scratch, the option needs to specifically be set to on, and even then it will only affect the WebApp, so there shouldn't be any side effects for any other reports as such.

ui: Add dependency tree deduplication option for WebApp

---

ui/src/components/form/password-input.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/secrets/$secretName/edit/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/secrets/create-secret/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/secrets/$secretName/edit/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/secrets/create-secret/index.tsx
ui/src/routes/organizations/$orgId/secrets/$secretName/edit/index.tsx
ui/src/routes/organizations/$orgId/secrets/create-secret/index.tsx

Add a new `PasswordInput` component that hides the value by default. The input contains a button to toggle between showing and hiding the input.
Use this component to hide the values of secrets by default.
Fixes #1940.

feat(ui): Hide secret values by default

---

workers/analyzer/docker/Analyzer.Dockerfile

The workaround introduced by e53580ac had no effect on some projects; corepack was still unable to install PNPM dynamically. Another approach described at [1] does the trick by explicitly installing the latest version of corepack. This version has been updated to accept the changed
certificates.
[1]: https://github.com/nodejs/corepack/issues/612#issuecomment-2629496091

fix(analyzer): Use the latest version of corepack

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/routes/index.tsx
ui/src/routes/organizations/$orgId/-components/organization-product-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-repository-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/repository-runs-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/runs/index.tsx
ui/src/store/table-prefs.store.ts

With this PR, user's choices for the page sizes of organizations, products, repositories and ORT runs data tables are seamlessly saved and persisted to browser's local storage, to improve the UX for ORT Server UI.

ui: Save some user preferences to browser's local storage

---

api/v1/client/src/commonMain/kotlin/auth/AuthService.kt
cli/src/main/kotlin/LoginCommand.kt
cli/src/main/kotlin/utils/AuthenticationUtils.kt
cli/src/test/kotlin/AuthLoginCommandTest.kt

Add the `offline_access` scope when requesting authentication and refresh tokens in the CLI. This ensures that the authentication provider issues **long-lived refresh tokens**, allowing the CLI to obtain new access tokens without requiring the user to log in frequently.
This allows for having long-lived refresh tokens for the CLI, while still having the refresh tokens for the web application expire after a shorter period of time in case there is no user activity.
Such refresh token will no langer have a `exp` (expiration) claim. However, in authentication providers like Keycloak there **are** policies that enable to invalidate them nevertheless after a period of time of inactivity. This mechanism allows to have a regular automatic **clean-up of long-lived CLI sessions**, avoiding the …

feat(auth): Add "offline_access" scope for long-lived refresh tokens

---

dao/src/main/resources/db/migration/V93__projectsPackagesCascadeDelete.sql
services/hierarchy/src/main/kotlin/OrphanRemovalService.kt
services/hierarchy/src/test/kotlin/OrphanRemovalServiceTest.kt

When archive scans are removed from database, some of orphaned entities stays in database, just occupying space, and deteriorating performance. To prevent this, obsolete (orphaned) records are deleted.

feat(database): Remove entities orphaned with removing ort run

---

workers/analyzer/src/test/kotlin/AnalyzerDownloaderTest.kt

The test case "throw an exception if the VCS type cannot be determined from the URL" was failing on local execution due to an `IOException` because of a missing local Mercurial installation. To prevent this, use mocking in this case, so that the test does not depend on the local environment.

test(analyzer): Fix a locally failing test case

---

workers/common/src/main/kotlin/common/env/config/EnvironmentConfigLoader.kt

Small improvements to the `EnvironmentConfigLoader`

---

.github/workflows/publish-website.yml
.github/workflows/release.yml

This avoids these workflows to always fail when doing testing in a forked repository. See the commit messages for details.

Run some workflows only in the original repository

---

ui/src/components/form/as-optional-field.ts
ui/src/components/form/optional-input.tsx
ui/src/routes/admin/users/create-user/index.tsx
ui/src/routes/create-organization/index.tsx
ui/src/routes/organizations/$orgId/create-product/index.tsx
ui/src/routes/organizations/$orgId/infrastructure-services/create/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/create-repository/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/secrets/create-secret/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/secrets/create-secret/index.tsx
ui/src/routes/organizations/$orgId/secrets/create-secret/index.tsx

This PR gets rid of most React warnings about form components transferring from `uncontrolled` to `controlled` state by:
1. Providing default values for mandatory form fields.
2. Handling optional fields in a special way, also allowing proper `Zod` validation for optional fields, whenever user inputs something to them.
As an example of handling optional fields, the user creation form is modified accordingly. If this approach is acceptable, other forms would be fixed in a follow-up PR.
This is a more proper alternative to #1946.

ui: Improve form handling

---

core/src/main/kotlin/plugins/Authentication.kt

Change the logger in the authentication plugin to use the `OrtPrincipal` class instead of Ktor's `Application` class. This makes the debug logs visible, because the minimum log level for Ktor is set to `INFO`. Using `OrtPrincipal` makes sense because all authentication information is stored in that object.

fix(core): Use `OrtPrincipal` instead of `Application` for logging

---

dao/src/main/resources/db/migration/V94__addVariousIndexes.sql

Add several indexes to speed up the queries executed by the statistics endpoints. Testing with several organizations and products with many repositories shows that these indexes improve performance by more than 50 percent.

chore(dao): Add indexes to speed up statistics queries

---

ui/src/routes/create-organization/index.tsx
ui/src/routes/organizations/$orgId/create-product/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/create-repository/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/settings/index.tsx
ui/src/routes/organizations/$orgId/settings/index.tsx

PR #1963 started improving validation for some forms. This PR continues the work by 
- requiring names of organizations and products to be non-empty strings
- getting rid of the React warnings coming from the optional description fields in the organization and product create forms

ui: Improve validation for item creation and editing

---

dao/src/main/resources/db/migration/V95__projectsOrphanEntitiesFix.sql
services/hierarchy/src/test/kotlin/OrphanRemovalServiceTest.kt

Add project_scopes_project_id_fkey constraint for project_scopes table to enable cascade deletion of orphaned projects

fix(database): Add missing constraint for project cascade deletion

---

workers/analyzer/src/test/kotlin/AnalyzerDownloaderTest.kt

In the only test that uses mocking, call the variant of `mockkObject` that takes a `block` as it automatically unmocks the object afterwards. This simplifies the code a bit and provides a better overview where mocking is used.

chore(workers): Nest mock configuration into the belonging object

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/ShortestDependencyPath.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/analyzerrun/DaoAnalyzerRunRepository.kt
dao/src/main/kotlin/repositories/analyzerrun/ShortestDependencyPathsTable.kt
dao/src/main/resources/db/migration/V96__addShortestDependencyPathsTable.sql
dao/src/test/kotlin/repositories/analyzerrun/DaoAnalyzerRunRepositoryTest.kt
dao/src/testFixtures/kotlin/Fixtures.kt
model/src/commonMain/kotlin/repositories/AnalyzerRunRepository.kt
model/src/commonMain/kotlin/runs/PackageWithShortestDependencyPaths.kt
model/src/commonMain/kotlin/runs/ShortestDependencyPath.kt
services/hierarchy/src/main/kotlin/PackageService.kt
services/hierarchy/src/test/kotlin/PackageServiceTest.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerWorker.kt
workers/analyzer/src/main/kotlin/analyzer/Utils.kt
workers/analyzer/src/test/kotlin/AnalyzerWorkerTest.kt
workers/analyzer/src/test/kotlin/UtilsTest.kt
workers/common/src/main/kotlin/common/OrtRunService.kt

Add information about shortest dependency paths to the packages endpoint response. This will give a quick overview for how deeply nested a dependency is in the project. For simplicity, only one path for a package for each project is returned (only the shortest path across scopes is picked).

Extend the packages endpoint with the shortest dependency path

---

.run/Advisor Worker.run.xml
.run/Analyzer Worker.run.xml
.run/Compose Latest.run.xml
.run/Orchestrator.run.xml
docker-compose.yml
orchestrator/build.gradle.kts
workers/advisor/build.gradle.kts
workers/analyzer/build.gradle.kts

This adds a bunch of run configurations for local development where everything, incl. the UI, is built from the latest source code. This allows to conveniently set breakpoints e.g. in the backend code, which is triggered by user actions in the frontend running on localhost.
To make this work, a developer first needs to launch the "Compose Latest" run configuration to build all Docker images locally, which will take some time. Once all containers are up, one or multiple of the remote debug configurations can be attached, depending on which Gradle modules the developer wants to be able to hit breakpoints. For now, only three modules are pre-configured: The orchestrator, the analyzer worker, and the advisor worker. Each come with their own remote debugging port configurations which needs to …

build: Add Docker-Compose-based IntelliJ run configurations for debugging

---

ui/src/components/dependency-paths.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx

This is the UI counterpart for #1882. Please note that this whole package details section will be revamped in later PRs, so this is only the initial/minimal implementation for the UI.
Question: Do we always want to show the "Shortest dependency paths" section in the package details, and notify the user in case there are none found? The most prominent reason for this being that the run is so old that the data isn't available, so the user should rerun to get the paths.

ui: Show the shortest dependency paths

---

kubernetes/jobmonitor/src/test/kotlin/JobWatchHelperTest.kt
model/src/commonMain/kotlin/orchestrator/OrchestratorMessage.kt
orchestrator/src/main/kotlin/Orchestrator.kt
workers/advisor/src/main/kotlin/advisor/AdvisorComponent.kt
workers/advisor/src/test/kotlin/AdvisorEndpointTest.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerComponent.kt
workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/config/src/main/kotlin/ConfigComponent.kt
workers/config/src/test/kotlin/ConfigWorkerTest.kt
workers/config/src/test/kotlin/EndpointTest.kt
workers/evaluator/src/main/kotlin/evaluator/EvaluatorComponent.kt
workers/evaluator/src/test/kotlin/EvaluatorEndpointTest.kt
workers/notifier/src/main/kotlin/notifier/NotifierComponent.kt
workers/notifier/src/test/kotlin/NotifierEndpointTest.kt
workers/reporter/src/main/kotlin/reporter/ReporterComponent.kt
workers/reporter/src/test/kotlin/reporter/ReporterComponentTest.kt
workers/reporter/src/test/kotlin/reporter/ReporterEndpointTest.kt
workers/scanner/src/main/kotlin/scanner/ScannerComponent.kt
workers/scanner/src/test/kotlin/ScannerEndpointTest.kt

Previously, the orchestrator just created generic issues like "The analyzer worker failed due to an unexpected error", swallowing the message of the underyling exception that occurred in the worker.
This change adds code to forward exception messages to be able to create meaningful issue messages.
Resolves #2034.

feat: Forward worker error messages to the orchestrator

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/-components/product-vulnerability-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/index.tsx
ui/src/schemas/index.ts

Also add filtering by the package ID to product vulnerability table, which was accidentally omitted from #2049.

ui: Enable filtering the vulnerability tables with rating

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/-components/product-vulnerability-table.tsx

As per Double Open's team decision, use "Package ID" consistently in  every place where package's identifier information is shown. This is more descriptive than a mere "Package", because we are showing identifying information for the package rather than the whole package's representation.

feat(ui): Use "Package ID" for package identifiers

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx

Please note that the products vulnerability table's component structure is different than the ORT result's item tables, and needs to be handled differently, which will be done in a follow-up PR.

ui: Show number of items matching filters in the title of run results table pages

---

.gitignore
.idea/copyright/Apache_2_0_ORT_Server.xml
.idea/copyright/profiles_settings.xml
REUSE.toml

Define and configure Apache-2.0 with ORT Server Authors' copyright as the default copyright header in IntelliJ IDEA.

chore(dev): Share the default Apache-2.0 license header

---

cli/src/commonMain/kotlin/ContextStorage.kt
cli/src/commonMain/kotlin/Extensions.kt
cli/src/commonMain/kotlin/InfoCommand.kt
cli/src/commonMain/kotlin/LogsCommand.kt
cli/src/commonMain/kotlin/ReportsCommand.kt
cli/src/commonMain/kotlin/StartCommand.kt

Before this change, when running in a CI/CD environment, the `osc` user has to use `jq` or similar tools to store the ORT Run ID if they want to be able to e.g. retrieve the reports after the run succeeded.
Remove this requirement, by storing the run ID started by the CLI, in a context file, which is then used in subsequent commands.

CLI: Store some contextual information for easier usage

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/Project.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/main/kotlin/di/Module.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/analyzerrun/ProjectsTable.kt
services/hierarchy/src/main/kotlin/ProjectService.kt
services/hierarchy/src/test/kotlin/ProjectServiceTest.kt

Introduce a new endpoint to retrieve the projects associated with an ORT run. 
To enable sorting on the primary key column, the helper variable `sortableId` is introduced by wrapping the default id column with the sortable() extension. This change allows the primary key to be sorted in queries just like any other column. Every other column in the table is not unique.
Resolves #1613

Get projects for run

---

ui/src/helpers/get-issue-category.ts

Double Open Scanner (DOS) plugin includes some issue logging for  its infrastructure failures. Add these to the UI so issues related to DOS infrastructure are not categorized as "Other".

feat(ui): Improve categorization of issues coming from DOS

---

workers/config/src/main/kotlin/ValidationScriptTemplate.kt

In [1] `ORT_SERVER_VERSION` was moved from the `model` module to a new systems utils module. As `model` was imported before, add the new location to the default imports of the validation script as well.
[1]: https://github.com/eclipse-apoapsis/ort-server/commit/a0a86

fix(workers): Add system utils as default imports for validation script

---

ui/index.html

This reverts commit 40fe0e16f7438c6926f257ad07199563b95a428e.
The fix only worked when loading the root URL of the UI, not when loading it from any subpath like `organizations/1`. Revert the change to make the favicon at least work consistently when the UI is not deployed to a subpath.
Relates to #1916.

Revert "fix(ui): Make the favicon path relative"

---

api/v1/client/build.gradle.kts
cli/build.gradle.kts
utils/system/build.gradle.kts

As of Kotlin 1.9.20 the hierarchy template is applied by default unless
kotlin.mpp.applyDefaultHierarchyTemplate = false
is set, and it only needs to be re-applyed manually if custom source sets were configured with `dependsOn`-calls [1].
[1]: https://kotlinlang.org/docs/multiplatform-hierarchy.html#additional-configuration

build(Gradle): Do not call `applyDefaultHierarchyTemplate()`

---

ui/src/components/not-found-error.ts
ui/src/routes/runs/$runId/index.tsx

fix(ui): Correct UI behaviour when searching for a non-existing run

---

.github/workflows/release.yml

I tested this change on my personal fork.
You can see there how a new release will look like: https://github.com/MarcelBochtler/ort-server/releases/tag/0.1.0-RC30

Release: Add CLI as release artifact

---

.run/osc --version [jvm].run.xml

To run the CLI in the IDE using the JVM target, the Gradle task `runJvm` has to be used.
Add a run configuration that sets the args to `--version` to show how arguments can be set in these Gradle run configurations.

chore(dev): Add exemplary run configuration to run and debug the CLI

---

core/src/main/kotlin/api/RunsRoute.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/advisorrun/VulnerabilitiesTable.kt
services/hierarchy/src/main/kotlin/VulnerabilityService.kt
services/hierarchy/src/test/kotlin/VulnerabilityServiceTest.kt

Align with the convention of commit https://github.com/eclipse-apoapsis/ort-server/commit/8c1d23ff0067850069600ef5a122bf57372b924d#diff-07702ede8522e232eb239906b7cf8ef6f3b5451730aeb6b5732cca33fcef54c6R42 that predates the addition of these sorting fields.

refactor: Align to use camel case for sorting field names

---

ui/src/routes/runs/$runId/index.tsx

Add a styled `errorComponent` to display a more user-friendly message when a `NotFoundError` occurs, aligning with the consistent use of the custom `Card` compoent across other routes.
New look:

feat(ui): Style `errorComponent` for global run search

---

services/hierarchy/src/main/kotlin/VulnerabilityService.kt
services/hierarchy/src/test/kotlin/VulnerabilityServiceTest.kt

As there is no need to sort by the identifier properties separately, combine the sorting for these fields.

refactor(services): Combine sorting for identifier fields

---

website/package.json
website/pnpm-lock.yaml

Version 4.3.5 breaks the local search plugin, for details see [1] and [2].
[1]: https://github.com/easyops-cn/docusaurus-search-local/issues/502
[2]: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1096

deps: Downgrade docusaurus-openapi-docs to 4.3.4

---

core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt

Return 404 HTTP error code instead of 500 when triggering ORT run on non existing repository.

fix: Return proper HTTP error code when calling non existing repo

---

scripts/compose/grafana/provisioning/dashboards/ort-run-component-logs.json

Only time and message shown for the log lines, lines are filtered with run ID and log levels (individually for each component). Gutter coloring for the log levels works.

New logging dashboard to Grafana

---

services/hierarchy/src/main/kotlin/IssueService.kt
services/hierarchy/src/test/kotlin/IssueServiceTest.kt

Return Scanner issues that are stored as part of Scan Summaries. Previously, these issues were not included in the API endpoints for retrieving issues, leading to discrepancies between issues in reports and those displayed in the ORT Server Web Application.
Fixes #1534.

fix(api): Additionally return Scanner issues for ORT runs

---

ui/.eslintrc.cjs
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/package-manager-field.tsx

Regarding the second commit, I'd like to get an opinion from @mmurto as the `console.error()` has come from you originally. Personally I've never encountered a situation where it would've been triggered, and would be willing to drop the whole line from code.

No console logs in production code

---

ui/src/routes/organizations/$orgId/infrastructure-services/$serviceName/edit/index.tsx
ui/src/routes/organizations/$orgId/infrastructure-services/create/index.tsx
ui/src/routes/organizations/$orgId/infrastructure-services/index.tsx

This PR addresses two issues:
1. Infrastructure service table's overflow off-screen to the right: 
2. Simplification of creation and editing of the infrastructure services with usage of dropdown lists for the secrets:

ui: Improve infrastructure handling

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
core/src/main/kotlin/api/RepositoriesRoute.kt

Apply the missing mapping from a Model object to an API object for to the `OrtRunSummary` entities returned from the REST endpoint `/api/v1/repositories/{repositoryId}/runs`.

fix(api): Apply mapping to API for OrtRunSummaries

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/route.tsx

See [1].
[1]: https://lucide.dev/icons/logs

feat(ui): Add an icon to the "Logs" menu for a run's details

---

scripts/docker/keycloak/master-realm.json
ui/src/components/header.tsx
ui/src/hooks/use-user.ts

Below the logged-in users username in the user account menu in the top right corner, additionally display the user's full name.

feat(ui): Add user's full name in user account menu

---

.github/workflows/check-issue-links.yml

Let `jq` itself remove duplicates (and sort) [1], and also the conversion to a comma-separated list [2]. This fixes the issue with a trailing comma in the list.
[1]: https://jqlang.org/manual/#unique-unique_by
[2]: https://jqlang.org/manual/#join

ci(github): Improve the check for issue links

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/OrtRun.kt
api/v1/model/src/commonMain/kotlin/OrtRunSummary.kt
api/v1/model/src/commonMain/kotlin/UserDisplayName.kt
core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/main/kotlin/authorization/OrtPrincipal.kt
core/src/main/kotlin/services/OrchestratorService.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/ortrun/DaoOrtRunRepository.kt
dao/src/main/kotlin/repositories/ortrun/OrtRunsTable.kt
dao/src/main/kotlin/repositories/userDisplayName/UserDisplayNamesTable.kt
dao/src/main/resources/db/migration/V98__userDisplayNames.sql
model/src/commonMain/kotlin/OrtRun.kt
model/src/commonMain/kotlin/OrtRunSummary.kt
model/src/commonMain/kotlin/UserDisplayName.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/repository-runs-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/index.tsx

Add username and full name (if present) of the user that triggered a scan to the scan representation in the database, and also provide these names when querying scans using the REST API in order to allow to display them in the UI in a user-friendly way.
Add username and full name (as tooltip) of the user that triggered a scan to the list of scans per repository and in the detail view of the scan.
Fixes #2132.
See the respective commits for details.

feat(api): Add name of the user that triggered a scan

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/advisor-job-details.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/analyzer-job-details.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/evaluator-job-details.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/job-title.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/notifier-job-details.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/reporter-job-details.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/scanner-job-details.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/route.tsx

This PR starts the refactoring of the (run) configuration page by simplifying the looks of it, adding the general run info which is missing from the top bar to the page, plus simplifying the code.
Note for the reviewers: the actual code changes to the page (especially in [this commit](https://github.com/eclipse-apoapsis/ort-server/pull/2286/commits/06f43d669c52be945df34d3d84064776ea66f62f)) are relatively small, even if the git hunks look big.

ui: Start refactoring the configuration page

---

api/v1/model/src/commonMain/kotlin/Licenses.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
services/hierarchy/src/main/kotlin/PackageService.kt
services/hierarchy/src/test/kotlin/PackageServiceTest.kt

The endpoint now returns the distinct processed declared licenses for packages found in a run.
These will be used to provide select filter options in the packages table in the UI.

feat: Add initial endpoint for the licenses for packages

---

secrets/vault/src/main/kotlin/VaultSecretsProviderFactory.kt

To diagnose problems with access to a HashiCorp Vault instance, it is helpful to know the exact configuration. Therefore, log it when creating a `VaultSecretProvider` instance.

chore(vault): Extend logging

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx

Avoid confusion to instead use e.g. the URL with the path to a GitHub repository.

docs(ui): Clarify that the `path` is relative to the repository root

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/analyzer-job-details.tsx

This is similar to showing package config provider in the evaluator section, from where the code was copied and adapted.

feat(ui): Show curation providers in the analyzer run config section

---

ui/src/components/dependency-paths.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx

PR #2309 laid the groundwork for setting and saving user preferences, so in this PR, either the ORT ID or PURL will be shown as the package ID in the Packages table. 
The default is ORT ID so there are no changes to the UI by default - the user needs to specifically go to the Settings page (accessible from the top-right menu) and choose the "PURL" option to see PURLs being used in the table.
There are several other tables where we want to show PURL instead of ORT ID in the "Package ID" column, but the corresponding endpoints do not return the purl, so they will need to be extended. Such endpoints are:
- all endpoints returning vulnerabilities
- issues endpoint
- rule violations endpoint

ui: Display configured Package ID in Packages table

---

website/src/pages/index.module.css

Do not use the same link color as for the background. This is a fixup for fe561a7. Also see [1].
[1]: https://github.com/oss-review-toolkit/ort/pull/9718

fix(website): Make the link to ORT readable

---

orchestrator/src/main/kotlin/Entrypoint.kt
transport/activemqartemis/src/main/kotlin/ArtemisMessageReceiverFactory.kt
transport/activemqartemis/src/test/kotlin/ArtemisMessageReceiverFactoryTest.kt
transport/kubernetes/src/test/kotlin/KubernetesMessageReceiverFactoryTest.kt
transport/rabbitmq/src/main/kotlin/RabbitMqMessageReceiverFactory.kt
transport/rabbitmq/src/test/kotlin/RabbitMqMessageReceiverFactoryTest.kt
transport/spi/src/main/kotlin/MessageReceiverFactory.kt
transport/spi/src/test/kotlin/EndpointComponentTest.kt
transport/spi/src/testFixtures/kotlin/Utils.kt
transport/sqs/src/main/kotlin/SqsMessageReceiverFactory.kt
transport/sqs/src/test/kotlin/SqsMessageReceiverFactoryTest.kt
workers/advisor/src/main/kotlin/advisor/AdvisorComponent.kt
workers/advisor/src/main/resources/application.conf
workers/analyzer/src/main/kotlin/analyzer/AnalyzerComponent.kt
workers/analyzer/src/main/resources/application.conf
workers/config/src/main/kotlin/ConfigComponent.kt
workers/config/src/main/resources/application.conf
workers/evaluator/src/main/kotlin/evaluator/EvaluatorComponent.kt
workers/evaluator/src/main/resources/application.conf
workers/notifier/src/main/kotlin/notifier/NotifierComponent.kt
workers/notifier/src/main/resources/application.conf
workers/reporter/src/main/kotlin/reporter/ReporterComponent.kt
workers/reporter/src/main/resources/application.conf
workers/scanner/src/main/kotlin/scanner/ScannerComponent.kt
workers/scanner/src/main/resources/application.conf

Add a way to configure workers to handle only a single message. This is useful when using Keda instead of the Kubernetes transport to create Kubernetes jobs which is used in an Azure deployment because the Kubernetes transport does not support the required configuration, and because it is more straightforward to configure the Kubernetes jobs with YAML files instead of environment variables passed to the orchestrator.

Add a mode to let workers handle only a single message

---

core/build.gradle.kts
core/src/main/kotlin/plugins/Authentication.kt
core/src/main/resources/application.conf
core/src/test/kotlin/auth/AuthenticationTest.kt
core/src/test/resources/application-test-auth.conf
core/src/test/resources/application-test.conf
gradle/libs.versions.toml

Requesting the user roles from Keycloak can take some time, slowing down endpoint which would otherwise respond very fast. For example, it was observed in a setup with Keycloak 24 that the Keycloak role requests took between 500-1000ms while the remaining request takes <50ms.
This slows down the UI, especially on pages like the repository list, where a single page makes a lot of API requests.
To mitigate the issue, cache Keycloak roles for one minute. This speeds up such UI pages while at the same time ensuring that changes in the Keycloak roles are quickly reflected by the UI.

feat(core): Cache Keycloak roles for one minute

---

ui/src/components/charts/job-durations.tsx
ui/src/globals.css

Some minor improvements to the run timings bar chart:
- clicking any bar takes the user to the corresponding run's overview page
- bars use colors from the corresponding ORT icons

ui: Improvements to bar chart

---

tasks/src/main/resources/logback.xml

Copy `logback.xml` from the Kubernetes Job Monitor deployment to align the logging output and configuration with other ORT Server components.

feat(tasks): Add logging configuration

---

.ort.yml

The vulnerable packages are no longer part of the dependency tree. Therefore, the vulnerability resolutions can be removed.

chore: Remove vulnerability resolutions

---

ui/src/helpers/job-helpers.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/issues-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/packages-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/rule-violations-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/vulnerabilities-statistics-card.tsx

With this PR, the statistics cards correctly indicate the number of items found, after each corresponding job is finished, instead of a "Failed" message.

ui: Fix statistics cards in the run overview page

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/components/ui/accordion.tsx
ui/src/components/ui/avatar.tsx
ui/src/components/ui/breadcrumb.tsx
ui/src/components/ui/dialog.tsx
ui/src/components/ui/dropdown-menu.tsx
ui/src/components/ui/label.tsx
ui/src/components/ui/popover.tsx
ui/src/components/ui/select.tsx
ui/src/components/ui/separator.tsx
ui/src/components/ui/sheet.tsx
ui/src/components/ui/switch.tsx
ui/src/components/ui/tabs.tsx
ui/src/components/ui/tooltip.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/analyzer-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx

React 19 and Tailwind v4 brought with them some changes, which to the `shadcn-ui` library are mostly big simplifications to the code. Typical examples of such are deprecation of `React.ElementRef`, making `React.forwardRef` obsolete, and adding `data-slot` attribute, that helps in styling the components with Tailwind.
Some `shadcn-ui` components have also undergone some minor tweaks and additions, so it warrants to update them, as we've mostly had the same components from the beginning of the project.
In this PR, all `shadcn-ui` components for which only formatting-related changes have been made locally, are updated by
1. Reinstalling the component (which overwrites the old one).
2. Correcting the code format.
3. Lint checking.
4. Checking for any warnings or errors in the browser's dev. …

ui: Update shadcn-ui "easy" components

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/User.kt
clients/keycloak/src/main/kotlin/DefaultKeycloakClient.kt
clients/keycloak/src/main/kotlin/KeycloakClient.kt
clients/keycloak/src/testFixtures/kotlin/KeycloakTestClient.kt
core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/api/UserWithGroupsHelper.kt
core/src/main/kotlin/apiDocs/OrganizationsDocs.kt
core/src/main/kotlin/apiDocs/ProductsDocs.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
core/src/test/kotlin/api/UserWithGroupsHelperTest.kt
model/src/commonMain/kotlin/User.kt
services/authorization/src/main/kotlin/UserService.kt
services/authorization/src/test/kotlin/UserServiceTest.kt

Implements: https://github.com/eclipse-apoapsis/ort-server/issues/2104
For the improved Users page as described in https://github.com/eclipse-apoapsis/ort-server/issues/2053, the ORT Server needs a new endpoint to return the list of users within an entity (organization, product, or repository). The endpoint should also clearly indicate which group (readers, writers, admins) each user belongs to.

2104 add endpoint users for entity

---

dao/src/main/kotlin/repositories/ortrun/DaoOrtRunRepository.kt
dao/src/test/kotlin/repositories/ortrun/DaoOrtRunRepositoryTest.kt
model/src/commonMain/kotlin/repositories/OrtRunRepository.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerDownloader.kt
workers/analyzer/src/main/kotlin/analyzer/AnalyzerWorker.kt
workers/analyzer/src/test/kotlin/AnalyzerDownloaderTest.kt
workers/analyzer/src/test/kotlin/AnalyzerWorkerTest.kt
workers/common/src/main/kotlin/common/OrtRunService.kt
workers/common/src/test/kotlin/common/OrtRunServiceTest.kt
workers/config/src/test/kotlin/ConfigWorkerTest.kt

If an ORT run is started with an empty `revision`, the analyzer worker uses the default branch of the repository as revision. Store that as the `revision` of the ORT run to make clear what revision was used to initialize the repository.
Fixes #2082.

feat(analyzer): Set the default branch as ORT run revision

---

core/src/main/kotlin/di/Module.kt
dao/src/main/resources/db/migration/V99__addOrphanDeletionIndexes.sql
services/hierarchy/src/main/kotlin/OrphanRemovalService.kt
services/hierarchy/src/test/kotlin/OrphanRemovalServiceTest.kt
tasks/src/main/kotlin/TaskRunner.kt
tasks/src/main/kotlin/impl/DeleteOrphanedEntitiesTask.kt
tasks/src/main/resources/application.conf
tasks/src/test/kotlin/TaskRunnerTest.kt
tasks/src/test/kotlin/impl/DeleteOrphanedEntitiesTaskTest.kt

This PR reworks the service for deleting orphaned entities to speed up the task execution. Refer to the single commits for further details.

Rework deletion of orphaned entities

---

core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/apiDocs/ProductsDocs.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
model/src/commonMain/kotlin/authorization/ProductPermission.kt
model/src/commonMain/kotlin/authorization/ProductRole.kt

This commit introduces an endpoint to trigger consistent ORT runs across
all repositories belonging to a product. It addresses the need for
efficient product-wide analysis while maintaining individual run tracking
and configuration uniformity.
The implementation retrieves all repository IDs using
`getRepositoryIdsForProduct` and creates an ORT run for each via the
`OrchestratorService` with identical parameters (`revision`, `jobConfigs`,
`labels` etc.). It requires `TRIGGER_ORT_RUN` permission for security and
returns created runs with status `201`.

feat(api): Add endpoint to trigger ORT runs for all product repositories

---

config/git/README.md
config/git/src/main/kotlin/GitConfigFileProvider.kt
config/git/src/main/kotlin/GitConfigFileProviderAuthenticator.kt
config/git/src/main/kotlin/GitConfigFileProviderFactory.kt
config/git/src/test/kotlin/GitConfigFileProviderAuthenticatorTest.kt

Add support for password authentication to the `GitConfigFileProvider`.
This is implemented using a custom `Authenticator` which is temporarily
installed when cloning the config repository.

feat(git-config): Add support for private repositories

---

ui/src/components/delete-icon-button.tsx
ui/src/components/ellipsis-icon-button.tsx
ui/src/components/ui/user-group-row-actions.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/users/-components/repository-users-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/users/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/users/route.tsx
ui/src/routes/organizations/$orgId/products/$productId/users/-components/product-users-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/users/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/users/route.tsx
ui/src/routes/organizations/$orgId/users/-components/organization-users-table.tsx
ui/src/routes/organizations/$orgId/users/index.tsx
ui/src/routes/organizations/$orgId/users/route.tsx

On the level of Organizations, Products and Repositories allow admins to assign users to one one of the groups ADMINS, WRITERS or READERS, and also allow to change the assignments and delete users. Existing users and their respective role assignments are displayed in a table.
For details, please have a look at the respective commit messages.
Fixes #2053.

feat(ui): Enable assignment of users to groups

---

ui/src/components/data-table/data-table-pagination.tsx
ui/src/components/data-table/filter-multi-select.tsx
ui/src/components/ui/breadcrumb.tsx

Icons have been replaced by looking up their visual appearance at [1] and finding a similar one at [2].
[1]: https://react-icons.github.io/react-icons/
[2]: https://lucide.dev/icons/

refactor(ui): Consistenly use only Lucide React icons

---

.github/workflows/static-analysis.yml
cli/src/commonMain/kotlin/AuthCommand.kt
cli/src/commonMain/kotlin/InfoCommand.kt
cli/src/commonMain/kotlin/LoginCommand.kt
cli/src/commonMain/kotlin/LogsCommand.kt
cli/src/commonMain/kotlin/OrtServerMain.kt
cli/src/commonMain/kotlin/ReportsCommand.kt
cli/src/commonMain/kotlin/StartCommand.kt
cli/src/commonMain/kotlin/model/Exceptions.kt
cli/src/commonMain/kotlin/model/printables/CliPrintable.kt
cli/src/commonMain/kotlin/model/printables/MessagePrintable.kt
cli/src/commonMain/kotlin/model/printables/OrtRunPrintable.kt
cli/src/commonMain/kotlin/utils/PrintHelper.kt
cli/src/jvmTest/kotlin/InfoCommandTest.kt
cli/src/jvmTest/kotlin/StartCommandTest.kt
integrations/completions/osc-completion.bash
integrations/completions/osc-completion.fish
integrations/completions/osc-completion.zsh
scripts/cli/generate_completion_scripts.sh

Example for the human-readable `osc runs info` command:

CLI: Add `--json` option to make the CLI output machine readable

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/sbom/index.tsx

Add a **download icon** to the buttons for downloading CycloneDX or SPDX BOM reports in one of two possible formats, in order to improve the UX of this page. The icons act as a visual shorthand: They immediately tell the user that when the
button is pressed, the respective report is downloaded.
Additionally, add tooltips to the buttons.
Fixes #2052.

feat(ui): Add download icon to SBOM reports

---

ui/src/routes/admin/users/authorization/index.tsx

The old link was not working anymore, replace it with a link to the authorization docs on the website.

fix(ui): Update the link to the authorization docs

---

cli/build.gradle.kts

Kotlin 2.1.20 added DSL functionality to replace Gradle's application plugin [1].
Make use of this new DSL to configure the `jvmDistZip` and `jvmDistTar` tasks that can be used to package the JVM targets of the CLI.

feat(cli): Configure executable binary task for JVM target

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/projects/index.tsx

This fixes authors to be displayed in one string like
"Danny van BruggenJúlio Vilmar GesserSebastian Kirsch"

fix(ui): Separate authors by commas

---

cli/build.gradle.kts
cli/src/commonMain/kotlin/StartCommand.kt
gradle/libs.versions.toml

Instead of printing the run status every time the status is being polled, show a progress bar when using the `--wait` flag.
If the `--json` flag is used together with the `--wait` flag, the run status is only printed after the run finished.

CLI: Add progress bar when using --wait flag

---

transport/spi/src/main/kotlin/EndpointComponent.kt

Instead to use the user's home directory to store the keep-alive, now use the system temporary directory, as this approach is more robust for all kinds of worker docker images.

fix: Use system temporary directory for keep-alive file

---

core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt

Add a test to verify that the organizations endpoint returns an empty result for a user without read permission for any organization.

test(core): Add test for organizations endpoint

---

dao/src/main/kotlin/utils/JsonHashFunction.kt
workers/scanner/src/main/kotlin/scanner/OrtServerScanResultStorage.kt

There is no reason to have a `utils` package inside of another `utils` package.

refactor(dao): Fix the package of `JsonHashFunction`

---

scripts/compose/config/ort-server.params.kts

Configure ScanCode to accept stored scan results for the version range `[32.2.1,33.0.0[`. Previously, all packages had to be rescanned when ScanCode was upgraded.

feat(compose): Configure version range for ScanCode results

---

workers/analyzer/src/main/kotlin/analyzer/AnalyzerWorker.kt
workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/analyzer/src/test/kotlin/AnalyzerWorkerTest.kt
workers/common/src/main/kotlin/common/context/AuthenticationListener.kt
workers/common/src/main/kotlin/common/context/OrtServerAuthenticator.kt
workers/common/src/main/kotlin/common/context/WorkerContext.kt
workers/common/src/main/kotlin/common/context/WorkerContextImpl.kt
workers/common/src/main/kotlin/common/env/EnvironmentModule.kt
workers/common/src/main/kotlin/common/env/EnvironmentService.kt
workers/common/src/main/kotlin/common/env/NetRcManager.kt
workers/common/src/test/kotlin/common/context/OrtServerAuthenticatorTest.kt
workers/common/src/test/kotlin/common/context/WorkerContextFactoryTest.kt
workers/common/src/test/kotlin/common/env/EnvironmentServiceTest.kt
workers/common/src/test/kotlin/common/env/NetRcManagerTest.kt
workers/reporter/src/main/kotlin/reporter/ReporterWorker.kt
workers/reporter/src/test/kotlin/reporter/ReporterWorkerTest.kt
workers/scanner/src/main/kotlin/scanner/ScannerWorker.kt
workers/scanner/src/test/kotlin/ScannerWorkerTest.kt

This PR changes the way the `.netrc` file is generated with the goal to keep it in sync with the infrastructure services that are used by the current worker. This should avoid conflicts with multiple services referring to the same host.

Change generation of the .netrc file

---

ui/src/components/charts/job-durations.tsx
ui/src/globals.css
ui/src/helpers/get-status-class.ts
ui/tailwind.config.js

To assist in reviewing the PR, I've provided a page which shows all currently used colors (some of which are tuned in this PR) for different indicators. This page will possibly be part of the Admin section, once the customizable footer support is added, because it belongs to a same section ("Customization") - so the page is not part of this PR.

ui: Tune some UI colors

---

core/src/test/kotlin/testutils/OrtServerApplicationHelper.kt
core/src/test/kotlin/utils/ExtensionsTest.kt

It is unclear why detekt did not report these, it also did not help to enable the alternative `NoUnusedImports` rule.

chore: Remove unused imports

---

ui/src/helpers/get-status-class.ts

Demo page:
For discussion: for some elements, the black font is now almost too dark in light mode. Should it be fine-tuned?

feat(ui): Tune font colors for colourful elements

---

ui/src/routes/admin/route.tsx

While technically correct, there probably will be no other plugins for the foreseeable future. So use a shorter name to better match "User Management".

chore(ui): Remove "ORT" from "Plugin Management"

---

services/hierarchy/src/main/kotlin/IssueService.kt

Previously, the ORT Server UI **could** display issues unrelated to the current run. This fix in the backend REST endpoint implementation for _issues_ ensures that only issues belonging to the actual run are shown.

Show only relevant issues in ORT Server run view

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/ContentManagementSection.kt
components/authorization/implementation/src/main/kotlin/Extensions.kt
core/build.gradle.kts
core/src/main/kotlin/api/AdminRoute.kt
core/src/main/kotlin/apiDocs/AdminDocs.kt
core/src/main/kotlin/di/Module.kt
core/src/test/kotlin/api/AdminRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/contentSection/ContentManagementSectionTable.kt
dao/src/main/resources/db/migration/V100__addContentManagementSections.sql
model/src/commonMain/kotlin/ContentManagementSection.kt
services/content-management/build.gradle.kts
services/content-management/src/main/kotlin/ContentManagementService.kt
settings.gradle.kts
ui/src/components/footer.tsx
ui/src/routes/__root.tsx
ui/src/routes/admin/content-management/footer/index.tsx
ui/src/routes/admin/route.tsx

Add a REST API endpoint to consume and update dynamic content for the footer section of the UI, add a footer section to the UI that uses this endpoint, and add a configuration panel in the admin section of the UI that allows to view and update the dynamic footer content.
See the respective commits for details.
Fixes #2344.

Add custom footer content

---

docker-compose.yml
scripts/compose/graphite/conf/storage-aggregation.conf
scripts/compose/graphite/conf/storage-schemas.conf

The commit message explains what is done in this PR, as per advice from @mnonnenmacher, but a sanity check is needed. 
I did verify that the changes to the files mounted from `scripts/compose/graphite/conf` are mirrored properly to the container, and the local Docker Compose environment starts properly and seems to be working. Some verification of the new retention policies would need to be done.

Tune Graphite's retention policies

---

ui/src/components/error-component.tsx
ui/src/routes/organizations/$orgId/index.tsx

This PR fixes a bug that was found for a huge organization (over thousand repositories). Moreover, it introduces a general error boundary pattern that can be used elsewhere in the UI whenever a query response breaks the whole UI.
The 504 error was simulated by setting the organization statistics endpoint to return a 504 after a delay instead of an OK.
Loading state when fetching data:
Error fallback component when 504 happens:
Yes, the error title is a bit cheeky. It could be made as a prop, to generalize the component a bit.

ui: Prevent the UI from breaking with Gateway Timeout

---

ui/src/components/error-component.tsx
ui/src/routes/organizations/$orgId/index.tsx

#2605 introduced a simple way to isolate UI errors in the DOM by setting error boundaries. If an error happens inside an error boundary, an error component is rendered in place of the erroring sub-DOM, instead of breaking the UI.
This PR extends the error component to provide both "user-friendly errors" (for production) and "technical errors" (mainly used for debugging purposes). Some examples:
1. Explicit user-friendly error title (this is now set for the organization overview page):
2. Error message with default props:
3. The error component can even show the stack trace of the error:

ui: Extend the error component

---

components/plugin-manager/api/src/commonMain/kotlin/PluginDescriptor.kt
components/plugin-manager/implementation/build.gradle.kts
components/plugin-manager/implementation/src/main/kotlin/Plugin.kt
components/plugin-manager/implementation/src/main/kotlin/PluginEvent.kt
components/plugin-manager/implementation/src/main/kotlin/PluginEventStore.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/DisablePlugin.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/EnablePlugin.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/GetInstalledPlugins.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/DisablePluginIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/EnablePluginIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/GetInstalledPluginsIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/PluginManagerAuthorizationTest.kt
core/src/main/kotlin/di/Module.kt
core/src/main/kotlin/plugins/Koin.kt
core/src/main/kotlin/plugins/Routing.kt
core/src/test/kotlin/ApplicationTest.kt
core/src/test/kotlin/api/AbstractIntegrationTest.kt
core/src/test/kotlin/api/ErrorsIntegrationTest.kt
core/src/test/kotlin/api/HealthIntegrationTest.kt
core/src/test/kotlin/api/OpenApiIntegrationTest.kt
core/src/test/kotlin/auth/AuthenticationIntegrationTest.kt
core/src/test/kotlin/testutils/OrtServerApplicationHelper.kt
core/src/test/kotlin/utils/ExtensionsTest.kt
core/src/test/kotlin/utils/GenerateOpenApiSpec.kt
core/src/test/resources/application-test-auth.conf
core/src/test/resources/application-test.conf
dao/src/main/resources/db/migration/V102__pluginEvents.sql
dao/src/main/resources/db/migration/V103__pluginsReadModel.sql
ui/src/routes/admin/plugins/index.tsx

Prepare for enabling and disabling ORT plugins globally by creating the required configuration and UI, see the commit messages for details. The workers still ignore those settings, this needs to be changed in a later PR.
This PR introduces some code duplication mainly in integration tests, this will be addressed in a follow-up.

Prepare enabling and disabling ORT plugins globally

---

ui/src/routes/organizations/$orgId/products/$productId/-components/product-repository-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/create-repository/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/runs/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/settings/index.tsx

Extend the UI to:
Add inputs for the description to the forms for creating and editing repositories:
Show the description in the repository table:
Show the description in the repository overview:

UI: Set and show repository description

---

ui/src/components/delete-dialog.tsx
ui/src/components/delete-icon-button.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/users/-components/repository-users-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/users/-components/product-users-table.tsx
ui/src/routes/organizations/$orgId/users/-components/organization-users-table.tsx

1. Tooltip indicates the consequence of the removal action. Also a different icon is used here:
2. Delete confirmation icon title indicates what is about to be deleted:
3. Successful removal of a user from an organization -  the users table is immediately updated:
4.  The user still exists on the server:

ui: Fix removal of a user from an entity (org, prod, repo)

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/runs/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/-components/run-details-bar.tsx

This PR contains minor fixes and tweaks for the UI.
Repository URL in the title when not hovering over it:
Repository URL is rendered as blue when hovering over:
"Revision:" and the revision rendered on the same line. Moreover, "Created by:" falls back to showing the username in case full name doesn't exist:
For discussion: when changing the repository URL into a link, I decided to _not_ render it always as blue, to retain some consistency with the different titles in the UI. The link now turns blue only when hovering over with a mouse. This can easily be changed, however, if so decided.

ui: Minor tweaks

---

ui/src/components/header.tsx

Show ORT logo as a "Home" indicator":
Show the gravatar also as the menu indicator:

ui: Small tweaks for the header

---

dao/src/main/kotlin/repositories/ortrun/DaoOrtRunRepository.kt
dao/src/test/kotlin/repositories/ortrun/DaoOrtRunRepositoryTest.kt
services/hierarchy/src/test/kotlin/OrtRunServiceTest.kt

Ensure the housekeeping logic keeps at least one ORT run for each repository, even if it is older than the defined retention period. This improves continuity of scanning activities after long pauses.
Please check the respective commits for details.

feat(dao): Retain at least one ORT run per repository

---

components/plugin-manager/implementation/build.gradle.kts
components/plugin-manager/implementation/src/test/kotlin/endpoints/DisablePluginIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/EnablePluginIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/GetInstalledPluginsIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/PluginManagerAuthorizationTest.kt
shared/ktor-utils/build.gradle.kts
shared/ktor-utils/src/testFixtures/kotlin/AbstractIntegrationTest.kt

Reduce code duplication in the integration tests of the plugin manager by extracting common code into an abstract class. The `AbstractIntegrationTest` is added as a test fixture to the ktor-utils so that it can be used in all components.

test: Add an abstract integration test class to ktor-utils

---

cli/build.gradle.kts
shared/ktor-utils/build.gradle.kts
tasks/build.gradle.kts

Group names that are used for Maven coordinates should refer to the parent directory of a module to avoid having groups that contain only a single module. This provides better overview when browsing artifacts.

build(Gradle): Fix group names to refer to the module parent

---

ui/src/components/footer.tsx

This was a decision of today's alignment meeting.

feat(ui): Drop the border and background color from the footer

---

ui/src/routes/about/index.tsx

Do not use "download" as a verb, but as a noun for the title. Also drop "CLI" for simplicity.

chore(ui): Tweak the title for OSC download

---

ui/src/routes/admin/content-management/footer/index.tsx

Do not repeat "Footer" for the "Content" title, and capitalize "Markdown" in the placeholder text.

chore(ui): Trivially tweak words in the footer UI

---

ui/src/components/header.tsx

Make the conditionally shown administration item go frist and rename it to make clear it is not about an "admin" user but server "administration".
Similarly, make clear that "settings" are about the user, not the server.

chore(ui): Tweak profile menu items a bit

---

buildSrc/src/main/kotlin/ort-server-base-conventions.gradle.kts

See the note at [1] which says
SIG-Repo is now https://repo.blackduck.com
All users should update their configurations to use the new
repo.blackduck.com domain.
Also see the FAQ at [2].
[1]: https://sig-repo.synopsys.com/
[2]: https://community.blackduck.com/s/article/Black-Duck-Domain-Change-FAQ

build(gradle): Use the new Black Duck repository URL

---

core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/api/RepositoriesRoute.kt

This aligns the error response with other endpoints.

fix(core): Return `ErrorResponse` when disabled plugins are used

---

workers/common/src/main/kotlin/common/env/ConfigFileBuilder.kt
workers/common/src/main/kotlin/common/env/GeneratorLogger.kt
workers/common/src/main/kotlin/common/env/GitConfigGenerator.kt
workers/common/src/main/kotlin/common/env/GitCredentialsGenerator.kt
workers/common/src/main/kotlin/common/env/MavenSettingsGenerator.kt
workers/common/src/main/kotlin/common/env/NetRcGenerator.kt
workers/common/src/main/kotlin/common/env/NpmRcGenerator.kt
workers/common/src/main/kotlin/common/env/NuGetGenerator.kt
workers/common/src/main/kotlin/common/env/YarnRcGenerator.kt

This commit extends logging on generated configuration files:
- .gitconfig
- .git-credentials
- .netrc
- .npmrc
- .yarnrc.yml
- NuGet.Config
- settings.xml (Maven) 
It helps on debug / troubleshooting when it's uncertain if file was generated, and what settings it contains.

feat(logs): Extend logging on generated files

---

services/hierarchy/src/main/kotlin/OrphanRemovalService.kt
services/hierarchy/src/test/kotlin/OrphanRemovalServiceTest.kt
tasks/src/main/resources/application.conf

Introduce a periodic cleanup mechanism to remove Snippets that are no longer associated with any SnippetFindings. This helps prevent unnecessary data accumulation and keeps the database clean. Being able to define a `limit` and a `chunkSize` allows to make sure that there is only little risk that the memory blows up when orphan snippets are looked up and that database limits are reached in the delete statement concerning the maximal allowed length of a SQL statement and the maximum number of operations allowed in a single database transaction.
Looking at the tests, Exposed creates the following SQL statements to find Snippet orphans (tests have a limit setting of 10):
````
SELECT snippets.id FROM snippets WHERE NOT EXISTS (
SELECT 1 FROM snippet_findings_snippets WHERE …
```

feat(services): Add a handler for orphaned snippets

---

core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/utils/Utils.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt

Differentiate between plugins which are not installed and plugins which are disabled when checking if the plugins used in an ORT run are available. Previously, also not installed plugins were reported as disabled.

feat(core): Improve error message for unavailable plugins

---

config/git/src/main/kotlin/GitConfigFileProvider.kt
config/git/src/test/kotlin/GitConfigFileProviderTest.kt

When updating the working tree, `GitConfigFileProvider` silently ignored exceptions that may be caused for instance by invalid credentials or a non-existing branch. This made it hard to diagnose such problems. So, throw corresponding exceptions to produce meaningful error logs.

fix(git-config): Do not swallow exceptions

---

buildSrc/src/main/kotlin/ort-server-base-conventions.gradle.kts

ORT and the ORT Server are often developed in parallel. To allow using non-published versions, the local maven repository is added as a source for dependencies of the `org.ossreviewtoolkit` group.

build: Allow the local maven repository for ORT dependencies

---

ui/src/components/charts/cvss23-radar-chart.tsx
ui/src/components/charts/cvss4-radar-chart.tsx
ui/src/components/charts/vulnerability-metrics.tsx
ui/src/helpers/vulnerability-statistics.ts

More scores are now available from the `metaeffect CVSS calculator` for CVSS 4.0 vectors, so take them into use.
1. Tweak the general look and feel of the radar charts by providing a slight opaque shadowing to the spanned area, and marking all data points (not only those with true data) with dots:
(Note for @sschuberth: I tried numerous ways of showing the numerical tick labels for the radial axis, but sadly couldn't make it work without the numbers overlapping/crowding the view, so I left the feature to future investigation.)
2. Show the radar chart and macrovector corresponding to a CVSS 4.0 vulnerability vector in tabs:
This is a hard-coded example which is also presented by the author of the `metaeffect CVSS calculator` [here](https://metaeffekt.com/security/cvss/calculator/?vector=%5B …

ui: CVSS 4.0 radar charts

---

.gitignore

The directory can also temporarily exist in subdirectories.

chore: Ignore `.kotlin` directories not only in root

---

core/src/main/kotlin/di/Module.kt
tasks/src/main/kotlin/TaskRunner.kt
workers/reporter/src/main/kotlin/reporter/ReporterComponent.kt

Different `Storage`s could be use by different services, so do not add them to the Koin context to avoid that a service accidentally uses the wrong `Storage`. This also is more consistent because in modules that define multiple `Storage`s only one of them was added to the context.

refactor: Do not add storages to the Koin context

---

dao/src/main/kotlin/repositories/analyzerjob/AnalyzerJobsTable.kt
dao/src/main/kotlin/repositories/analyzerrun/AnalyzerConfigurationsPackageManagerConfigurationsTable.kt
dao/src/main/kotlin/repositories/analyzerrun/AnalyzerConfigurationsTable.kt
dao/src/main/kotlin/repositories/analyzerrun/AnalyzerRunsTable.kt
dao/src/main/kotlin/repositories/analyzerrun/DaoAnalyzerRunRepository.kt
dao/src/main/kotlin/repositories/analyzerrun/PackagesAnalyzerRunsTable.kt
dao/src/main/kotlin/repositories/analyzerrun/PackagesAuthorsTable.kt
dao/src/main/kotlin/repositories/analyzerrun/PackagesDeclaredLicensesTable.kt
dao/src/main/kotlin/repositories/analyzerrun/PackagesTable.kt
dao/src/main/kotlin/repositories/analyzerrun/ProcessedDeclaredLicensesTable.kt
dao/src/main/kotlin/repositories/analyzerrun/ProjectScopesTable.kt
dao/src/main/kotlin/repositories/analyzerrun/ProjectsAnalyzerRunsTable.kt
dao/src/main/kotlin/repositories/analyzerrun/ProjectsAuthorsTable.kt
dao/src/main/kotlin/repositories/analyzerrun/ProjectsDeclaredLicensesTable.kt
dao/src/main/kotlin/repositories/analyzerrun/ProjectsTable.kt
dao/src/main/kotlin/tables/shared/EnvironmentsTable.kt
dao/src/main/kotlin/tables/shared/EnvironmentsToolVersionsTable.kt
dao/src/main/kotlin/tables/shared/EnvironmentsVariablesTable.kt
dao/src/main/kotlin/tables/shared/OrtRunsIssuesTable.kt
workers/common/src/test/kotlin/common/OrtRunServiceTest.kt

Add queries to bulk load the contents of an `AnalyzerRun` and use that instead of the `AnalyzerRunDao` in the `DaoAnalyzerRunRepository`.
The DAO suffers from the N + 1 problem because an `AnalyzerRun` contains several nested objects and the Exposed DAO API creates lots of separate queries to load them. Depending on the amount of projects and packages in an `AnalyzerRun` this can easily result in several thousand executed queries.
The new approach solves the N + 1 problem by bulk loading the data from the one-to-many relations: For example, the authors for all packages are loaded in a single query and then associated to the packages in memory. This results in a constant amount of executed queries, independent of the number of projects or packages in the `AnalyzerRun`.
Loading all data in …

feat(dao): Improve performance of loading analyzer runs

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/JobConfigurations.kt
dao/src/main/kotlin/tables/NestedProvenancesTable.kt
dao/src/main/resources/db/migration/V105__addNestedProvenancesConfiguration.sql
model/src/commonMain/kotlin/JobConfigurations.kt
workers/scanner/src/main/kotlin/scanner/OrtServerNestedProvenanceStorage.kt
workers/scanner/src/main/kotlin/scanner/ScannerRunner.kt
workers/scanner/src/test/kotlin/OrtServerNestedProvenanceStorageTest.kt
workers/scanner/src/test/kotlin/ScannerRunnerTest.kt

Introduce `submoduleFetchStrategy` config to control how the Scanner fetches Git submodules. When set to `TOP_LEVEL_ONLY`, only top-level submodules are fetched, avoiding timeouts on deeply nested repos.
This mirrors the behavior already available in the Analyzer and allows to resolve nested provenances even in this kind of repositories with a vast amount of nested submodules.
If activated, in the logs you will no longer see the `--recursive` flag in the `gib submodule update` command then:
````
Running 'git submodule update --init --depth 50' in '/tmp/ort-DefaultWorkingTreeCache13286267791034354700'..."
````
If particular VCS plugin configurations are active during a scan (like `submoduleFetchStrategy=TOP_LEVEL_ONLY`),
ensure that VCS plugin configurations are stored alongside nested …

feat(scanner): Add submodule fetch strategy for nested repositories

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts

When rerunning a scan with **no** selected package managers selected, don't send 'Unmanaged' as the package manager, but instead don't send a list of enabled package managers at all to the backend. This allows ORT Server to fall back to its default behavior of using **all** installed package managers.
This solves issues where scans were rerun, but all of a sudden where no longer analyzed by some package managers.

fix(ui): Don't use 'Unmanaged' when no package manager is selected

---

ui/src/components/delete-dialog.tsx

If there is no `itemName`, do not show a space before a comma.

fix(ui): Do not show a space before a comma

---

buildSrc/src/main/kotlin/ort-server-kotlin-jvm-conventions.gradle.kts

This fixes the issue that the custom `MdcConverter` was not on the classpath when running tests in several modules resulting in an exception from Logback.

test: Add `:utils:logging` as test dependency to all JVM modules

---

cli/build.gradle.kts

Just enabling `optimized` clashes with the default of `debuggable` also being enabled, resulting in a compiler warning saying
Unsupported combination of flags: -opt and -g. Please pick one.
Instead of disabling `debuggable`, use the proper way to configure the build type(s) [1], which takes care of mutually setting these options.

fix(cli): Properly configure the release build

---

cli/src/commonMain/kotlin/StartCommand.kt
integrations/completions/osc-completion.bash
integrations/completions/osc-completion.fish
integrations/completions/osc-completion.zsh

Because Clikt doesn't support the `file` and `path` parameter types on
Kotlin native [1], we have to use a String parameter.
This means that the `--parameter-file` option doesn't offer any
tab-completion options.
Fix this by explicitly defining paths as completion candidates.
[1]: https://ajalt.github.io/clikt/advanced/#jvm

fix(cli): Enable path completion for `--parameters-file` option

---

shared/reporters/src/main/kotlin/OrtResultReporter.kt
shared/reporters/src/main/kotlin/RunStatisticsReporter.kt
shared/reporters/src/main/kotlin/SourceCodeBundleReporter.kt

Follow an ORT change [1] and do not repeat the plugin type as part of the display name, which avoids duplication when listing plugins by type, like in the administration UI.
[1]: https://github.com/oss-review-toolkit/ort/pull/10190/commits/dc690ea12e0a229c52099772e8f00434eb457196

chore(reporters): Omit the plugin type from the display name

---

components/admin-config/backend/src/main/kotlin/Routing.kt
components/admin-config/backend/src/main/kotlin/endpoints/GetConfigByKey.kt
components/admin-config/backend/src/main/kotlin/endpoints/InsertOrUpdateConfig.kt
components/plugin-manager/implementation/src/main/kotlin/Routing.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/DisablePlugin.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/EnablePlugin.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/GetInstalledPlugins.kt
core/src/main/kotlin/plugins/Routing.kt

Add helper functions that add all routes for a component to simplify the routing in `core`. This also allows to make the actual route functions internal.

refactor: Add helper functions to group routes in components

---

core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/apiDocs/OrganizationsDocs.kt
core/src/main/kotlin/apiDocs/ProductsDocs.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/users/-components/repository-users-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/users/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/users/-components/product-users-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/users/index.tsx
ui/src/routes/organizations/$orgId/users/-components/organization-users-table.tsx
ui/src/routes/organizations/$orgId/users/index.tsx

Update user removal from Keycloak groups to pass the username as a request parameter rather than placing it in the DELETE request body. Bodies in DELETE requests are discouraged and cause issues in our company cloud infrastructure with intermediate API proxies.

fix(api): Move username to query param in Keycloak group removal

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/vulnerabilities/index.tsx

This PR is a temporary means to advance towards the goal of showing either PURLs or ORT IDs everywhere throughout the UI. Once the endpoints return PURLs (and possibly, whether the item was triggered by a project or package), we will follow-up with a proper implementation in the UI.
Relates to #2176, #2340, #2878.

ui: Show PURL for vulnerabilities if so configured

---

clients/keycloak/src/main/kotlin/DefaultKeycloakClient.kt
clients/keycloak/src/main/kotlin/KeycloakClient.kt
clients/keycloak/src/testFixtures/kotlin/KeycloakTestClient.kt
core/src/main/kotlin/di/Module.kt
services/authorization/src/main/kotlin/UserService.kt
services/authorization/src/test/kotlin/UserServiceTest.kt

Fix user membership queries to include the Keycloak group prefix when listing users in _Organization_, _Product_, or _Repository_ groups. This prevents incorrect results when multiple ORT Server instances share the same Keycloak realm.
This bug came up in an environment where a productive ORT Server instance and a development ORT Server instance shared the same Keycloak realm. In the ORT Server UI's User page, users showed up in the list that actually did not have an group membership on the production environment.

fix(services): Respect group prefix when querying Keycloak members

---

.github/workflows/release.yml
buildSrc/src/main/kotlin/ort-server-publication-conventions.gradle.kts

The Eclipse Foundation has migrated the accounts to the new portal [1].
[1]: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5854#note_4174244
~Currently a draft because the GitHub secrets are not yet updated:
https://otterdog.eclipse.org/projects/technology.apoapsis#secrets~

build(gradle): Switch publishing to new Maven Central portal

---

.github/actions/free-disk-space/action.yml
.github/workflows/docker-build.yml
workers/analyzer/docker/Analyzer.Dockerfile

The used environment variables are not defined in the stages where they are used, so replace them with the actual values.

fix(analyzer): Fix warning about undefined variables in Docker build

---

clients/keycloak/src/main/kotlin/KeycloakClientConfiguration.kt
clients/keycloak/src/testFixtures/kotlin/Extensions.kt
core/src/main/kotlin/api/AuthenticationRoute.kt
core/src/main/kotlin/utils/Extensions.kt
core/src/main/resources/application.conf

Introduce dedicated properties for the `baseUrl` and `realm`, which otherwise are only encoded in the `apiUrl` and `accessTokenUrl` properties.
Having `baseUrl` and `realm` available separately is a preparation for migrating to the official Keycloak client which needs these.

refactor: Add `baseUrl` and `realm` to `KeycloakClientConfiguration`

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/JobConfigurations.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
dao/src/testFixtures/kotlin/Fixtures.kt
model/src/commonMain/kotlin/JobConfigurations.kt
services/admin-config/build.gradle.kts
services/admin-config/src/main/kotlin/AdminConfig.kt
services/admin-config/src/main/kotlin/AdminConfigService.kt
services/admin-config/src/main/kotlin/RuleSet.kt
services/admin-config/src/test/kotlin/AdminConfigServiceTest.kt
settings.gradle.kts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/evaluator-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/config/-components/evaluator-job-details.tsx
workers/common/build.gradle.kts
workers/common/src/main/kotlin/common/Extensions.kt
workers/common/src/main/kotlin/common/context/WorkerContextModule.kt
workers/config/build.gradle.kts
workers/config/src/main/kotlin/ConfigValidator.kt
workers/config/src/main/kotlin/ConfigWorker.kt
workers/config/src/test/kotlin/ConfigValidatorTest.kt
workers/config/src/test/kotlin/ConfigWorkerTest.kt
workers/evaluator/build.gradle.kts
workers/evaluator/src/main/kotlin/evaluator/EvaluatorRunner.kt
workers/evaluator/src/test/kotlin/EvaluatorRunnerTest.kt
workers/evaluator/src/test/kotlin/EvaluatorWorkerTest.kt
workers/reporter/src/main/kotlin/reporter/ReporterRunner.kt

This PR starts with moving properties from job configurations to a new admin configuration as described in https://github.com/eclipse-apoapsis/ort-server/issues/2901. It does this on all layers for the Evaluator configuration to have an initial admin configuration available and a proof of concept for this approach. Similar exercises then need to be done for the other workers.

Introduce admin configuration

---

dao/src/main/kotlin/repositories/infrastructureservice/DaoInfrastructureServiceDeclarationRepository.kt
dao/src/main/kotlin/repositories/infrastructureservice/DaoInfrastructureServiceRepository.kt
dao/src/main/kotlin/repositories/infrastructureservice/InfrastructureServiceDeclarationsRunsTable.kt
dao/src/main/kotlin/repositories/infrastructureservice/InfrastructureServiceDeclarationsTable.kt
dao/src/main/resources/db/migration/V110__addInfrastructureServiceDeclarations.sql
dao/src/test/kotlin/repositories/infrastructureservice/DaoInfrastructureServiceRepositoryTest.kt
dao/src/test/kotlin/repositories/infrastructureservice/InfrastructureServiceDeclarationRepositoryTest.kt
dao/src/testFixtures/kotlin/Fixtures.kt
model/src/commonMain/kotlin/InfrastructureService.kt
model/src/commonMain/kotlin/InfrastructureServiceDeclaration.kt
model/src/commonMain/kotlin/repositories/InfrastructureServiceDeclarationRepository.kt
model/src/commonMain/kotlin/repositories/InfrastructureServiceRepository.kt
workers/analyzer/src/test/kotlin/AnalyzerEndpointTest.kt
workers/common/src/main/kotlin/common/env/EnvironmentModule.kt
workers/common/src/main/kotlin/common/env/EnvironmentService.kt
workers/common/src/test/kotlin/common/env/EnvironmentServiceTest.kt
workers/common/src/test/kotlin/common/env/MockConfigFileBuilder.kt

Persist **Infrastructure Service Declarations**. These are
* created dynamically on the fly from _.ort.env.yml_ files in the source repository and associated
directly to the current ORT run. 
* referencing secrets **by name** (unlike existing infrastructure services which have a foreign key relationship to secrets). This allows that Secrets can be deleted, even when referenced. An ORT Run will fail if Secrets cannot be resolved by name at runtime.
* using some logic to look up the Secrets by name, searching on levels Repository --> Product --> Organization and writing warnings to the log if there is ambiguity detected
* not having attributes _organization_ or _product_, because the related ORT run specifies to which Organization or Product they belong to.
In contract to this, the existing …

feat(services): Add support for dynamic infrastructure services

---

components/secrets/backend/src/test/kotlin/routes/organization/DeleteSecretByOrganizationIdAndNameIntegrationTest.kt
components/secrets/backend/src/test/kotlin/routes/product/DeleteSecretByProductIdAndNameIntegrationTest.kt
core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/infrastructureservice/DaoInfrastructureServiceRepository.kt
dao/src/test/kotlin/repositories/infrastructureservice/DaoInfrastructureServiceRepositoryTest.kt
dao/src/test/kotlin/repositories/infrastructureservice/InfrastructureServiceDeclarationRepositoryTest.kt
model/src/commonMain/kotlin/repositories/InfrastructureServiceRepository.kt
services/infrastructure/src/main/kotlin/InfrastructureServiceService.kt
services/infrastructure/src/test/kotlin/InfrastructureServiceServiceTest.kt
workers/common/src/main/kotlin/common/env/config/EnvironmentConfigLoader.kt
workers/common/src/test/kotlin/common/env/config/EnvironmentConfigLoaderTest.kt

Refactoring only: Replace duplicated service functions for Infrastructure Services at _Organization_ and _Product_ levels with a shared approach based on the existing `Hierarchy` abstraction. This reduces **code duplication** and simplifies maintenance.
This change removes duplicate code sections for _Organizations_ and _Products_ by using the already existing concept of `Hierarchy` and `HierarchyId`. It prepares the introduction of additional functionality on _Repository_ level, that would have led to even more code duplication in future.

refactor(services): Unify Infrastructure Service logic using Hierarchy concept

---

ui/src/components/header.tsx
ui/src/components/siblings.tsx

This PR introduces a "shortcut" navigation to sibling organizations, products, repositories and runs to the breadcrumb. 
@sschuberth I decided to keep the down carets in the breadcrumb in case there are siblings available on server, to simplify the logic of this feature combined with the earlier feature of not showing upper-level entities in breadcrumb for technical users that do not have access rights to upper-level entities.
I also tested that the breadcrumb works as intended also for the said technical users, which only have access to some lower-level entities such as product/repository.
1. This user only has access rights to one particular product (Semver).  No sibling products are shown in the breadcrumb, as intended.
2. This user only has access rights to one particular repository …

ui: Sibling navigation in breadcrumb

---

core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
dao/src/main/kotlin/repositories/infrastructureservice/DaoInfrastructureServiceRepository.kt
dao/src/main/kotlin/repositories/infrastructureservice/InfrastructureServicesTable.kt
dao/src/main/resources/db/migration/V111__addRepositoryLevelToInfrastructureServices.sql
dao/src/test/kotlin/repositories/infrastructureservice/DaoInfrastructureServiceRepositoryTest.kt
dao/src/test/kotlin/repositories/infrastructureservice/InfrastructureServiceDeclarationRepositoryTest.kt
model/src/commonMain/kotlin/InfrastructureService.kt
model/src/commonMain/kotlin/repositories/InfrastructureServiceRepository.kt
workers/common/src/main/kotlin/common/env/EnvironmentForkHelper.kt
workers/common/src/main/kotlin/common/env/EnvironmentService.kt
workers/common/src/main/kotlin/common/env/config/EnvironmentConfigLoader.kt
workers/common/src/test/kotlin/auth/OrtServerAuthenticatorTest.kt
workers/common/src/test/kotlin/common/context/WorkerContextFactoryTest.kt
workers/common/src/test/kotlin/common/env/EnvironmentForkHelperTest.kt
workers/common/src/test/kotlin/common/env/EnvironmentServiceTest.kt
workers/common/src/test/kotlin/common/env/MockConfigFileBuilder.kt
workers/common/src/test/kotlin/common/env/config/EnvironmentConfigLoaderTest.kt

Add functionality to manage Infrastructure Services on Repository level.
This change also contains a commit that ...
- makes use of the existing `Hierarchy` data class to simplify the call to `listForHierarchy`
- removes obsolete code in the `InfrastructureServiceDAO` that is no longer used since the introduction of `InfrastructureServiceDeclaration`. (With #2957, the respective code went to `InfrastructureServiceDeclarationDao`).

feat(api): Add Infrastructure Services on Repository level

---

config/git/src/main/kotlin/GitConfigFileProviderAuthenticator.kt

It can happen that while `GitConfigFileProviderAuthenticator` is active for the checkout of the config repository, ORT's authenticator is installed. This breaks the chain of temporary authenticators, and the original one (typically the custom authenticator for ORT Server) is not enabled again. Afterward authentication in ORT Server is broken.
As a quick fix, let `GitConfigFileProviderAuthenticator` extend `OrtAuthenticator`. This prevents another installation of ORT's authenticator. A better fix may be added later to make the collaboration of the involved authenticators more robust.

fix(config): Fix an issue with collaborating authenticators

---

ui/src/components/siblings.tsx

This PR changes the logic of the `Siblings` component to resemble more closely a select type of dropdown, where the currently active sibling is not filtered out of the list, but instead indicated with a check mark.
Moreover, some fixes to query logic are included.

ui: Minor changes and fixes to sibling navigation in breadcrumb

---

buildSrc/src/main/kotlin/ort-server-base-conventions.gradle.kts
settings.gradle.kts

The intention for using a local maven repository for ORT was to allow
changing the ORT version during development. [1] broke the current
approach to do this.
To restore the old behavior, add the local maven repository to the
dependency resolution management repositories definition.
Signed-off-by: Marcel Bochtler <marcel.bochtler@bosch.com>

build: Define local maven repository definition

---

services/admin-config/src/test/kotlin/AdminConfigServiceTest.kt

Use `with` and `shouldNotBeNull` to reduce redundancy in test code a bit.

test(admin-config): Reduce redundancy in test code

---

components/plugin-manager/implementation/src/main/kotlin/PluginTemplateService.kt
components/plugin-manager/implementation/src/main/kotlin/Routing.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/CreateTemplate.kt
components/plugin-manager/implementation/src/main/kotlin/endpoints/UpdateTemplateOptions.kt
components/plugin-manager/implementation/src/main/kotlin/queries/GetPluginTemplatesQuery.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/AddTemplateToOrganizationIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/CreateTemplateIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/DeleteTemplateIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/DisableGlobalTemplateIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/EnableGlobalTemplateIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/GetTemplateIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/GetTemplatesIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/RemoveTemplateFromOrganizationIntegrationTest.kt
components/plugin-manager/implementation/src/test/kotlin/endpoints/UpdateTemplateOptionsIntegrationTest.kt
ui/src/routes/admin/plugins/$pluginType/$pluginId/create-template/index.tsx
ui/src/routes/admin/plugins/$pluginType/$pluginId/index.tsx
ui/src/routes/admin/plugins/index.tsx
ui/src/routes/admin/plugins/route.tsx

Add the UI for managing plugin templates. This is a first version that needs improvements in presentation and error handling. Also, currently templates can not be edited, this will be added later. Note that plugin templates are still not applied when creating ORT runs, this will follow in another PR.

Plugin template UI

---

core/src/main/kotlin/api/ForbiddenConfigurationPropertyException.kt
core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/plugins/StatusPages.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt

Limit access to the _keepAliveWorker_ job configuration option to superusers only. This flag is useful for debugging by support or developers, but should not be exposed to regular users as it prevents worker shutdown and may lead to unnecessary resource usage.

feat(api): Restrict keepAliveWorker flag to superusers

---

core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt

Use `forAll` instead of a test matrix in the tests for the keep alive option. This reduces the duration of those tests from roughly 90 seconds to below 20 seconds, because the Keycloak realm is not recreated for every single API call.

test(core): Use `forAll` instead of a test matrix

---

workers/common/src/test/kotlin/common/env/ConanGeneratorTest.kt
workers/common/src/test/kotlin/common/env/GradleInitGeneratorTest.kt
workers/common/src/test/kotlin/common/env/NetRcGeneratorTest.kt
workers/common/src/test/kotlin/common/env/NpmRcGeneratorTest.kt
workers/common/src/test/kotlin/common/env/NuGetGeneratorTest.kt
workers/common/src/test/kotlin/common/env/YarnRcGeneratorTest.kt

chore(common): Migrate generator tests to use blocks for expected lines

---

.github/workflows/release.yml

This is supposed to be supported as of [1].
[1]: https://github.com/eclipse-apoapsis/ort-server/pull/3160

ci(github): Allow configuration caching when publishing

---

api/v1/mapping/src/commonMain/kotlin/Mappings.kt
api/v1/model/src/commonMain/kotlin/Vulnerability.kt
api/v1/model/src/commonMain/kotlin/VulnerabilityResolution.kt
core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/api/RunsRoute.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
core/src/main/kotlin/di/Module.kt
core/src/test/kotlin/api/RunsRouteIntegrationTest.kt
model/src/commonMain/kotlin/VulnerabilityRating.kt
model/src/commonMain/kotlin/VulnerabilityWithIdentifier.kt
services/ort-run/src/main/kotlin/OrtServerMappings.kt
services/ort-run/src/main/kotlin/VulnerabilityService.kt
services/ort-run/src/test/kotlin/VulnerabilityServiceTest.kt

If resolutions exist for vulnerabilities, add them to the respective vulnerabilities in the `api/v1/runs/{id}/vulnerabilities` endpoint. 
Add a request query parameter to support filtering vulnerabilities by their resolution status, to provide the possibility for clients to only query for relevant data.
For details, please check the commit messages of the respective commits.
For review: The change was split up into several commits. 
- The first commit is pure refactoring done by the IDE, it is just about moving a class to a different package.
- The second commit changes the way that vulnerabilities are looked up (using ORTRunService instead of querying the results directly from the database)
- The third commit adds support for adding resolutions to vulnerabilities
- The fourth commit adds …

Apply resolutions to vulnerablities endpoint

---

config/git/src/main/kotlin/GitConfigFileProvider.kt
config/git/src/test/kotlin/GitConfigFileProviderTest.kt
config/github/src/main/kotlin/GitHubConfigFileProvider.kt
config/github/src/test/kotlin/GitHubConfigFileProviderTest.kt
config/local/src/main/kotlin/LocalConfigFileProvider.kt
config/local/src/test/kotlin/LocalConfigFileProviderTest.kt
config/spi/src/main/kotlin/ConfigFileProvider.kt

This PR changes the `contains` implementation in config file providers to allow checking whether a path refers to an existing directory. This is needed for validation of the admin configuration.
Refer to the single commits for further details.

Improve ConfigFileProvider.contains

---

build.gradle.kts
gradle.properties

Enable the usage of Docker compatible container engines like Podman [1] by making the command configurable for the `buildAllImages` task.
[1]: https://podman-desktop.io/docs/migrating-from-docker/managing-docker-compatibility

build: Make the CLI command used to build containers configurable

---

core/src/main/kotlin/utils/Extensions.kt
core/src/test/kotlin/utils/ExtensionsTest.kt

The function will be used for validating plugin configs in a follow-up commit.

feat(core): Add a function to extract plugin configs from `CreateOrtRun`

---

ui/src/components/form/multi-select-field.tsx
ui/src/lib/types.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/advisor-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/reporter-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx

Use the endpoint from #3168 to populate the advisor and reporter lists in the create ORT run form. This is a small first step of applying the admin configuration for plugins to the form. The form will now show all installed plugins, except for those which are globally disabled.
Advisor section:
Reporter section:
Reporter section with some plugins globally disabled:

Use plugins endpoint for create ORT run form

---

workers/reporter/docker/Reporter.Dockerfile
workers/scanner/docker/Scanner.Dockerfile

ScanCode does not support to be installed on `ARM64` machines, see [1], [2] and [3].
Use `linux/amd64` base-images for any all images that install ScanCode to be able to build them on `ARM64` machines.
[1]: https://scancode-toolkit.readthedocs.io/en/stable/getting-started/install.html#system-requirements
[2]: https://github.com/aboutcode-org/scancode-toolkit/issues/3141
[3]: https://github.com/aboutcode-org/scancode-toolkit/issues/3958

chore(docker): Set `linux/amd64` platform for images that install ScanCode

---

ui/src/app.tsx
ui/src/components/providers.tsx
ui/src/config.ts
ui/src/hooks/use-user.ts
ui/src/lib/query-client.ts
ui/src/ui-env.ts

This PR adds a solution for handling errors in case of an expired session. The problem is two-fold, sometimes the automatic silent renewal fails and results to a "Something went wrong" error, this is handled by adding a handler for such errors. In some cases, for example if the session is manually killed in Keycloak, the API requests may start failing before the automatic renewal kicks in. Handling for such cases is added to the query client.
Also a debug logger is added and some improvements for the "Unable to log in" screen.

ui: Auth improvements

---

dao/src/main/kotlin/tables/ScanSummariesIssuesTable.kt
dao/src/test/kotlin/tables/ScanSummariesIssuesTableTest.kt

This commit normalizes timestamp precision to standard one used in ORT. Precision problem is caused by conversion between Java and Kotlin Instant type. Higher precision (nanosecons) has been introduced in Java 15 [1].
[1] https://bugs.openjdk.org/browse/JDK-8242504

fix: Adjust timestamp precision for database compatibility

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/advisor-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/analyzer-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/evaluator-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/notifier-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/reporter-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/scanner-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx

Add inputs for the `keepAliveWorker` flags for each job when creating an ORT run. The inputs are only shown for superusers because only they can use the flags.

feat(ui): Add inputs for `keepAliveWorker` flags

---

workers/scanner/src/main/kotlin/scanner/ScannerWorker.kt

Take the issues from `ScannerRun` into account when determining the job status.

fix(scanner): Account issues from failed scans to job status

---

ui/src/components/breakable-string.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/projects/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/vulnerabilities/index.tsx
ui/src/routes/organizations/$orgId/vulnerabilities/index.tsx

"Normal" situation with easily word-wrappable Package IDs:
A Package ID that cannot be word-wrapped with usual supported TailwindCSS classes:

ui: Wrap Package ID around ":" and "::" where needed

---

components/secrets/backend/build.gradle.kts
components/secrets/backend/src/main/kotlin/Routing.kt
components/secrets/backend/src/main/kotlin/routes/repository/GetAvailableSecretsByRepositoryId.kt
components/secrets/backend/src/test/kotlin/SecretsIntegrationTest.kt
components/secrets/backend/src/test/kotlin/routes/SecretsAuthorizationTest.kt
components/secrets/backend/src/test/kotlin/routes/repository/GetAvailableSecretsByRepositoryIdIntegrationTest.kt
core/src/main/kotlin/di/Module.kt
core/src/main/kotlin/plugins/Koin.kt
core/src/main/kotlin/plugins/Routing.kt
core/src/test/kotlin/ApplicationTest.kt
services/hierarchy/src/main/kotlin/RepositoryService.kt
services/hierarchy/src/test/kotlin/RepositoryServiceTest.kt
services/secret/build.gradle.kts
services/secret/src/main/kotlin/SecretService.kt
services/secret/src/test/kotlin/SecretServiceTest.kt

Add a route that returns all available secrets in the context of a repository. This will be used to implement drop-downs to select secrets when triggering a run via the UI.

Add route to get the available secrets for a repository

---

ui/src/components/charts/job-durations.tsx
ui/src/helpers/calculate-duration.ts

This PR was a required feature from @sschuberth: to separate and show the time spent on "infrastructure" (for example, spinning up a Kubernetes pod) from the "actual" running time of the jobs.
The main calculation principle in this PR is as follows:
```
infrastructureDuration = totalRunDuration - sum(jobDurations)
```
where `totalRunDuration` is calculated from `[createdAt, finishedAt]` of the run, and `jobDurations` is calculated from `[startedAt, finishedAt]` of each respective job. Advisor and Scanner are typically run in parallel, so the longer of those jobs is included in calculation.
As the DoubleOpen team doesn't know the deep details of the state machines of the jobs and runs, I'd like to ask @mnonnenmacher (or anyone else more familiar with the back-end implementation): is this a …

ui: Infrastructure durations

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx

Further improvements to this feature could be to change the reported advisor into a link to its homepage, but for now, it wasn't absolutely clear as to which pages to redirect to for each advisor.

ui: Show the advisor that reported the vulnerability

---

workers/reporter/src/main/kotlin/reporter/CustomLicenseTextProvider.kt
workers/reporter/src/test/kotlin/reporter/CustomLicenseTextProviderTest.kt

The implementation could not handle a license text directory parameter with a trailing slash. This is problematic, since the directory is now defined in the admin configuration which expects that directory paths end on a slash.

fix(reporter): Make `CustomLicenseTextProvider` more robust

---

.github/workflows/build-and-test.yml
.github/workflows/release.yml

By September 30, 2025, GitHub will make `windows-latest` point to `windows-2025` as the recommended Windows image. Get access to more modern tools already now by upgrading the image explicitly.

ci(github): Upgrade to the `windows-2025` image

---

services/admin-config/src/main/kotlin/ReporterConfig.kt
services/admin-config/src/test/kotlin/ReporterConfigTest.kt
workers/reporter/src/main/kotlin/reporter/ReporterRunner.kt
workers/reporter/src/test/kotlin/reporter/ReporterRunnerTest.kt

This PR allows to associate report definitions from the admin configuration with special plugin configurations. This makes it possible to call a reporter plugin multiple times with different options. This also fixes an issue where duplicate reports can be generated by template reporters.

Support plugin configurations for report definitions

---

cli/src/commonMain/kotlin/OrtServerMain.kt
cli/src/commonMain/kotlin/StartCommand.kt
cli/src/commonMain/kotlin/model/Exceptions.kt

When using the CLI in CI/CD the user want to immediately know if the run was successful or not. Therefore the CLI should return a non-zero exit code when the run finished with issues.
This aligns the behavior of `osc` with the ORT CLI, that also uses exit code 2 for runs with issues.

feat(cli): Use exit code 2 for ORT runs finishing with issues

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx

Please note that I did not mark this PR as resolving #3403 yet, because the issue still needs some discussion between the teams as to how to properly deduplicate and filter the vulnerabilities reported by different advisors.

ui: Move the Advisor info to a table column

---

services/admin-config/src/main/kotlin/ReporterConfig.kt
services/admin-config/src/test/kotlin/ReporterConfigTest.kt

Compare plugin IDs specified in report definitions in a case-insensitive way. This simplifies the configuration and prevents hard-to-diagnose errors when plugin options cannot be assigned correctly.

fix(admin-config): Support case-insensitive plugin IDs

---

ui/src/routes/admin/content-management/branding/-components/favicon-form.tsx
ui/src/routes/admin/content-management/branding/-components/footer-form.tsx
ui/src/routes/admin/content-management/branding/-components/home-icon-form.tsx
ui/src/routes/admin/content-management/branding/-components/product-name-form.tsx

The form for editing the different branding elements on Admin / Content Management / Branding page was using `defaultValues`, so when for example refreshing the page, updated values were not displayed correctly. 
Switching to `values` instead of `defaultValues` ensures that the form  always reflects the current values of the branding elements.

fix(ui): Show updated branding values correctly on edit

---

buildSrc/src/main/kotlin/ort-server-kotlin-conventions.gradle.kts

This allows the developer to use `./gradle detekt --auto-correct` to fix trivial formatting issues.

build: Enable Detekt's autoCorrect

---

api/v1/mapping/src/commonMain/kotlin/ApiMappings.kt
api/v1/model/src/commonMain/kotlin/Issue.kt
api/v1/model/src/commonMain/kotlin/RuleViolation.kt
api/v1/model/src/commonMain/kotlin/VulnerabilityWithDetails.kt
core/src/main/kotlin/apiDocs/RunsDocs.kt
model/src/commonMain/kotlin/VulnerabilityWithDetails.kt
model/src/commonMain/kotlin/runs/Issue.kt
model/src/commonMain/kotlin/runs/RuleViolation.kt
services/ort-run/src/main/kotlin/IssueService.kt
services/ort-run/src/main/kotlin/RuleViolationService.kt
services/ort-run/src/main/kotlin/VulnerabilityService.kt
services/ort-run/src/test/kotlin/IssueServiceTest.kt
services/ort-run/src/test/kotlin/RuleViolationServiceTest.kt
services/ort-run/src/test/kotlin/VulnerabilityServiceTest.kt

Add the purls in the responses for the run specific items if the item is related to a package. This doesn't yet contain returning purls for the organization and product vulnerabilities endpoints, as they need to be handled a bit differently.

Return purls for issues, rule violations and vulnerabilities of a run

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx

This PR is the UI counterpart for #3425.
1. In case ORT IDs have been chosen for the UI in Preferences, show them in every table.
2. If PURL has been chosen in the preferences, show it where applicable. This means that rule violations and issues arising from packages show PURL, and ORT ID is still shown for those arising from projects.
This picture shows the logic of 2. in the UI. I have also selected a text filter "ts" for the Package ID column, since it matches both some projects and packages, to show that the text filtering in the column still works:

ui: Show PURL from back-end directly in the UI

---

workers/analyzer/docker/Analyzer.Dockerfile

Some projects may have a hard build dependency on this crate (see [1]).
[1]: https://crates.io/crates/cargo-credential-netrc
See also https://github.com/oss-review-toolkit/ort/pull/10808.

feat(docker): Add cargo-credential-netrc to the Docker image

---

.github/workflows/build-and-test.yml

This makes it easier to configure them as required checks with Otterdog, otherwise the job names contain all matrix parameters.

ci: Add names for the CLI build jobs

---

build.gradle.kts
gradle/libs.versions.toml

Follow ORT in removing the `versions` plugin as the task to update dependencies has been fully taken over by Renovate. Local users may want to give [1] a try instead.
[1]: https://github.com/bishiboosh/caupain

build(gradle): Remove the `versions` plugin

---

core/build.gradle.kts

Adding a dependency on a feature variant of a module does not automatically add a dependency to the main part of the module (see the example at [1]). Add the missing project dependencies to prevent class not found exceptions at runtime.
This is a fixup for bd3754f.
[1]: https://docs.gradle.org/current/userguide/how_to_create_feature_variants_of_a_library.html#sec::consuming_feature_variants

fix(core): Add missing project dependencies

---

clients/keycloak/build.gradle.kts
config/spi/build.gradle.kts
dao/build.gradle.kts
gradle/libs.versions.toml
logaccess/spi/build.gradle.kts
secrets/spi/build.gradle.kts
secrets/vault/build.gradle.kts
storage/azure-blob/build.gradle.kts
storage/database/build.gradle.kts
storage/s3/build.gradle.kts
storage/spi/build.gradle.kts
transport/activemqartemis/build.gradle.kts
transport/rabbitmq/build.gradle.kts
transport/spi/build.gradle.kts
transport/sqs/build.gradle.kts
utils/config/build.gradle.kts

As of Kotest 6 all extensions follow the main versioning again, see [1]. Also fix the Testcontainers catalog name while at it.
Note that DAO `testFixtures` now require an explicit dependency on Hikari. Also, some deprecated extension can only be updated once [2] is released.
[1]: https://kotest.io/docs/extensions/test_containers.html#dependencies
[2]: https://github.com/kotest/kotest/pull/5079

build(gradle): Use Kotest 6 extensions

---

workers/analyzer/docker/Analyzer.Dockerfile

In some environments, Cargo is not able to write to $CARGO_HOME due to missing write permissions. This change ensures that the user running the container can access and modify the $CARGO_HOME directory.

fix(docker): Change access rights for the `$CARGO_HOME` directory

---

services/ort-run/src/main/kotlin/IssueService.kt
services/ort-run/src/main/kotlin/OrtRunService.kt

Loading the file lists is not necessary in order to access the needed functions in the `OrtResult` in this particular case. Add a `loadFileLists` flag for the `generateOrtResult` function to allow skipping the loading of the file lists, while still allowing to fetch other data from the database for the `ScannerRun` object.

refactor(services): Don't load file lists for result on IssueService

---

components/plugin-manager/backend/src/main/kotlin/PluginTemplateState.kt
components/plugin-manager/backend/src/test/kotlin/routes/DeleteTemplateIntegrationTest.kt

Make sure that the `isDeleted` flag is set to `false` if a plugin template is recreated that was previously deleted.

fix(plugin-manager): Reset the deleted flag when creating a template

---

ui/src/routes/admin/plugins/$pluginType/$pluginId/create-template/index.tsx
ui/src/routes/admin/plugins/$pluginType/$pluginId/index.tsx
ui/src/routes/admin/plugins/index.tsx
ui/src/routes/admin/plugins/route.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/index.tsx

This PR concludes the refactoring of the query client to use the hey-api instead of the old one.
After this PR and #3541 are merged, the old query client will be removed, and the error handling will be returned to have the more informative error messaged from back-end again.
This picture shows that the only import from the old query client is the `ApiError` which will be the topic of the final refactoring follow-up PR.

refactor(ui): Refactor plugins handling

---

ui/src/app.tsx
ui/src/components/charts/cvss4-vector-card.tsx
ui/src/components/charts/job-durations.tsx
ui/src/components/charts/vulnerability-metrics.tsx
ui/src/components/dependency-paths.tsx
ui/src/components/ort-run-job-status.tsx
ui/src/components/package-curation.tsx
ui/src/components/providers.tsx
ui/src/components/ui/user-group-row-actions.tsx
ui/src/helpers/calculate-duration.ts
ui/src/helpers/get-status-class.ts
ui/src/helpers/identifier-conversion.ts
ui/src/helpers/job-helpers.ts
ui/src/helpers/resolutions.ts
ui/src/helpers/role-helpers.ts
ui/src/helpers/sorting-functions.ts
ui/src/helpers/vulnerability-statistics.ts
ui/src/routes/organizations/$orgId/products/$productId/-components/product-violations-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-vulnerabilities-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/advisor-fields.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/-components/reporter-fields.tsx
ui/src/routes/runs/$runId/index.tsx
ui/src/schemas/index.ts

After this PR, the only parts of the UI not yet refactored are the ones touching the plugins handling, so once that part is refactored as well, a follow-up PR can remove the old query client, clean up the UI code, and return error handling to the former, more informative type.

refactor(ui): Refactor left-overs

---

ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx

Please see the commit for details (and wording of the tooltips, which is subject to discussion).
After a lengthy discussion with the DoubleOpen team, it was decided _not_ so show these "exception" flags when they are `false`, after all, to not overwhelm the user with package data which is "normal" (i.e. most of the packages are probably non-modified and contain the source in some form).

ui: Show metadata and modified flags for packages

---

dao/src/main/resources/db/migration/V116__deleteInfrastructureServiceDeclarationsCascade.sql
dao/src/test/kotlin/repositories/ortrun/DaoOrtRunRepositoryTest.kt

This constraint was missing for the
`infrastructure_service_declarations_ort_runs` table preventing the deletion of runs with associated infrastructure service declarations.

fix(dao): Add a missing ON DELETE CASCADE constraint

---

ui/src/helpers/get-issue-category.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx

NOTE: This kind of "dirty" UI fix very much emphasizes the need of #3587, as it becomes now very hard to work with columnized tables that are so crowded, and hacks are needed to resolve the overflow issues.

fix(ui): Fix some problems with the issues table

---

api/v1/client/src/commonMain/kotlin/HttpClientUtils.kt
api/v1/client/src/jvmTest/kotlin/HttpClientUtilsTest.kt

Install and configure the `HttpRequestRetry` plugin [1] on the default HTTP client used by the ORT Server client to retry GET requests that failed due to a 504 response. This makes the client more stable in environments with an unreliable network infrastructure or if the server experiences load peaks.
[1]: https://ktor.io/docs/client-request-retry.html

feat(client): Support retries for timed out requests

---

ui/.gitignore
ui/src/components/data-table-cards/data-table-cards-header.tsx
ui/src/components/data-table-cards/data-table-cards-sort.tsx
ui/src/components/data-table-cards/data-table-cards.tsx
ui/src/components/data-table/data-table-filter.tsx
ui/src/components/data-table/filter-multi-select.tsx
ui/src/components/data-table/filter-regex.tsx
ui/src/components/data-table/filter-text.tsx
ui/src/components/ui/badge-variants.ts
ui/src/helpers/handle-multisort.ts
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx

This PR starts implementation of #3587, by introducing a new "card table" component along with providing refactorization of packages table into the new layout as an example.
Card table is implemented with minimal changes to the column tables, by 
1. Rendering all data in one column
2. Implementing sorting and filtering of that column by retaining the sorting and filtering properties of sorted/filtered columns in `columns` object
3. Hiding the sorting/filtering columns
As those columns don't render any data and are marked as hidden, performance impact will be negligible.
Reviewers of the PR are kindly asked to concentrate more to the table and component structure than the details of the cards themselves, as those can very easily be changed in follow-up PRs. Packages is not the most …

ui: Introduce a new card table

---

ui/src/components/data-table/data-table-body.tsx
ui/src/lib/constants.ts
ui/src/routes/organizations/$orgId/-components/organization-product-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-repository-table.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/issues/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/packages/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/projects/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/rule-violations/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/vulnerabilities/index.tsx

Change all tables to use the new card layout, to fit more data to the tables and present them in a nicer form.

ui: Refactor all tables in ORT run details pages

---

cli/src/commonMain/kotlin/StartCommand.kt
cli/src/jvmTest/kotlin/StartCommandTest.kt

Do not fail the waiting loop for the first error on a status check, but
only if there are multiple failures in sequence. This makes the polling
more stable against temporary network glitches.

feat(cli): Make waiting for a run more robust

---

api/v1/client/src/commonMain/kotlin/api/RepositoriesApi.kt
api/v1/client/src/jvmTest/kotlin/RepositoriesApiTest.kt
api/v1/model/src/commonMain/kotlin/ContentManagementSection.kt
api/v1/model/src/commonMain/kotlin/Organization.kt
api/v1/model/src/commonMain/kotlin/OrtRun.kt
api/v1/model/src/commonMain/kotlin/Product.kt
api/v1/model/src/commonMain/kotlin/Repository.kt
api/v1/model/src/commonMain/kotlin/User.kt
cli/src/commonMain/kotlin/StartCommand.kt
core/src/main/kotlin/api/AdminRoute.kt
core/src/main/kotlin/api/OrganizationsRoute.kt
core/src/main/kotlin/api/ProductsRoute.kt
core/src/main/kotlin/api/RepositoriesRoute.kt
core/src/main/kotlin/apiDocs/AdminDocs.kt
core/src/main/kotlin/apiDocs/OrganizationsDocs.kt
core/src/main/kotlin/apiDocs/ProductsDocs.kt
core/src/main/kotlin/apiDocs/RepositoriesDocs.kt
core/src/main/kotlin/plugins/Validation.kt
core/src/main/kotlin/utils/Extensions.kt
core/src/test/kotlin/api/AdminRouteIntegrationTest.kt
core/src/test/kotlin/api/OrganizationsRouteIntegrationTest.kt
core/src/test/kotlin/api/ProductsRouteIntegrationTest.kt
core/src/test/kotlin/api/RepositoriesRouteIntegrationTest.kt
core/src/test/kotlin/utils/ExtensionsTest.kt
ui/src/routes/admin/users/create-user/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/_repo-layout/create-run/-create-run-utils.ts

As requested by @mnonnenmacher [here](https://github.com/eclipse-apoapsis/ort-server/pull/3647#pullrequestreview-3305080465), align the request objects with the new refactored operation IDs. This will make the `openapi.json` contract between the front-end and back-end even cleaner.

api: Align request objects with operation IDs in apiDocs

---

.github/workflows/static-analysis.yml

This has the benefit of Renovate-based updates to specific versions.

ci(github): Use the `reuse-action` instead of calling `lint` manually

---

ui/src/components/charts/cvss23-radar-chart.tsx
ui/src/components/charts/cvss4-radar-chart.tsx
ui/src/components/charts/epss-chart.tsx
ui/src/components/color-theme-toggle.tsx
ui/src/components/header.tsx
ui/src/components/mode-toggle.tsx
ui/src/components/providers.tsx
ui/src/components/theme-provider-state.tsx
ui/src/components/theme-provider.tsx
ui/src/globals.css
ui/src/lib/types.ts
ui/src/routes/organizations/$orgId/-components/organization-issues-statistics-card.tsx
ui/src/routes/organizations/$orgId/-components/organization-packages-statistics-card.tsx
ui/src/routes/organizations/$orgId/-components/organization-violations-statistics-card.tsx
ui/src/routes/organizations/$orgId/-components/organization-vulnerabilities-statistics-card.tsx
ui/src/routes/organizations/$orgId/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-issues-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-packages-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-violations-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/-components/product-vulnerabilities-statistics-card.tsx
ui/src/routes/organizations/$orgId/products/$productId/index.tsx
ui/src/routes/organizations/$orgId/products/$productId/repositories/$repoId/runs/$runIndex/sbom/index.tsx

This PR lays the groundwork for theming in the UI. Existing themes can be easily changed and new themes can be added to `globals.css`.
The old theme is still the default, so the users shouldn't see any difference, if they don't deliberately change the theme in the selector in the header.
New themes are added with the free tool [shadcn Theme Generator](https://www.shadcn.io/theme-generator), which is encouraged to try out by any interested parties.

ui: Add support for theming
